// Code generated by plane/gen; DO NOT EDIT.

// Package integration is the typed client for the "integration" app's internal ops.
//
// Every call here is a ZAP call BY NAME over the peer's unix socket — no URL, no
// env var, no HTTP round trip, and no way to reach the public edge by accident.
// That last one is not a style preference: integration's own callers used to reach it
// through CLOUD_COMMERCE_HTTP_URL, which defaulted to the api.hanzo.ai edge —
// the SAME binary — so the forwarder re-entered itself and the billing gate died
// of it. A call by name cannot express that mistake.
//
// It depends on the CONTRACT (package plane) and never on integration's implementation,
// so importing it costs a caller nothing but the types it is already sending.
package integration

import (
	"context"

	"github.com/hanzoai/cloud/plane"
)

// App is the peer's name, which is also the socket it answers on. It is the
// ONE place this package spells it.
const App = "integration"

// Ops is every op this peer answers, in the spelling the wire uses.
//
// It exists so a test can hold this generated surface against the LIVE plane
// registry and fail when they disagree — which is what lets this be generated
// from source without the document drifting away from the program. See
// plane_registry_test.go.
var Ops = []string{
	plane.ChatIdentity,
	plane.ChatSend,
	plane.IntegrationsConnection,
	plane.IntegrationsSlackSend,
}

// ChatIdentity resolve the Hanzo account a chat user has linked.
//
// Calls plane.ChatIdentity on integration over the peer plane.
func ChatIdentity(ctx context.Context, in *plane.ChatIdentityIn) (*plane.ChatIdentityOut, error) {
	return plane.Ask[plane.ChatIdentityIn, plane.ChatIdentityOut](ctx, App, plane.ChatIdentity, in)
}

// ChatSend post one message back to a chat platform as the org.
//
// Calls plane.ChatSend on integration over the peer plane.
func ChatSend(ctx context.Context, in *plane.ChatSendIn) (*plane.ChatSendOut, error) {
	return plane.Ask[plane.ChatSendIn, plane.ChatSendOut](ctx, App, plane.ChatSend, in)
}

// IntegrationsConnection whether the caller's org has connected a provider.
//
// Calls plane.IntegrationsConnection on integration over the peer plane.
func IntegrationsConnection(ctx context.Context, in *plane.ConnectionIn) (*plane.Connection, error) {
	return plane.Ask[plane.ConnectionIn, plane.Connection](ctx, App, plane.IntegrationsConnection, in)
}

// IntegrationsSlackSend post to an org's Slack channel via the org's KMS-custodied bot token.
//
// Calls plane.IntegrationsSlackSend on integration over the peer plane.
func IntegrationsSlackSend(ctx context.Context, in *plane.SlackSendIn) (*plane.SlackSent, error) {
	return plane.Ask[plane.SlackSendIn, plane.SlackSent](ctx, App, plane.IntegrationsSlackSend, in)
}
