apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud.fullname" . }}
  labels: {{- include "cloud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "cloud.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: cloud
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--brand={{ .Values.hanzo.brand }}"
            - "--domain={{ .Values.hanzo.domain }}"
            - "--data-dir={{ .Values.hanzo.dataDir }}"
            - "--iam-issuer={{ .Values.hanzo.iamIssuer }}"
            - "--enable={{ .Values.hanzo.enable }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - name: zap
              containerPort: 9653
              protocol: TCP
          livenessProbe: {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe: {{- toYaml .Values.probes.readiness | nindent 12 }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.hanzo.dataDir }}
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "cloud.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
