apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud.fullname" . }}
  labels: {{- include "cloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
    - name: zap
      port: {{ .Values.service.zapPort }}
      targetPort: zap
      protocol: TCP
  selector: {{- include "cloud.selectorLabels" . | nindent 4 }}
