// Code generated by zipdoc; DO NOT EDIT.

package websearch

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("POST /v1/websearch", zip.Doc{
		Description: "Searches the live web and answers with ranked results.\n\nThis is the fleet's path to what is happening RIGHT NOW — today's weather, an\noutage, a release that postdates any model's training. `q` is the query and\n`language` narrows it to a locale. The answer is `{query, number_of_results,\nresults:[{url, title, content, engine}]}`, where `content` is the ENGINE's\nsnippet and not the page: read a page with POST /v1/crawl.\n\nIt is served in-process by a Go meta-search over keyless public engines — never\na third-party search API and never a search key. The enabled engines run\nconcurrently and their hits are merged, deduplicated by normalised URL (host\nand path, trailing slash and fragment dropped, query kept, so distinct queries\nstay distinct results) and capped at 30. Ranking is deterministic rather than\nscored: the first configured engine's hits lead.\n\nIt fails SOFT on the engines. One that errors, times out or is served a\nbot-challenge page contributes zero results and never fails the call, so an\nempty `results` is a real answer — nothing was found — and not an outage. The\narray is always present, never null.\n\nA VALIDATED PRINCIPAL IS REQUIRED, and there is no tenant beyond that: the\nresults are public web pages, identical for every caller, so nothing here is\nscoped and nothing here can leak across orgs. A typed op is also an MCP tool\nand a CLI command, and tools/call invokes it with no route and therefore no\nmiddleware — so the gate is in the handler, where every caller reaches it,\nrather than in a middleware only one caller passes through.",
		Fields: map[string]string{
			"webEngine.name":                     "Name is the engine, matching the `engine` stamped on each result.",
			"webEngine.outcome":                  "Outcome is \"answered\", \"blind\" or \"failed\" — see outcome.go. \"blind\" means\nthe page came back and no results could be read out of it.",
			"webEngine.results":                  "Results is how many hits this engine contributed, before the merge\ndeduplicated them against the others.",
			"webResult.content":                  "Content is the ENGINE's snippet — the few lines shown under the title, not\nthe page's text. Read the page itself with POST /v1/crawl.",
			"webResult.engine":                   "Engine names the backend that found this hit, so one engine's view of a\nquery can be told from another's.",
			"webResult.title":                    "Title is the page's title.",
			"webResult.url":                      "URL is the page's address, as the engine reported it.",
			"webSearchQuery.language":            "Language narrows the engines to a locale, BCP-47-ish (\"en\", \"ja\", \"de\").\nEmpty means no narrowing.",
			"webSearchQuery.q":                   "Q is the query. Required — an empty one is refused rather than answered\nwith the whole web.",
			"webSearchResults.engines":           "Engines is one entry per engine asked, in the order they were asked. It is\nADDITIVE to the SearXNG contract, which the LibreChat client ignores as an\nunknown field exactly as it ignores `engine` on a result.",
			"webSearchResults.number_of_results": "NumberOfResults is len(results) — what this answer carries, never an\nestimate of what the web holds.",
			"webSearchResults.query":             "Query is the query that ran, echoed back.",
			"webSearchResults.results":           "Results are the merged hits, deduplicated by normalised URL and capped at\n30. Always an array and never null: no hits is an ANSWER, not a fault.",
		},
	})
}
