// Code generated by zipdoc; DO NOT EDIT.

package audit

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /v1/admin/audit", zip.Doc{
		Description: "Reads cloud's tamper-evident audit trail, newest first, with the chain's live\nintegrity attached so a listing can be badged as verified.\n\nWhen cloud has no local store configured it falls back to forwarding IAM's own\nget-records trail verbatim — a DIFFERENT trail, federated so the endpoint never\nregresses to an empty list. Those rows carry no integrity of ours, so the field is\nnull there.",
		Fields: map[string]string{
			"Integrity.brokenAt":   "BrokenAt is the seq of the FIRST record that failed verification, or -1 when\nOK. Reason describes the break (recomputed-hash mismatch, prev-hash\ndiscontinuity, or a seq gap).",
			"Integrity.count":      "Count is the number of records walked.",
			"Integrity.headHash":   "HeadHash is the hash of the last record (or the genesis anchor for an empty\nchain). Pin this externally over time to detect tail-truncation.",
			"Integrity.ok":         "OK is true iff every record's stored hash equals the recomputed hash AND the\nchain links are continuous (each PrevHash == the prior record's Hash, seqs\ngapless from 0).",
			"RecordsIn.action":     "Action restricts it to one action name, e.g. \"admin.waitlist.grant\".",
			"RecordsIn.org":        "Org restricts the trail to one tenant.",
			"RecordsIn.p":          "Page is the 1-based page number, driving the offset.",
			"RecordsIn.pageSize":   "PageSize is rows per page, default 100.",
			"RecordsIn.resource":   "Resource restricts it to one resource kind, e.g. \"credit-grant\".",
			"RecordsIn.resourceId": "ResourceID restricts it to one resource instance.",
			"RecordsIn.result":     "Result restricts it to \"success\" or \"error\".",
			"RecordsIn.since":      "Since is the inclusive lower time bound, RFC3339. An unparseable value is\nignored rather than refused — one malformed filter must not hide the trail.",
			"RecordsIn.sub":        "Sub restricts it to one actor (the validated subject that made the request).",
			"RecordsIn.until":      "Until is the upper time bound, RFC3339, with the same tolerance.",
		},
		Example:  json.RawMessage(`{"org":"acme","action":"admin.waitlist.grant","since":"2026-07-01T00:00:00Z","pageSize":"50"}`),
		Response: json.RawMessage(`{"status":"ok","msg":"","data":[{"seq":41,"ts":"2026-07-26T18:00:00Z","org":"acme","sub":"z@hanzo.ai","action":"admin.waitlist.grant","resource":"waitlist","result":"success"}],"total":1,"integrity":{"ok":true,"count":42,"headHash":"9f2c","brokenAt":-1}}`),
	})
	zip.Describe("GET /v1/admin/audit/verify", zip.Doc{
		Description: "Walks the WHOLE hash chain and reports whether it is intact: how many records\nwere checked, the head hash to pin externally against tail-truncation, and — when the\nchain is broken — the seq of the first bad record and why.\n\nbrokenAt is -1 exactly when ok is true. An unconfigured store is an honest failure\nhere rather than a fabricated pass.",
		Fields: map[string]string{
			"Integrity.brokenAt": "BrokenAt is the seq of the FIRST record that failed verification, or -1 when\nOK. Reason describes the break (recomputed-hash mismatch, prev-hash\ndiscontinuity, or a seq gap).",
			"Integrity.count":    "Count is the number of records walked.",
			"Integrity.headHash": "HeadHash is the hash of the last record (or the genesis anchor for an empty\nchain). Pin this externally over time to detect tail-truncation.",
			"Integrity.ok":       "OK is true iff every record's stored hash equals the recomputed hash AND the\nchain links are continuous (each PrevHash == the prior record's Hash, seqs\ngapless from 0).",
		},
		Response: json.RawMessage(`{"status":"ok","msg":"","data":{"ok":true,"count":42,"headHash":"9f2c","brokenAt":-1}}`),
	})
}
