// Code generated by zipdoc; DO NOT EDIT.

package help

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /v1/help/articles", zip.Doc{
		Description: "listArticles returns the help center's published, public articles without bodies. The\ntenant is fixed at mount and the published/public filter is server-set, so a caller\ncan widen neither.",
		Fields: map[string]string{
			"ArticleCard.category":  "Category is the knowledge-base section the article sits in.",
			"ArticleCard.excerpt":   "Excerpt is the short summary shown in a list.",
			"ArticleCard.slug":      "Slug is the article's URL slug.",
			"ArticleCard.title":     "Title is the article headline.",
			"ArticleCard.updatedAt": "UpdatedAt is the last edit, as a unix timestamp in seconds.",
			"ArticleList.data":      "Data is the published, public articles, newest content first as the store returns them.",
			"ArticleQuery.category": "Category narrows the list to one knowledge-base section, by category name.",
			"ArticleQuery.limit":    "Limit caps the articles returned; 0 means 50 and nothing above 200 is honoured.",
		},
		Example:  json.RawMessage(`{"category":"billing","limit":20}`),
		Response: json.RawMessage(`{"data":[{"slug":"reset-my-password","title":"Reset my password","category":"accounts","excerpt":"Use the reset link on the sign-in page.","updatedAt":1780000000}]}`),
	})
	zip.Describe("GET /v1/help/articles/:slug", zip.Doc{
		Description: "getArticle returns one published, public article by slug. The article's document name\nIS its slug, and a missing, Draft, or internal (non-public) article is 404 —\nfail-closed, no existence oracle beyond \"published + public\".",
		Fields: map[string]string{
			"Article.body":      "Body is the rendered article text.",
			"Article.category":  "Category is the knowledge-base section the article sits in.",
			"Article.excerpt":   "Excerpt is the short summary shown in a list.",
			"Article.slug":      "Slug is the article's URL slug.",
			"Article.title":     "Title is the article headline.",
			"Article.updatedAt": "UpdatedAt is the last edit, as a unix timestamp in seconds.",
			"ArticleRef.slug":   "Slug is the article's URL slug, which is also its document name.",
		},
		Example:  json.RawMessage(`{"slug":"reset-my-password"}`),
		Response: json.RawMessage(`{"slug":"reset-my-password","title":"Reset my password","category":"accounts","excerpt":"Use the reset link on the sign-in page.","body":"<p>Open the sign-in page…</p>","updatedAt":1780000000}`),
	})
	zip.Describe("GET /v1/help/categories", zip.Doc{
		Description: "listCategories returns the knowledge-base sections that front a public article. Only\nsections carrying at least one Published + public article are listed, so an internal\n(agent-only) category name or description never leaks; an org with no public articles\nhas no sections (empty, not an error).",
		Fields: map[string]string{
			"CategoryCard.description": "Description is the section blurb.",
			"CategoryCard.name":        "Name is the section's name, which is also its document name.",
			"CategoryList.data":        "Data is the sections that front at least one published, public article.",
		},
		Response: json.RawMessage(`{"data":[{"name":"accounts","description":"Signing in and account settings."}]}`),
	})
	zip.Describe("POST /v1/help/tickets", zip.Doc{
		Description: "fileTicket opens a support ticket from an anonymous customer submission. The ticket is\ncreated status Open, source portal, with the customer's message on the description,\nand that message is then recorded as the opening conversation entry — the description\ncarries it regardless, so failing to write the entry loses nothing.",
		Fields: map[string]string{
			"TicketIntake.description": "Description is the customer's message. Clipped to 16 KiB.",
			"TicketIntake.email":       "Email is the customer's address, and the party the ticket is filed against. Required.",
			"TicketIntake.priority":    "Priority is one of low, medium, high or urgent; anything else means medium.",
			"TicketIntake.subject":     "Subject is the one-line summary. Required; clipped to 300 characters.",
			"TicketReceipt.status":     "Status is the ticket's lifecycle state, always Open on intake.",
			"TicketReceipt.ticket":     "Ticket is the opaque customer-facing reference; the internal ticket number is not disclosed.",
		},
		Example:  json.RawMessage(`{"subject":"Cannot sign in","description":"The reset link 404s.","email":"sam@example.com","priority":"high"}`),
		Response: json.RawMessage(`{"ticket":"tkt_4c1e9b7a2d6f0538e4a7c9b1","status":"Open"}`),
	})
}
