// Code generated by zipdoc; DO NOT EDIT.

package deploy

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /v1/deploy/applications", zip.Doc{
		Description: "applications lists the caller's applications, projected from the operator App CRs.\nA SuperAdmin sees the whole fleet; a validated org member sees only its own\norg's apps. Nothing is read from a stored argocd Application — every item is\nsynthesized from the App CR that actually runs.",
		Fields: map[string]string{
			"argoDestination.name": "ArgoCD allows a destination by cluster name; omitted for the in-cluster projection.",
		},
	})
	zip.Describe("GET /v1/deploy/applications/:name", zip.Doc{
		Description: "application returns one projected application, with its reconciled resources.\nA name another org owns is reported as not found, never as forbidden, so the\ndetail route leaks no cross-tenant existence oracle.",
		Fields: map[string]string{
			"appRef.name":          "Name is the application name from the path; a DNS-1123 label.",
			"argoDestination.name": "ArgoCD allows a destination by cluster name; omitted for the in-cluster projection.",
		},
		Example: json.RawMessage(`{"name":"cloud"}`),
	})
	zip.Describe("GET /v1/deploy/applications/:name/resource-tree", zip.Doc{
		Description: "resourceTree returns one application's live resource tree, node by node.\nThe tree is built from what the cluster actually runs; a name another org owns\nis reported as not found.",
		Fields: map[string]string{
			"appRef.name": "Name is the application name from the path; a DNS-1123 label.",
		},
		Example: json.RawMessage(`{"name":"cloud"}`),
	})
	zip.Describe("GET /v1/deploy/applications/:name/revisions/:revision/metadata", zip.Doc{
		Description: "revisionMetadata describes one revision of an application as far as the CR knows.\n\nThe App CR is IMAGE-based: the deploy is pinned to an image tag, not a git commit, and\nthe projection's git source (git.hanzo.ai/hanzoai/universe) is the display-only manifest\nrepo, NOT the app's own source — so there is no in-process commit to resolve a revision\nauthor/date/message from (clients/git exposes CloneURL + VerifyRef only, neither of which\nyields commit metadata for an arbitrary revision). Rather than 404 (the toast) or\nfabricate a git author, this returns an HONEST minimal RevisionMetadata: message = the\nrevision (HEAD resolves to the CR's declared image tag), date = when the app was declared\n(the CR creation time), author = \"\" (none). Real git enrichment is a follow-on gated on\nthe CR carrying a real git source + a clients/git CommitMetadata export.",
		Fields: map[string]string{
			"revisionRef.name":     "Name is the application name from the path; a DNS-1123 label.",
			"revisionRef.revision": "Revision is the revision from the path; \"\" or \"HEAD\" resolves to the CR's tag.",
		},
		Example: json.RawMessage(`{"name":"cloud","revision":"HEAD"}`),
	})
	zip.Describe("GET /v1/deploy/applications/:name/syncwindows", zip.Doc{
		Description: "syncWindows reports whether one application may be synced right now.\nThis plane declares no blackout windows, so the answer is always yes — but the\napp must exist AND belong to the caller, or the read is a 404.",
		Fields: map[string]string{
			"appRef.name": "Name is the application name from the path; a DNS-1123 label.",
		},
		Example: json.RawMessage(`{"name":"cloud"}`),
	})
	zip.Describe("GET /v1/deploy/clusters", zip.Doc{
		Description: "clusters lists the destination clusters the caller's applications reconcile into.\nThe in-cluster destination is always present, only the caller's own apps are\ncounted (a SuperAdmin counts the fleet), and no cluster credential can leak —\nthe projected cluster carries no config field at all.",
	})
	zip.Describe("GET /v1/deploy/gitops", zip.Doc{
		Description: "gitops reports the CD plane's own state: its git source, the commit it last\napplied, and its deploy history. Fleet infrastructure with no tenant dimension,\nso it is SuperAdmin-only. A cluster with no Hanzo CD installed answers\ninstalled=false with the reason, never an error.",
		Fields: map[string]string{
			"GitOpsApp.health":   "Healthy|Degraded|Progressing|…",
			"GitOpsApp.revision": "the commit last applied",
			"GitOpsApp.sync":     "Synced|OutOfSync|Unknown",
		},
	})
	zip.Describe("GET /v1/deploy/projects", zip.Doc{
		Description: "projects lists the caller's IAM projects, reflected read-only as AppProjects.\nIAM is the one source of truth for the (org, name) Project resource: a normal\norg sees only its own organization's projects, a SuperAdmin every org's, and\n\"default\" always resolves. When the embedded IAM store is unreachable a\nSuperAdmin still sees real argoproj.io/v1alpha1 AppProject CRs if that CRD is\nserved, else one permissive project per distinct App-CR project name.",
		Fields: map[string]string{
			"argoDestination.name": "ArgoCD allows a destination by cluster name; omitted for the in-cluster projection.",
		},
	})
	zip.Describe("GET /v1/deploy/session/userinfo", zip.Doc{
		Description: "userInfo reports whether this browser is signed in, and where to sign in if not.\nIt is the ONE route here that answers an anonymous caller, because a 403 to\nthat question is unanswerable for an XHR client. The predicate is the same\nSuperAdmin fact every other route gates on, so a validated-but-not-SuperAdmin\ncaller is reported as not logged in — the truth as this console defines it.",
		Fields: map[string]string{
			"userInfoView.groups":    "Groups is the signed-in operator's group list, always empty here; absent\nfor an anonymous caller.",
			"userInfoView.iss":       "Iss is the issuer the SPA checks before offering an SSO redirect; absent\nfor an anonymous caller.",
			"userInfoView.loggedIn":  "LoggedIn reports whether the caller may use this console at all.",
			"userInfoView.loginUrl":  "LoginURL is where an anonymous caller signs in; absent once signed in.",
			"userInfoView.logoutUrl": "LogoutURL is where the signed-in operator signs out; absent when anonymous.",
			"userInfoView.username":  "Username is the signed-in operator; absent for an anonymous caller.",
		},
		Response: json.RawMessage(`{"loggedIn":true,"username":"z","iss":"argocd","groups":[],"logoutUrl":"/v1/deploy/logout"}`),
	})
	zip.Describe("GET /v1/deploy/settings", zip.Doc{
		Description: "settings returns the fixed bootstrap configuration the dashboard SPA reads first.\nNothing here is per-request or per-tenant: this plane runs no OIDC/Dex of its\nown (IAM gates identity at the edge) and offers no exec, plugins or badges.",
		Fields: map[string]string{
			"authSettings.appsInAnyNamespaceEnabled": "AppsInAnyNamespaceEnabled is always false.",
			"authSettings.dexConfig":                 "DexConfig carries an empty connector list, for the same reason.",
			"authSettings.execEnabled":               "ExecEnabled is always false: no pod exec from this console.",
			"authSettings.googleAnalytics":           "GoogleAnalytics is off, with user anonymization on.",
			"authSettings.help":                      "Help carries no chat or binary download links.",
			"authSettings.hydratorEnabled":           "HydratorEnabled is always false.",
			"authSettings.kustomizeVersions":         "KustomizeVersions is always empty.",
			"authSettings.oidcConfig":                "OIDCConfig is always null: IAM gates identity at the edge, not here.",
			"authSettings.plugins":                   "Plugins is always empty: no plugin runs on this plane.",
			"authSettings.statusBadgeEnabled":        "StatusBadgeEnabled is always false: this plane serves no badges.",
			"authSettings.statusBadgeRootUrl":        "StatusBadgeRootURL is always empty, for the same reason.",
			"authSettings.syncWithReplaceAllowed":    "SyncWithReplaceAllowed is always false: replace-on-sync is never offered.",
			"authSettings.uiBannerContent":           "UIBannerContent is always empty (no banner).",
			"authSettings.uiCssURL":                  "UICSSURL is always empty (no injected stylesheet).",
			"authSettings.url":                       "URL is the console's own base URL.",
			"authSettings.userLoginsDisabled":        "UserLoginsDisabled is always true: the SPA never renders its own login form.",
			"settingsAnalytics.anonymizeUsers":       "AnonymizeUsers is always true.",
			"settingsAnalytics.trackingID":           "TrackingID is always empty: no analytics is wired.",
			"settingsDex.connectors":                 "Connectors is always empty.",
			"settingsHelp.binaryUrls":                "BinaryURLs is always empty.",
			"settingsHelp.chatText":                  "ChatText is always empty.",
			"settingsHelp.chatUrl":                   "ChatURL is always empty.",
		},
	})
	zip.Describe("GET /v1/deploy/version", zip.Doc{
		Description: "version identifies this plane to the dashboard SPA as a projection.\nIt is not a real argocd server and says so; the toolchain is never disclosed.",
		Fields: map[string]string{
			"versionMessage.BuildDate": "BuildDate is the moment this answer was produced, RFC3339 UTC.",
			"versionMessage.Compiler":  "Compiler is always \"gc\".",
			"versionMessage.GoVersion": "GoVersion is always empty: this plane discloses no toolchain.",
			"versionMessage.Platform":  "Platform is always \"linux/amd64\".",
			"versionMessage.Version":   "Version names this plane as a projection, not a real argocd server.",
		},
	})
	zip.Describe("POST /v1/deploy/applications/:name/rollback", zip.Doc{
		Description: "rollback requests the same operator reconcile sync does, for the UI's Rollback action.\nRollback-by-revision is the image-pin follow-on; today both actions mean\n\"reconcile this App now\". SuperAdmin only.",
		Fields: map[string]string{
			"appRef.name":          "Name is the application name from the path; a DNS-1123 label.",
			"argoDestination.name": "ArgoCD allows a destination by cluster name; omitted for the in-cluster projection.",
		},
		Example: json.RawMessage(`{"name":"cloud"}`),
	})
	zip.Describe("POST /v1/deploy/applications/:name/sync", zip.Doc{
		Description: "sync requests an operator reconcile of one application, and returns it projected.\nThe App CR is the source of truth, so a sync is an annotation bump the operator\nacts on — nothing is applied from this plane. SuperAdmin only.",
		Fields: map[string]string{
			"appRef.name":          "Name is the application name from the path; a DNS-1123 label.",
			"argoDestination.name": "ArgoCD allows a destination by cluster name; omitted for the in-cluster projection.",
		},
		Example: json.RawMessage(`{"name":"cloud"}`),
	})
	zip.Describe("POST /v1/deploy/logout", zip.Doc{
		Description: "logout clears the session cookie for this host. IAM's own session is untouched —\nthis ends the console session only.\n\nIt is a POST because it CHANGES STATE. As a GET it was reachable by a cross-site\ntop-level navigation (an <img> or a link on any page), which a SameSite=Lax cookie\nstill rides, so any site could sign a SuperAdmin out at will. A nuisance rather\nthan a compromise, but a state-changing GET is a bug regardless; POST is not\ncarried cross-site by a Lax cookie, so the class is closed.\nlogout clears the console session cookie and reports the caller signed out.\nPOST, not GET: signing out changes state, and a state-changing GET is reachable\nby a cross-site top-level navigation a SameSite=Lax cookie still rides.",
		Fields: map[string]string{
			"userInfoView.groups":    "Groups is the signed-in operator's group list, always empty here; absent\nfor an anonymous caller.",
			"userInfoView.iss":       "Iss is the issuer the SPA checks before offering an SSO redirect; absent\nfor an anonymous caller.",
			"userInfoView.loggedIn":  "LoggedIn reports whether the caller may use this console at all.",
			"userInfoView.loginUrl":  "LoginURL is where an anonymous caller signs in; absent once signed in.",
			"userInfoView.logoutUrl": "LogoutURL is where the signed-in operator signs out; absent when anonymous.",
			"userInfoView.username":  "Username is the signed-in operator; absent for an anonymous caller.",
		},
		Response: json.RawMessage(`{"loggedIn":false,"loginUrl":"/v1/deploy/login"}`),
	})
	zip.Describe("POST /v1/deploy/reconcile", zip.Doc{
		Description: "reconcile renders the configured git source and applies it to the cluster once.\nIt is the SuperAdmin-gated write half that replaces universe-crs: a three-way\nserver-side apply through the embedded gitops-engine, with a scoped prune and\nper-resource health. Disabled unless DEPLOY_ENGINE_ENABLED is set.",
		Fields: map[string]string{
			"reconcileResult.message":  "Message is the engine's detail for that outcome; empty when it succeeded cleanly.",
			"reconcileResult.resource": "Resource is the object key (group/kind/namespace/name) that was applied.",
			"reconcileResult.status":   "Status is the engine's outcome: Synced, Pruned, SyncFailed or Unknown.",
			"reconcileSource.path":     "Path is the directory within the repo that was rendered.",
			"reconcileSource.ref":      "Ref is the branch or tag that was rendered.",
			"reconcileSource.repo":     "Repo is the git repository the manifests were rendered from.",
			"reconcileView.declared":   "Declared is how many objects the source rendered.",
			"reconcileView.failed":     "Failed is how many objects the apply rejected.",
			"reconcileView.instance":   "Instance is the tracking instance the applied objects are labelled with.",
			"reconcileView.prune":      "Prune reports whether objects absent from the source were deleted.",
			"reconcileView.pruned":     "Pruned is how many objects were deleted.",
			"reconcileView.results":    "Results is the per-resource outcome.",
			"reconcileView.revision":   "Revision is the commit that was rendered and applied.",
			"reconcileView.source":     "Source is the git source the revision came from.",
			"reconcileView.synced":     "Synced is how many objects were applied.",
		},
	})
}
