// Code generated by zipdoc; DO NOT EDIT.

package storage

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("DELETE /v1/s3/buckets/:bucket", zip.Doc{
		Description: "deleteBucket removes an EMPTY bucket of the caller's org and answers 204. A\nbucket that still holds objects is refused rather than cascaded.",
		Fields: map[string]string{
			"bucketRef.bucket": "Bucket is the friendly bucket name from the path, as listBuckets returns it.",
		},
		Example: json.RawMessage(`{"bucket":"photos"}`),
	})
	zip.Describe("GET /v1/s3/buckets", zip.Doc{
		Description: "listBuckets returns the caller org's buckets by their friendly names.",
		Fields: map[string]string{
			"bucketItem.createdAt": "CreatedAt is when the bucket was made, unix seconds.",
			"bucketItem.name":      "Name is the bucket's FRIENDLY name — what the tenant created it as, with the\nserver-side org prefix stripped.",
			"bucketList.buckets":   "Buckets is every bucket in the caller's org namespace; another tenant's\nbuckets are invisible rather than forbidden.",
			"bucketList.total":     "Total is how many buckets came back — the listing is not paginated.",
		},
		Response: json.RawMessage(`{"buckets":[{"name":"photos","createdAt":1780000000}],"total":1}`),
	})
	zip.Describe("GET /v1/s3/buckets/:bucket/objects", zip.Doc{
		Description: "listObjects lists one folder level of a bucket, keys relative to the prefix.\nThe page is capped at 1000 entries, so a huge bucket cannot exhaust memory.",
		Fields: map[string]string{
			"listObjectsRequest.bucket":    "Bucket is the friendly bucket name from the path.",
			"listObjectsRequest.prefix":    "Prefix scopes the listing to a sub-folder; empty lists the bucket root. An\nabsolute or traversing prefix is coerced to the root rather than refused.",
			"listObjectsRequest.recursive": "Recursive lists every key flat under prefix instead of one folder level.",
			"objectItem.etag":              "ETag is the store's entity tag, quotes stripped; absent for a folder.",
			"objectItem.isDir":             "IsDir is true for a folder (an S3 common prefix), false for a real object.",
			"objectItem.key":               "Key is the object key RELATIVE to the requested prefix, so a UI can render a\nbreadcrumb without re-splitting the full key.",
			"objectItem.lastModified":      "LastModified is unix seconds; 0 for a folder.",
			"objectItem.size":              "Size is the object's bytes; 0 for a folder.",
			"objectList.bucket":            "Bucket is the friendly bucket name that was listed.",
			"objectList.objects":           "Objects is the folder's entries, at most 1000 per call.",
			"objectList.prefix":            "Prefix is the folder that was listed, after normalization.",
			"objectList.total":             "Total is how many entries came back.",
		},
		Example:  json.RawMessage(`{"bucket":"photos","prefix":"2026/","recursive":false}`),
		Response: json.RawMessage(`{"bucket":"photos","prefix":"2026/","objects":[{"key":"may/","isDir":true,"size":0,"lastModified":0}],"total":1}`),
	})
	zip.Describe("POST /v1/s3/buckets", zip.Doc{
		Description: "createBucket makes a new bucket in the caller org's namespace and answers 201.",
		Fields: map[string]string{
			"bucketItem.createdAt":     "CreatedAt is when the bucket was made, unix seconds.",
			"bucketItem.name":          "Name is the bucket's FRIENDLY name — what the tenant created it as, with the\nserver-side org prefix stripped.",
			"createBucketRequest.name": "Name is the friendly bucket name, lowercase DNS-style\n(^[a-z0-9]([a-z0-9-]{0,38}[a-z0-9])?$). The physical name is derived from the\ncaller's org server-side.",
		},
		Example:  json.RawMessage(`{"name":"photos"}`),
		Response: json.RawMessage(`{"name":"photos","createdAt":1780000000}`),
	})
	zip.Describe("POST /v1/s3/buckets/:bucket/objects", zip.Doc{
		Description: "presignUpload mints a short-lived presigned PUT URL so the browser uploads\nstraight to the object store — no body through this binary, and the admin\ncredential never leaves the server.",
		Fields: map[string]string{
			"presignResponse.expiresIn":   "Expiry is how many seconds the URL stays valid.",
			"presignResponse.key":         "Key is the object key the URL addresses, after cleaning.",
			"presignResponse.method":      "Method is the verb the URL is signed for: PUT to upload, GET to download.",
			"presignResponse.url":         "URL is the presigned URL the browser follows directly, signed against the\nPUBLIC endpoint and scoped to this exact bucket and key.",
			"presignUploadRequest.bucket": "Bucket is the friendly bucket name from the path.",
			"presignUploadRequest.key":    "Key is the object key to upload, relative to the bucket root. It may contain\n\"/\" but must not be absolute, empty, a folder marker or traverse with \"..\".",
		},
		Example:  json.RawMessage(`{"bucket":"photos","key":"2026/may/cover.jpg"}`),
		Response: json.RawMessage(`{"url":"https://s3.hanzo.ai/o1234-photos/2026/may/cover.jpg?X-Amz-Signature=...","method":"PUT","key":"2026/may/cover.jpg","expiresIn":300}`),
	})
}
