// Code generated by zipdoc; DO NOT EDIT.

package sbom

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /v1/sbom/*", zip.Doc{
		Description: "Binds a Service-scoped handler to a route: it adapts a\n`func(*Service[S], *zip.Ctx) error` to the plain `func(*zip.Ctx) error` the\nrouter takes, capturing s. One adapter, so packages write free-function\nhandlers and register them with `app.Get(\"/path\", cloud.Handle(s, myHandler))`.",
	})
	zip.Describe("GET /v1/sbom/health", zip.Doc{
		Description: "Health is a pure liveness probe: the service is up; datastore reflects whether\nthe datastore store is connected. Not JWT-gated, always 200 (a disconnected\ndatastore is degraded-but-alive; the data endpoints report that as 503).",
		Fields: map[string]string{
			"SbomHealth.datastore": "Datastore reports whether the shared datastore connection this subsystem reads\nand writes through is established. False means the data endpoints answer 503.",
			"SbomHealth.service":   "Service names the subsystem answering: always \"sbom\".",
			"SbomHealth.status":    "Status is the liveness verdict: always \"ok\" here, because the process answering\nat all IS the liveness fact.",
			"SbomHealth.table":     "Table is the fully-qualified datastore table the components live in.",
		},
	})
	zip.Describe("POST /v1/sbom", zip.Doc{
		Description: "Ingest persists a CycloneDX SBOM's components keyed by image digest. Gated to a\nvalidated SuperAdmin (owner == AdminOrg) — the canonical cloud super-admin\ncheck, which the build fleet / CI carries. Re-ingest is idempotent: rows share\nthe (digest, name, version, purl) ORDER BY, so ReplacingMergeTree keeps the\nlatest by ingested_at (and resolve reads FINAL).",
		Fields: map[string]string{
			"SbomIngest.document":         "Document is the raw CycloneDX bill of materials, any JSON. Its components[]\nare flattened and persisted; nothing else is read or stored.",
			"SbomIngest.format":           "Format names the document format; \"cyclonedx\" is the only one parsed.",
			"SbomIngest.gitSha":           "GitSha is the commit the image was built from.",
			"SbomIngest.imageDigest":      "ImageDigest is the content-addressed digest (sha256:…) the components are\nkeyed under. Required — it, not a tenant, is what an SBOM belongs to.",
			"SbomIngest.imageRef":         "ImageRef is the human-readable image reference the digest was published as.\nA resolve matches on either this or the digest.",
			"SbomIngest.sourceRepo":       "SourceRepo is the repository the image was built from.",
			"SbomIngested.componentCount": "ComponentCount is how many components the CycloneDX document yielded and this\ncall persisted.",
			"SbomIngested.imageDigest":    "ImageDigest is the content-addressed digest the components were keyed under.",
		},
		Example: json.RawMessage(`{"imageDigest":"sha256:abc","imageRef":"registry.hanzo.ai/hanzo/cloud:v1","format":"cyclonedx","document":{"components":[]}}`),
	})
}
