package openapi_test

// The composition proof — and, now that the monolith is gone, the ONLY producer
// of the published spec.
//
// TestFleetIsTheWeaveOfItsApps weaves every app's own subset — each generated by
// that app's own binary from that app's own router (`<app> openapi`) — into the
// fleet document, and requires it to equal openapi.yaml byte for byte. There is
// no fully-mounted binary left to read: "compose the apps" and "the spec" are one
// statement. `make describe` writes the golden through this same weave (-weave);
// with no flag the same weave is the check.
//
// What it proves is COMPOSITION and only composition: that the subsets compose
// without two apps claiming one address or one schema name, and that the golden
// is what they compose to. Both sides are derived, so it cannot prove either is
// still the routes — `make -f mk/fleet.mk check` regenerates them from
// source for that, and manifest/router_test.go asks the router whether the fleet
// delivers what they describe. Three questions, three gates, each answered where
// its answer lives.
//
// It links no subsystem and mounts nothing but the openapi endpoint itself, so
// it costs a second and runs on every push.

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"os"
	"path/filepath"
	"testing"

	"github.com/hanzoai/cloud/manifest"
	"github.com/hanzoai/cloud/openapi"
	"sigs.k8s.io/yaml"
)

// weaveOut writes the woven document — the fleet spec the SDK repos pull. It is
// the SOLE writer of openapi.yaml now that the monolith is gone: `make describe`
// regenerates each app's subset and then runs this with -weave to compose them
// into the golden. Without the flag the same weave is the drift gate.
var weaveOut = flag.String("weave", "", "write the woven document to this path (regenerate the golden)")

// goldenPath, floorPath and specDir are relative to this package's directory.
const (
	goldenPath = "../openapi.yaml"
	floorPath  = "floor.json"
	specDir    = "../plugin"
)

// fromTree is the WORKING TREE's copy of one app's subset — the files
// check has just regenerated from source and is about to compare against.
// The host reads the same files through plugin.Spec, embedded at build time;
// openapi.Subsets decodes either, so there is one decoder and one weave whichever
// end you enter from.
//
// It reads them and nothing else. WHERE a path is routed is not a question a
// document can answer, and the version of this function that tried is why the
// fleet published 58 unreachable paths: it skipped any path already present in
// openapi.yaml — the artifact this test protects — so the golden exempted every
// defect it already contained, and what survived that was reported with t.Logf.
// A gate that reads its own output cannot fail. The question moved to the only
// thing that can answer it, the router: manifest/router_test.go.
func fromTree(app string) []byte {
	raw, err := os.ReadFile(filepath.Join(specDir, app, "openapi.json"))
	if err != nil {
		return nil // openapi.Subsets refuses it by name
	}
	return raw
}

func TestFleetIsTheWeaveOfItsApps(t *testing.T) {
	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read %s: %v — run `make describe`", goldenPath, err)
	}
	subsets, err := openapi.Subsets(manifest.Names(), fromTree)
	if err != nil {
		t.Fatal(err)
	}
	// The SAME composition the host serves (cmd/cloud spec → openapi.MountFleet),
	// which is what makes the served document and this golden one document rather
	// than two that agree today.
	woven, err := openapi.Fleet(subsets)
	if err != nil {
		t.Fatalf("weave: %v", err)
	}

	// THE RATCHET, before anything is written: a regeneration that publishes less
	// than the committed floor is refused in BOTH modes, so `make describe` cannot
	// be the thing that lands a shrunken document. See openapi/floor.go.
	was, err := openapi.ReadFloor(floorPath)
	if err != nil {
		t.Fatal(err)
	}
	raised, err := was.Raise(openapi.Measure(woven))
	if err != nil {
		t.Fatal(err)
	}

	j, err := json.Marshal(woven)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	got, err := yaml.JSONToYAML(j)
	if err != nil {
		t.Fatalf("yaml: %v", err)
	}

	// -weave is the REGENERATE mode (write the golden and stop); no flag is the
	// GATE mode (verify below). Falling through would compare the just-written
	// document against the golden we read BEFORE writing it, and fail every real
	// regeneration for having done its job.
	if *weaveOut != "" {
		if err := os.WriteFile(*weaveOut, got, 0o644); err != nil {
			t.Fatalf("write %s: %v", *weaveOut, err)
		}
		if err := raised.Write(floorPath); err != nil {
			t.Fatalf("write %s: %v", floorPath, err)
		}
		t.Logf("wrote %s (%d paths) and %s (%d products)", *weaveOut, len(woven.Paths), floorPath, len(raised.Products))
		return
	}

	// The monolith is gone: the woven document IS the published spec, so this is a
	// plain golden check. A byte for byte match is the whole guarantee — any
	// difference means a route moved (an app subset regenerated) without the
	// golden being regenerated too, or the reverse.
	if !bytes.Equal(got, want) {
		t.Fatalf("openapi.yaml is not the weave of its apps' subsets (%d paths woven now). A route was added, "+
			"removed or renamed and either an app subset or the golden was not regenerated — the SDK repos pull "+
			"this file. Run `make describe` and commit the result.", len(woven.Paths))
	}
	t.Logf("woven %d paths / %d schemas / %d tags from %d apps — byte-identical to %s",
		len(woven.Paths), schemaCount(woven), len(woven.Tags), len(manifest.Apps), goldenPath)
}

// Two apps may not claim one address. This is the check the manifest's
// call-graph walk found the need for: clients/git's /:org/:repo catch-all was
// swallowing other apps' routes, and a merge that picked a winner would have
// published a document describing a fleet nobody deploys.
func TestWeaveRefusesTwoAppsAtOneAddress(t *testing.T) {
	dup := func(app, path string) openapi.Part {
		return openapi.Part{App: app, Doc: &openapi.Document{
			Paths: map[string]openapi.PathItem{path: {"get": {OperationID: "get_" + app}}},
		}}
	}
	_, err := openapi.Weave([]openapi.Part{dup("git", "/v1/x"), dup("code", "/v1/x")})
	var c *openapi.Conflict
	if !errors.As(err, &c) {
		t.Fatalf("Weave = %v, want a *Conflict — a silent last-write-wins is the bug this exists to refuse", err)
	}
	if c.Kind != "operation" || c.A != "git" || c.B != "code" {
		t.Errorf("Conflict = %+v, want operation GET /v1/x between git and code", c)
	}
	// The same address in ONE app is not a conflict — an app's own document
	// already had to be injective to be generated at all.
	if _, err := openapi.Weave([]openapi.Part{dup("git", "/v1/x"), dup("code", "/v1/y")}); err != nil {
		t.Errorf("two apps at two addresses: %v", err)
	}
}

// One schema name, two shapes. Schemas are named after Go types (AccessOut,
// Campaign, None), so two apps CAN reach the same name honestly — and every
// generated SDK would bind whichever the merge read last.
func TestWeaveRefusesOneSchemaNameWithTwoShapes(t *testing.T) {
	part := func(app string, schema any) openapi.Part {
		return openapi.Part{App: app, Doc: &openapi.Document{
			Paths:      map[string]openapi.PathItem{"/v1/" + app: {"get": {OperationID: "get_" + app}}},
			Components: &openapi.Components{Schemas: map[string]any{"None": schema}},
		}}
	}
	_, err := openapi.Weave([]openapi.Part{
		part("ads", map[string]any{"type": "object"}),
		part("crm", map[string]any{"type": "string"}),
	})
	var c *openapi.Conflict
	if !errors.As(err, &c) {
		t.Fatalf("Weave = %v, want a *Conflict", err)
	}
	if c.Kind != "schema" || c.Name != "None" {
		t.Errorf("Conflict = %+v, want schema None", c)
	}

	// Identical shapes are ONE schema, not a conflict: two apps using the same
	// type is composition working, not colliding.
	same := map[string]any{"type": "object", "properties": map[string]any{"ok": map[string]any{"type": "boolean"}}}
	doc, err := openapi.Weave([]openapi.Part{part("ads", same), part("crm", same)})
	if err != nil {
		t.Fatalf("identical schemas: %v", err)
	}
	if n := schemaCount(doc); n != 1 {
		t.Errorf("schemas = %d, want 1 — an identical definition must merge, not duplicate", n)
	}
}

// The composed document owes the same invariant a generated one does. Two apps
// at two addresses whose ids collide is a defect composition can introduce even
// when neither app is at fault.
func TestWeaveRefusesCollidingOperationIDs(t *testing.T) {
	fixed := func(app, path string) openapi.Part {
		return openapi.Part{App: app, Doc: &openapi.Document{
			Paths: map[string]openapi.PathItem{path: {"get": {OperationID: "get_thing"}}},
		}}
	}
	if _, err := openapi.Weave([]openapi.Part{fixed("a", "/v1/a"), fixed("b", "/v1/b")}); err == nil {
		t.Fatal("Weave accepted a duplicate operationId — a generator would mis-consume the document")
	}
}

// PROVENANCE: every operation names the registry that registered it, so a
// misplaced one names a repo to file against instead of costing a bisect of 116
// subsets. Written where it is known and never overwritten — an operation that
// arrived through a door already knows better than the part it arrived in.
func TestWeaveNamesTheRegistryBehindEachOperation(t *testing.T) {
	doc, err := openapi.Weave([]openapi.Part{
		{App: "ai", Doc: &openapi.Document{Paths: map[string]openapi.PathItem{
			"/v1/ai/health":        {"get": {OperationID: "a"}},
			"/v1/chat/completions": {"post": {OperationID: "b", App: "github.com/hanzoai/ai"}},
		}}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if got := doc.Paths["/v1/ai/health"]["get"].App; got != "ai" {
		t.Errorf("x-app = %q, want the app that contributed the part", got)
	}
	if got := doc.Paths["/v1/chat/completions"]["post"].App; got != "github.com/hanzoai/ai" {
		t.Errorf("x-app = %q, want the module behind the door — the weave overwrote a registry that had already named itself", got)
	}
}

// A DOOR YIELDS TO A SPECIFIC ROUTE, because that is what the matcher does. This
// is the one overlap Weave resolves, and it resolves it by reading the router's
// rule off the data — a relayed operation names its own registry, a direct one
// does not — rather than by preferring an app.
func TestWeaveGivesTheSpecificRouteWhatTheMatcherGivesIt(t *testing.T) {
	specific := openapi.Part{App: "provisioning", Doc: &openapi.Document{Paths: map[string]openapi.PathItem{
		"/v1/search": {"post": {OperationID: "provisioningSearch"}},
	}}}
	relayed := openapi.Part{App: "ai", Doc: &openapi.Document{Paths: map[string]openapi.PathItem{
		"/v1/search": {"post": {OperationID: "aiSearch", App: "github.com/hanzoai/ai"}},
	}}}
	for _, order := range [][]openapi.Part{{specific, relayed}, {relayed, specific}} {
		doc, err := openapi.Weave(order)
		if err != nil {
			t.Fatalf("%s first: %v", order[0].App, err)
		}
		if got := doc.Paths["/v1/search"]["post"].OperationID; got != "provisioningSearch" {
			t.Errorf("%s first: operationId = %q, want the specific route — the relay's handler never runs at that address",
				order[0].App, got)
		}
	}

	// Two DOORS at one address is still a refusal: two wildcards overlapping is a
	// bug at the composition root and there is no rule that picks between them.
	both := func(app, src string) openapi.Part {
		return openapi.Part{App: app, Doc: &openapi.Document{Paths: map[string]openapi.PathItem{
			"/v1/x": {"get": {OperationID: "get_" + app, App: src}},
		}}}
	}
	_, err := openapi.Weave([]openapi.Part{both("ai", "github.com/hanzoai/ai"), both("iam", "github.com/hanzoai/iam")})
	var c *openapi.Conflict
	if !errors.As(err, &c) || c.Kind != "operation" {
		t.Fatalf("Weave = %v, want an operation Conflict between two doors", err)
	}
}

func schemaCount(d *openapi.Document) int {
	if d.Components == nil {
		return 0
	}
	return len(d.Components.Schemas)
}
