// Code generated by zipdoc; DO NOT EDIT.

package destinations

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("DELETE /v1/destinations/:platform", zip.Doc{
		Description: "disconnect forgets a destination for the caller's org: every credential held in\nKMS, then the stored config. Idempotent, and it requires org admin.",
		Fields: map[string]string{
			"destinationDisconnected.disconnected": "Disconnected is true when the credentials and the row are gone.",
			"destinationRef.platform":              "Platform is the destination to act on, from the path: ga4 | meta | tiktok |\nlinkedin | x | reddit | posthog | umami.",
		},
		Example: json.RawMessage(`{"platform":"ga4"}`),
	})
	zip.Describe("GET /v1/destinations", zip.Doc{
		Description: "list reports every destination this deployment can forward to, each with the\ncaller org's connection state: whether it is connected, whether it is enabled,\nwhether a credential resolves right now, and the config fields the console\nrenders for it.",
		Fields: map[string]string{
			"DestinationField.example":     "a sample value of the right shape (\"G-XXXXXXX\"), when one helps",
			"DestinationField.key":         "the camelCase key on both the connect body and the stored config",
			"DestinationField.label":       "human label for the console card's input",
			"DestinationField.required":    "when true, a connect that leaves it empty is refused 400",
			"DestinationStatus.account":    "Account is the operator's own label for the connected account, as supplied on\nconnect. Absent when unset.",
			"DestinationStatus.category":   "groups the card: Analytics | Advertising",
			"DestinationStatus.config":     "Config is the org's stored NON-SECRET configuration — the measurement/pixel\nids keyed by DestinationField.Key. A secret is never in here; secrets live in\nKMS and only their names are published, in Secrets.",
			"DestinationStatus.connected":  "Connected is true when this org has a stored row for the platform — it has\nbeen configured here at least once. It says nothing about whether a\ncredential still resolves; that is Live.",
			"DestinationStatus.enabled":    "Enabled is whether the fan-out forwards to this destination. False on a\ndestination that is connected but paused, and on one never connected.",
			"DestinationStatus.fields":     "Fields are the non-secret inputs this platform needs, which the console card\nrenders and the connect body fills.",
			"DestinationStatus.live":       "Live is whether a credential resolves RIGHT NOW: a KMS-sealed secret for this\norg, else the integrations connection named by the platform's Fallback, else\nno credential needed at all (a public-ingest sink like Umami). False on a\nconnected destination whose secret has gone missing — Connected && !Live is\nexactly the \"reconnect me\" state.",
			"DestinationStatus.name":       "the platform's display name (\"Google Analytics 4\")",
			"DestinationStatus.platform":   "the platform slug, and the path segment every route addresses it by",
			"DestinationStatus.secrets":    "Secrets are the KMS secret NAMES this platform custodies for the org — names\nonly, never values. The connect body accepts each under its camelCase form.",
			"destinationList.destinations": "Destinations is one card per registered platform, in slug order.",
		},
	})
	zip.Describe("GET /v1/destinations/:platform", zip.Doc{
		Description: "get reports one destination's card for the caller's org — its config fields,\nits connection state, and whether a credential resolves right now. A platform\nthis deployment does not carry is not found.",
		Fields: map[string]string{
			"DestinationField.example":    "a sample value of the right shape (\"G-XXXXXXX\"), when one helps",
			"DestinationField.key":        "the camelCase key on both the connect body and the stored config",
			"DestinationField.label":      "human label for the console card's input",
			"DestinationField.required":   "when true, a connect that leaves it empty is refused 400",
			"DestinationStatus.account":   "Account is the operator's own label for the connected account, as supplied on\nconnect. Absent when unset.",
			"DestinationStatus.category":  "groups the card: Analytics | Advertising",
			"DestinationStatus.config":    "Config is the org's stored NON-SECRET configuration — the measurement/pixel\nids keyed by DestinationField.Key. A secret is never in here; secrets live in\nKMS and only their names are published, in Secrets.",
			"DestinationStatus.connected": "Connected is true when this org has a stored row for the platform — it has\nbeen configured here at least once. It says nothing about whether a\ncredential still resolves; that is Live.",
			"DestinationStatus.enabled":   "Enabled is whether the fan-out forwards to this destination. False on a\ndestination that is connected but paused, and on one never connected.",
			"DestinationStatus.fields":    "Fields are the non-secret inputs this platform needs, which the console card\nrenders and the connect body fills.",
			"DestinationStatus.live":      "Live is whether a credential resolves RIGHT NOW: a KMS-sealed secret for this\norg, else the integrations connection named by the platform's Fallback, else\nno credential needed at all (a public-ingest sink like Umami). False on a\nconnected destination whose secret has gone missing — Connected && !Live is\nexactly the \"reconnect me\" state.",
			"DestinationStatus.name":      "the platform's display name (\"Google Analytics 4\")",
			"DestinationStatus.platform":  "the platform slug, and the path segment every route addresses it by",
			"DestinationStatus.secrets":   "Secrets are the KMS secret NAMES this platform custodies for the org — names\nonly, never values. The connect body accepts each under its camelCase form.",
			"destinationRef.platform":     "Platform is the destination to act on, from the path: ga4 | meta | tiktok |\nlinkedin | x | reddit | posthog | umami.",
		},
		Example: json.RawMessage(`{"platform":"ga4"}`),
	})
	zip.Describe("POST /v1/destinations/:platform/test", zip.Doc{
		Description: "test sends ONE synthetic pageview through the connected destination end to end\nand reports what the platform said. A send the platform refuses is reported as\ndata — {\"ok\": false, \"error\": …} at 200 — so the console shows the platform's\nown words rather than an error about Hanzo. It requires org admin.",
		Fields: map[string]string{
			"destinationRef.platform": "Platform is the destination to act on, from the path: ga4 | meta | tiktok |\nlinkedin | x | reddit | posthog | umami.",
			"destinationTest.error":   "Error is the platform's rejection, present only on a failed send.",
			"destinationTest.message": "Message is the platform's own note about the send, present only on success.",
			"destinationTest.ok":      "OK is true when the platform accepted the synthetic event.",
			"destinationTest.sent":    "Sent is how many events the platform accepted, present only on success.",
		},
		Example: json.RawMessage(`{"platform":"ga4"}`),
	})
}
