// Code generated by plane/gen; DO NOT EDIT.

// Package treasury is the typed client for the "treasury" app's internal ops.
//
// Every call here is a ZAP call BY NAME over the peer's unix socket — no URL, no
// env var, no HTTP round trip, and no way to reach the public edge by accident.
// That last one is not a style preference: treasury's own callers used to reach it
// through CLOUD_COMMERCE_HTTP_URL, which defaulted to the api.hanzo.ai edge —
// the SAME binary — so the forwarder re-entered itself and the billing gate died
// of it. A call by name cannot express that mistake.
//
// It depends on the CONTRACT (package plane) and never on treasury's implementation,
// so importing it costs a caller nothing but the types it is already sending.
package treasury

import (
	"context"

	"github.com/hanzoai/cloud/plane"
)

// App is the peer's name, which is also the socket it answers on. It is the
// ONE place this package spells it.
const App = "treasury"

// Ops is every op this peer answers, in the spelling the wire uses.
//
// It exists so a test can hold this generated surface against the LIVE plane
// registry and fail when they disagree — which is what lets this be generated
// from source without the document drifting away from the program. See
// plane_registry_test.go.
var Ops = []string{
	plane.TreasuryReserve,
}

// TreasuryReserve reserve fund balance.
//
// Calls plane.TreasuryReserve on treasury over the peer plane.
func TreasuryReserve(ctx context.Context) (*plane.Reserved, error) {
	return plane.Ask[struct{}, plane.Reserved](ctx, App, plane.TreasuryReserve, &struct{}{})
}
