// Code generated by zipdoc; DO NOT EDIT.

package ml

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("DELETE /v1/ml/models/:name", zip.Doc{
		Description: "deleteModel undeploys one model and answers 204. The serving endpoint stops as the\noperator tears the InferenceService down.",
		Fields: map[string]string{
			"ResourceRef.name": "Name is the resource name from the path, lower-cased.",
		},
		Example: json.RawMessage(`{"name":"sentiment"}`),
	})
	zip.Describe("DELETE /v1/train/experiments/:name", zip.Doc{
		Description: "deleteExperiment cancels one experiment and answers 204. Its trials are torn down\nwith it.",
		Fields: map[string]string{
			"ResourceRef.name": "Name is the resource name from the path, lower-cased.",
		},
		Example: json.RawMessage(`{"name":"lr-sweep"}`),
	})
	zip.Describe("DELETE /v1/train/jobs/:name", zip.Doc{
		Description: "deleteJob cancels one training job and answers 204. Compute stops as the operator\ntears the job down; anything already written to storage is kept.",
		Fields: map[string]string{
			"ResourceRef.name": "Name is the resource name from the path, lower-cased.",
		},
		Example: json.RawMessage(`{"name":"finetune-7b"}`),
	})
	zip.Describe("GET /v1/ml/models", zip.Doc{
		Description: "listModels returns the caller's deployed inference models. A tenant namespace that\ndoes not exist yet is an empty list, not an error.",
		Fields: map[string]string{
			"Resource.createdAt": "CreatedAt is when the resource was created, RFC3339.",
			"Resource.name":      "Name is the resource name, unique within the caller's tenant namespace.",
			"Resource.spec":      "Spec is the resource spec as submitted; sent on single-object reads only.",
			"Resource.status":    "Status is the operator-reported live status, absent until the operator writes one.",
			"ResourceList.items": "Items is the resources, without their specs.",
		},
	})
	zip.Describe("GET /v1/ml/models/:name", zip.Doc{
		Description: "getModel returns one deployed model with its spec and live serving status.",
		Fields: map[string]string{
			"Resource.createdAt": "CreatedAt is when the resource was created, RFC3339.",
			"Resource.name":      "Name is the resource name, unique within the caller's tenant namespace.",
			"Resource.spec":      "Spec is the resource spec as submitted; sent on single-object reads only.",
			"Resource.status":    "Status is the operator-reported live status, absent until the operator writes one.",
			"ResourceRef.name":   "Name is the resource name from the path, lower-cased.",
		},
		Example: json.RawMessage(`{"name":"sentiment"}`),
	})
	zip.Describe("GET /v1/train/experiments", zip.Doc{
		Description: "listExperiments returns the caller's hyperparameter-search experiments. A tenant\nnamespace that does not exist yet is an empty list, not an error.",
		Fields: map[string]string{
			"Resource.createdAt": "CreatedAt is when the resource was created, RFC3339.",
			"Resource.name":      "Name is the resource name, unique within the caller's tenant namespace.",
			"Resource.spec":      "Spec is the resource spec as submitted; sent on single-object reads only.",
			"Resource.status":    "Status is the operator-reported live status, absent until the operator writes one.",
			"ResourceList.items": "Items is the resources, without their specs.",
		},
	})
	zip.Describe("GET /v1/train/experiments/:name", zip.Doc{
		Description: "getExperiment returns one experiment with its search spec and best-trial status.",
		Fields: map[string]string{
			"Resource.createdAt": "CreatedAt is when the resource was created, RFC3339.",
			"Resource.name":      "Name is the resource name, unique within the caller's tenant namespace.",
			"Resource.spec":      "Spec is the resource spec as submitted; sent on single-object reads only.",
			"Resource.status":    "Status is the operator-reported live status, absent until the operator writes one.",
			"ResourceRef.name":   "Name is the resource name from the path, lower-cased.",
		},
		Example: json.RawMessage(`{"name":"lr-sweep"}`),
	})
	zip.Describe("GET /v1/train/experiments/:name/trials", zip.Doc{
		Description: "trials lists the individual runs a hyperparameter experiment has spawned. The\nexperiment is read first, so a name that does not exist — or belongs to another\ntenant — is a clean 404 rather than a silently empty list.",
		Fields: map[string]string{
			"Resource.createdAt":   "CreatedAt is when the resource was created, RFC3339.",
			"Resource.name":        "Name is the resource name, unique within the caller's tenant namespace.",
			"Resource.spec":        "Spec is the resource spec as submitted; sent on single-object reads only.",
			"Resource.status":      "Status is the operator-reported live status, absent until the operator writes one.",
			"ResourceRef.name":     "Name is the resource name from the path, lower-cased.",
			"TrialList.experiment": "Experiment is the owning experiment's name.",
			"TrialList.items":      "Items is the trials, without their specs.",
		},
		Example: json.RawMessage(`{"name":"lr-sweep"}`),
	})
	zip.Describe("GET /v1/train/jobs", zip.Doc{
		Description: "listJobs returns the caller's training jobs. A tenant namespace that does not exist\nyet is an empty list, not an error.",
		Fields: map[string]string{
			"Resource.createdAt": "CreatedAt is when the resource was created, RFC3339.",
			"Resource.name":      "Name is the resource name, unique within the caller's tenant namespace.",
			"Resource.spec":      "Spec is the resource spec as submitted; sent on single-object reads only.",
			"Resource.status":    "Status is the operator-reported live status, absent until the operator writes one.",
			"ResourceList.items": "Items is the resources, without their specs.",
		},
	})
	zip.Describe("GET /v1/train/jobs/:name", zip.Doc{
		Description: "getJob returns one training job with its spec and live run status.",
		Fields: map[string]string{
			"Resource.createdAt": "CreatedAt is when the resource was created, RFC3339.",
			"Resource.name":      "Name is the resource name, unique within the caller's tenant namespace.",
			"Resource.spec":      "Spec is the resource spec as submitted; sent on single-object reads only.",
			"Resource.status":    "Status is the operator-reported live status, absent until the operator writes one.",
			"ResourceRef.name":   "Name is the resource name from the path, lower-cased.",
		},
		Example: json.RawMessage(`{"name":"finetune-7b"}`),
	})
}
