// Code generated by zipdoc; DO NOT EDIT.

package templates

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("DELETE /v1/templates/:slug", zip.Doc{
		Description: "remove deletes the caller org's OWN starter kit. A slug they do not own is a\n404, never a delete: the DELETE binds org.",
		Fields: map[string]string{
			"kitRef.slug": "Slug is the starter kit to act on, from the path.",
		},
		Example: json.RawMessage(`{"slug":"acme-portal"}`),
	})
	zip.Describe("GET /v1/templates", zip.Doc{
		Description: "browse lists the public starter-kit catalog plus, for a validated caller, that\norg's own private kits. No request field can widen the scope: the org comes\nfrom the validated principal, so an anonymous or cross-org caller structurally\nsees the public catalog only.",
		Fields: map[string]string{
			"StarterKit.demo":     "live demo (<slug>.hanzo.app), when deployed",
			"StarterKit.org":      "owner of a PRIVATE template; empty in the public catalog",
			"StarterKit.variants": "the shapes this template ships in",
			"Variant.framework":   "only when it differs from the template's",
			"Variant.id":          "selector, unique within the template (\"react\", \"grid-3-fluid\")",
			"Variant.kind":        "the axis it varies: format | page | theme",
			"Variant.label":       "human label for the picker",
			"kitList.data":        "Data is the public catalog followed by the caller org's own kits.",
		},
	})
	zip.Describe("GET /v1/templates/:slug", zip.Doc{
		Description: "get returns one starter kit: the caller org's own by that slug, else the public\ncatalog's. A slug another org owns reads as not found.",
		Fields: map[string]string{
			"StarterKit.demo":     "live demo (<slug>.hanzo.app), when deployed",
			"StarterKit.org":      "owner of a PRIVATE template; empty in the public catalog",
			"StarterKit.variants": "the shapes this template ships in",
			"Variant.framework":   "only when it differs from the template's",
			"Variant.id":          "selector, unique within the template (\"react\", \"grid-3-fluid\")",
			"Variant.kind":        "the axis it varies: format | page | theme",
			"Variant.label":       "human label for the picker",
			"kitRef.slug":         "Slug is the starter kit to act on, from the path.",
		},
		Example: json.RawMessage(`{"slug":"folio"}`),
	})
	zip.Describe("POST /v1/templates", zip.Doc{
		Description: "publish creates a starter kit PRIVATE to the caller's org and answers 201 with\nthe stored kit. The owner is stamped by the server, so a body \"org\" is never\ntrusted; publishing over a public-catalog slug is 409, so a slug still names\nexactly one kit.",
		Fields: map[string]string{
			"StarterKit.demo":          "live demo (<slug>.hanzo.app), when deployed",
			"StarterKit.org":           "owner of a PRIVATE template; empty in the public catalog",
			"StarterKit.variants":      "the shapes this template ships in",
			"Variant.framework":        "only when it differs from the template's",
			"Variant.id":               "selector, unique within the template (\"react\", \"grid-3-fluid\")",
			"Variant.kind":             "the axis it varies: format | page | theme",
			"Variant.label":            "human label for the picker",
			"publishKitIn.category":    "Category groups the kit in the gallery browser.",
			"publishKitIn.demo":        "Demo is the deployed site itself, when there is one.",
			"publishKitIn.description": "Description is the browse-card blurb, max 4096 characters.",
			"publishKitIn.features":    "Features are the highlights the card lists, at most 32.",
			"publishKitIn.framework":   "Framework is the stack the kit is built on (\"Next.js 14\").",
			"publishKitIn.preview":     "Preview is the still image the browse card renders, max 4096 characters.",
			"publishKitIn.slug":        "Slug is the kit's identity — lowercase alphanumeric with dashes, max 40.",
			"publishKitIn.source":      "Source is the repository the kit is forked from, max 4096 characters.",
			"publishKitIn.title":       "Title is the display name. Required, max 200 characters.",
			"publishKitIn.useCase":     "UseCase is what the kit is for, in a phrase.",
			"publishKitIn.variants":    "Variants are the shapes this kit ships in, at most 32; the fork picks one.",
		},
		Example: json.RawMessage(`{"slug":"acme-portal","title":"Acme Internal Portal","framework":"Next.js 14"}`),
	})
	zip.Describe("PUT /v1/templates/:slug", zip.Doc{
		Description: "replace overwrites the caller org's OWN starter kit at the path slug, answering\nthe stored kit. A slug they do not own is 404, never a create: the UPDATE binds\norg, so a PUT can never reach another org's kit.",
		Fields: map[string]string{
			"StarterKit.demo":          "live demo (<slug>.hanzo.app), when deployed",
			"StarterKit.org":           "owner of a PRIVATE template; empty in the public catalog",
			"StarterKit.variants":      "the shapes this template ships in",
			"Variant.framework":        "only when it differs from the template's",
			"Variant.id":               "selector, unique within the template (\"react\", \"grid-3-fluid\")",
			"Variant.kind":             "the axis it varies: format | page | theme",
			"Variant.label":            "human label for the picker",
			"replaceKitIn.category":    "Category groups the kit in the gallery browser.",
			"replaceKitIn.demo":        "Demo is the deployed site itself, when there is one.",
			"replaceKitIn.description": "Description is the browse-card blurb, max 4096 characters.",
			"replaceKitIn.features":    "Features are the highlights the card lists, at most 32.",
			"replaceKitIn.framework":   "Framework is the stack the kit is built on (\"Next.js 14\").",
			"replaceKitIn.preview":     "Preview is the still image the browse card renders, max 4096 characters.",
			"replaceKitIn.slug":        "Slug is the kit to replace, from the path.",
			"replaceKitIn.source":      "Source is the repository the kit is forked from, max 4096 characters.",
			"replaceKitIn.title":       "Title is the display name. Required, max 200 characters.",
			"replaceKitIn.useCase":     "UseCase is what the kit is for, in a phrase.",
			"replaceKitIn.variants":    "Variants are the shapes this kit ships in, at most 32; the fork picks one.",
		},
		Example: json.RawMessage(`{"slug":"acme-portal","title":"Acme Internal Portal v2"}`),
	})
}
