// Code generated by zipdoc; DO NOT EDIT.

package captable

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("DELETE /v1/captable/convertibles/:id", zip.Doc{
		Description: "DeleteConvertible removes one of the caller org's convertible notes, taking its\nprincipal out of the cap table's unconverted-instrument totals. An id this org\ndoes not hold is not found.",
		Fields: map[string]string{
			"captableDeleted.success": "Success is true when the row was removed.",
			"noteRef.id":              "ID is the convertible note to delete.",
		},
	})
	zip.Describe("DELETE /v1/captable/options/:id", zip.Doc{
		Description: "DeleteOption removes one of the caller org's option grants, taking its shares\nout of the cap table's granted-options and fully-diluted counts. An id this org\ndoes not hold is not found.",
		Fields: map[string]string{
			"captableDeleted.success": "Success is true when the row was removed.",
			"optionRef.id":            "ID is the option grant to delete.",
		},
	})
	zip.Describe("DELETE /v1/captable/safes/:id", zip.Doc{
		Description: "DeleteSafe removes one of the caller org's SAFEs, taking its capital out of the\ncap table's unconverted-instrument totals. An id this org does not hold is not\nfound.",
		Fields: map[string]string{
			"captableDeleted.success": "Success is true when the row was removed.",
			"safeRef.id":              "ID is the SAFE to delete.",
		},
	})
	zip.Describe("DELETE /v1/captable/shares/:id", zip.Doc{
		Description: "DeleteShare removes one of the caller org's share certificates, taking its\nshares out of the cap table's outstanding and fully-diluted counts. An id this\norg does not hold is not found.",
		Fields: map[string]string{
			"captableDeleted.success": "Success is true when the row was removed.",
			"shareRef.id":             "ID is the share certificate to delete.",
		},
	})
	zip.Describe("DELETE /v1/captable/stakeholders/:id", zip.Doc{
		Description: "DeleteStakeholder removes one of the caller org's stakeholders. It REFUSES to\norphan issued equity: a holder that still holds share certificates or option\ngrants cannot be deleted, and answers 400 saying so — release or transfer the\nholdings first. An id this org does not hold is not found.",
		Fields: map[string]string{
			"captableDeleted.success": "Success is true when the row was removed.",
			"stakeholderRef.id":       "ID is the stakeholder to delete.",
		},
	})
	zip.Describe("GET /v1/captable/classes", zip.Doc{
		Description: "ListShareClasses returns the caller org's share classes, in creation order. A\nshare class is what a certificate is issued in, and every class the company\nhas authorized appears. The response is a bare JSON array, not an envelope.",
		Fields: map[string]string{
			"captableShareClass.classType":                     "ClassType is COMMON or PREFERRED.",
			"captableShareClass.companyName":                   "CompanyName is the name of the company whose cap table this is.",
			"captableShareClass.conversionRights":              "ConversionRights describes what the class converts into, e.g.\nCONVERTS_TO_FUTURE_ROUND.",
			"captableShareClass.id":                            "ID is the share class id.",
			"captableShareClass.idx":                           "Idx is the class's 1-based position within the company, in creation order.",
			"captableShareClass.initialSharesAuthorized":       "InitialSharesAuthorized is how many shares of this class are authorized.",
			"captableShareClass.liquidationPreferenceMultiple": "LiquidationPreferenceMultiple is the preference multiple on liquidation.",
			"captableShareClass.name":                          "Name is the class name, e.g. \"Common\" or \"Series A Preferred\".",
			"captableShareClass.parValue":                      "ParValue is the par value per share.",
			"captableShareClass.participationCapMultiple":      "ParticipationCapMultiple caps participation on liquidation; 0 is uncapped.",
			"captableShareClass.prefix":                        "Prefix is the certificate prefix, CS for common and PS for preferred.",
			"captableShareClass.pricePerShare":                 "PricePerShare is the issue price per share.",
			"captableShareClass.seniority":                     "Seniority orders classes in a liquidation waterfall; higher is more senior.",
			"captableShareClass.votesPerShare":                 "VotesPerShare is how many votes one share of this class carries.",
		},
	})
	zip.Describe("GET /v1/captable/company", zip.Doc{
		Description: "GetCompany returns the caller org's cap-table company record. The row is\nseeded when the tenant's store first opens, so it always exists; its name and\nincorporation details are set with PUT /v1/captable/company.",
		Fields: map[string]string{
			"captableCompany.createdAt":            "CreatedAt is when the company row was seeded, in unix milliseconds.",
			"captableCompany.id":                   "ID is the company id, which is the tenant's own org id.",
			"captableCompany.incorporationCountry": "IncorporationCountry is the ISO country the entity is incorporated in.",
			"captableCompany.incorporationState":   "IncorporationState is the state or province of incorporation.",
			"captableCompany.incorporationType":    "IncorporationType is the entity kind, e.g. LLC or C_CORP.",
			"captableCompany.name":                 "Name is the company's legal name.",
			"captableCompany.publicId":             "PublicID is the company's shareable public identifier.",
			"captableCompany.updatedAt":            "UpdatedAt is when the company row last changed, in unix milliseconds.",
		},
	})
	zip.Describe("GET /v1/captable/convertibles", zip.Doc{
		Description: "ListConvertibles returns the caller org's convertible notes, newest first. A\nnote's principal sits OUTSIDE issued equity until it converts, so it is not\npart of the share counts.",
		Fields: map[string]string{
			"captableNote.capital":         "Capital is the principal the investor lent.",
			"captableNote.conversionCap":   "ConversionCap is the valuation cap on conversion, if any.",
			"captableNote.discountRate":    "DiscountRate is the discount to the next round's price, if any.",
			"captableNote.id":              "ID is the note id.",
			"captableNote.interestRate":    "InterestRate is the annual interest rate, if any.",
			"captableNote.issueDate":       "IssueDate is the ISO date the note was signed.",
			"captableNote.publicId":        "PublicID is the note's shareable identifier, unique within the company.",
			"captableNote.stakeholderId":   "StakeholderID is the investor.",
			"captableNote.stakeholderName": "StakeholderName is that investor's name.",
			"captableNote.status":          "Status is the note's state, e.g. DRAFT or ACTIVE.",
			"captableNote.type":            "Type is the instrument kind, e.g. NOTE.",
			"captableNotes.data":           "Data is every convertible note, newest first.",
		},
	})
	zip.Describe("GET /v1/captable/investments", zip.Doc{
		Description: "ListInvestments returns the caller org's investments, newest first. It spans\nevery round, so it is the flat ledger of cheques written into the company,\neach naming its investor and the round it went into.",
		Fields: map[string]string{
			"captableInvestment.amount":          "Amount is the cash invested.",
			"captableInvestment.date":            "Date is the ISO date of the investment.",
			"captableInvestment.id":              "ID is the investment id.",
			"captableInvestment.roundId":         "RoundID is the round the cheque went into.",
			"captableInvestment.shareClassId":    "ShareClassID is the class shares were issued in, for a priced round.",
			"captableInvestment.shares":          "Shares is how many shares the investment bought; 0 when the round issues\nno equity at the time of investment.",
			"captableInvestment.stakeholderId":   "StakeholderID is the investor.",
			"captableInvestment.stakeholderName": "StakeholderName is that investor's name.",
			"captableInvestments.data":           "Data is every investment across every round, newest first.",
		},
	})
	zip.Describe("GET /v1/captable/options", zip.Doc{
		Description: "ListOptions returns the caller org's option grants, newest first. Each row is\njoined to its grantee and its equity plan. Grants that are EXERCISED, EXPIRED\nor CANCELLED are listed here but do not dilute the cap table.",
		Fields: map[string]string{
			"captableOption.cliffYears":      "CliffYears is how many years before any of the grant vests.",
			"captableOption.equityPlanId":    "EquityPlanID is the plan the grant draws from.",
			"captableOption.equityPlanName":  "EquityPlanName is that plan's name.",
			"captableOption.exercisePrice":   "ExercisePrice is the strike price per share.",
			"captableOption.expirationDate":  "ExpirationDate is the ISO date the grant expires.",
			"captableOption.grantId":         "GrantID is the grant number, unique within the company.",
			"captableOption.id":              "ID is the option id.",
			"captableOption.issueDate":       "IssueDate is the ISO date the grant was issued.",
			"captableOption.quantity":        "Quantity is how many shares the grant covers.",
			"captableOption.stakeholderId":   "StakeholderID is the grantee.",
			"captableOption.stakeholderName": "StakeholderName is that grantee's name.",
			"captableOption.status":          "Status is the grant's state, e.g. DRAFT, ACTIVE, EXERCISED, EXPIRED or\nCANCELLED. Only non-terminal grants dilute the cap table.",
			"captableOption.type":            "Type is the grant kind, ISO or NSO.",
			"captableOption.vestingYears":    "VestingYears is the total vesting period in years.",
			"captableOptions.data":           "Data is every option grant, newest first.",
		},
	})
	zip.Describe("GET /v1/captable/plans", zip.Doc{
		Description: "ListEquityPlans returns the caller org's equity plans, newest first. An equity\nplan is an option pool: a reserve of shares, drawn from one share class, that\noption grants are written against.",
		Fields: map[string]string{
			"captableEquityPlan.boardApprovalDate":          "BoardApprovalDate is the ISO date the board approved the plan.",
			"captableEquityPlan.comments":                   "Comments is free-form notes on the plan.",
			"captableEquityPlan.createdAt":                  "CreatedAt is when the plan was recorded, in unix milliseconds.",
			"captableEquityPlan.defaultCancellatonBehavior": "DefaultCancellatonBehavior is what happens to cancelled grants, RETIRE or\nRETURN_TO_POOL. The key is spelled as the cap-table wire spells it.",
			"captableEquityPlan.id":                         "ID is the equity plan id.",
			"captableEquityPlan.initialSharesReserved":      "InitialSharesReserved is how many shares the plan reserves.",
			"captableEquityPlan.name":                       "Name is the plan name, e.g. \"2026 Stock Option Plan\".",
			"captableEquityPlan.planEffectiveDate":          "PlanEffectiveDate is the ISO date the plan takes effect.",
			"captableEquityPlan.shareClassId":               "ShareClassID is the class the reserved shares come from.",
			"captableEquityPlans.data":                      "Data is every equity plan on the caller org's cap table, newest first.",
		},
	})
	zip.Describe("GET /v1/captable/rounds", zip.Doc{
		Description: "ListRounds returns the caller org's fundraising rounds, newest first. A round\ngroups a fundraising event; a PRICED round also carries the share class and\nprice per share it issues at.",
		Fields: map[string]string{
			"captableRound.closeDate":         "CloseDate is the ISO date the round closed, once it has.",
			"captableRound.createdAt":         "CreatedAt is when the round was recorded, in unix milliseconds.",
			"captableRound.id":                "ID is the round id.",
			"captableRound.name":              "Name is the round name, e.g. \"Series A\".",
			"captableRound.preMoneyValuation": "PreMoneyValuation is the pre-money valuation, for a priced round.",
			"captableRound.pricePerShare":     "PricePerShare is the price per share, for a priced round.",
			"captableRound.raisedAmount":      "RaisedAmount is how much has been invested so far.",
			"captableRound.roundType":         "RoundType is PRICED, SAFE or CONVERTIBLE_NOTE.",
			"captableRound.shareClassId":      "ShareClassID is the class a priced round issues into.",
			"captableRound.status":            "Status is OPEN or CLOSED.",
			"captableRound.targetAmount":      "TargetAmount is how much the round set out to raise.",
			"captableRounds.data":             "Data is every round, newest first.",
		},
	})
	zip.Describe("GET /v1/captable/rounds/:id", zip.Doc{
		Description: "GetRound returns one of the caller org's fundraising rounds together with every\ninvestment written into it, oldest first. A round id that does not exist in the\ncaller's org is not found — including one that exists in another tenant, since\nthe org comes from the caller's principal and is part of the lookup.",
		Fields: map[string]string{
			"captableRound.closeDate":                 "CloseDate is the ISO date the round closed, once it has.",
			"captableRound.createdAt":                 "CreatedAt is when the round was recorded, in unix milliseconds.",
			"captableRound.id":                        "ID is the round id.",
			"captableRound.name":                      "Name is the round name, e.g. \"Series A\".",
			"captableRound.preMoneyValuation":         "PreMoneyValuation is the pre-money valuation, for a priced round.",
			"captableRound.pricePerShare":             "PricePerShare is the price per share, for a priced round.",
			"captableRound.raisedAmount":              "RaisedAmount is how much has been invested so far.",
			"captableRound.roundType":                 "RoundType is PRICED, SAFE or CONVERTIBLE_NOTE.",
			"captableRound.shareClassId":              "ShareClassID is the class a priced round issues into.",
			"captableRound.status":                    "Status is OPEN or CLOSED.",
			"captableRound.targetAmount":              "TargetAmount is how much the round set out to raise.",
			"captableRoundDetail.investments":         "Investments is every investment into this round, oldest first.",
			"captableRoundDetail.round":               "Round is the round itself.",
			"captableRoundInvestment.amount":          "Amount is the cash invested.",
			"captableRoundInvestment.comments":        "Comments is the note recorded with the cheque, if any.",
			"captableRoundInvestment.date":            "Date is the ISO date of the investment.",
			"captableRoundInvestment.id":              "ID is the investment id.",
			"captableRoundInvestment.shares":          "Shares is how many shares the investment bought; 0 when the round issues no\nequity at the time of investment.",
			"captableRoundInvestment.stakeholderId":   "StakeholderID is the investor.",
			"captableRoundInvestment.stakeholderName": "StakeholderName is that investor's name.",
			"roundRef.id":                             "ID is the round to read. It is the path segment: the URL is the addressing\nauthority, and the org it is resolved in comes from the caller's principal,\nso an id from another tenant is simply not found.",
		},
	})
	zip.Describe("GET /v1/captable/safes", zip.Doc{
		Description: "ListSafes returns the caller org's SAFEs, newest first. A SAFE is a simple\nagreement for future equity: its capital sits OUTSIDE issued equity until it\nconverts, so it is not part of the share counts.",
		Fields: map[string]string{
			"captableSafe.capital":         "Capital is the cash the investor put in.",
			"captableSafe.discountRate":    "DiscountRate is the discount to the next round's price, if any.",
			"captableSafe.id":              "ID is the SAFE id.",
			"captableSafe.issueDate":       "IssueDate is the ISO date the SAFE was signed.",
			"captableSafe.mfn":             "MFN is true when the SAFE carries a most-favoured-nation clause.",
			"captableSafe.proRata":         "ProRata is true when the SAFE carries pro-rata rights.",
			"captableSafe.publicId":        "PublicID is the SAFE's shareable identifier, unique within the company.",
			"captableSafe.stakeholderId":   "StakeholderID is the investor.",
			"captableSafe.stakeholderName": "StakeholderName is that investor's name.",
			"captableSafe.status":          "Status is the SAFE's state, e.g. DRAFT or ACTIVE.",
			"captableSafe.type":            "Type is POST_MONEY or PRE_MONEY.",
			"captableSafe.valuationCap":    "ValuationCap is the valuation cap, if any.",
			"captableSafes.data":           "Data is every SAFE, newest first.",
		},
	})
	zip.Describe("GET /v1/captable/shares", zip.Doc{
		Description: "ListShares returns the caller org's share certificates, newest first. Each row\nis joined to its holder and its share class, so a certificate names who holds\nit and what class it is in without a second call.",
		Fields: map[string]string{
			"captableShare.capitalContribution": "CapitalContribution is the cash paid for the certificate, if recorded.",
			"captableShare.certificateId":       "CertificateID is the certificate number, unique within the company.",
			"captableShare.companyLegends":      "CompanyLegends are the restrictive legends printed on the certificate.",
			"captableShare.id":                  "ID is the share id.",
			"captableShare.issueDate":           "IssueDate is the ISO date the certificate was issued.",
			"captableShare.pricePerShare":       "PricePerShare is the price paid per share, if recorded.",
			"captableShare.quantity":            "Quantity is how many shares the certificate covers.",
			"captableShare.shareClassId":        "ShareClassID is the class the shares belong to.",
			"captableShare.shareClassName":      "ShareClassName is that class's name.",
			"captableShare.shareClassType":      "ShareClassType is that class's type, COMMON or PREFERRED.",
			"captableShare.stakeholderId":       "StakeholderID is the holder of the certificate.",
			"captableShare.stakeholderName":     "StakeholderName is that holder's name.",
			"captableShare.status":              "Status is ACTIVE or DRAFT.",
			"captableShares.data":               "Data is every issued share certificate, newest first.",
		},
	})
	zip.Describe("GET /v1/captable/stakeholders", zip.Doc{
		Description: "ListStakeholders returns the caller org's stakeholders, newest first. The\nresponse is a bare JSON array, not an envelope. Each row carries the holder's\ncontact and address fields alongside the company's name.",
		Fields: map[string]string{
			"captableStakeholder.city":                "City is the stakeholder's city, if recorded.",
			"captableStakeholder.companyName":         "CompanyName is the name of the company whose cap table this is.",
			"captableStakeholder.country":             "Country is the stakeholder's two-letter country code.",
			"captableStakeholder.createdAt":           "CreatedAt is when the stakeholder was added, in unix milliseconds.",
			"captableStakeholder.currentRelationship": "CurrentRelationship is how the stakeholder relates to the company, e.g.\nFOUNDER, INVESTOR or EMPLOYEE.",
			"captableStakeholder.email":               "Email is the stakeholder's email, unique within the company.",
			"captableStakeholder.id":                  "ID is the stakeholder id.",
			"captableStakeholder.institutionName":     "InstitutionName names the institution, when the stakeholder is one.",
			"captableStakeholder.name":                "Name is the stakeholder's full name.",
			"captableStakeholder.stakeholderType":     "StakeholderType is INDIVIDUAL or INSTITUTION.",
			"captableStakeholder.state":               "State is the stakeholder's state or province, if recorded.",
			"captableStakeholder.streetAddress":       "StreetAddress is the stakeholder's street address, if recorded.",
			"captableStakeholder.taxId":               "TaxID is the stakeholder's tax identifier, if recorded.",
			"captableStakeholder.zipcode":             "Zipcode is the stakeholder's postal code, if recorded.",
		},
	})
	zip.Describe("GET /v1/captable/summary", zip.Doc{
		Description: "GetSummary computes the caller org's cap table. It answers who owns what on a\nfully-diluted basis: outstanding shares, granted options, per-stakeholder\nownership percentages, each share class's authorized versus issued position,\nand the capital sitting on SAFEs and convertible notes that have not yet\nconverted. Only non-terminal option grants dilute — EXERCISED, EXPIRED and\nCANCELLED grants are excluded, so equity issued through an exercised option is\nnever counted twice.",
		Fields: map[string]string{
			"captableClassHolding.authorized":   "Authorized is how many shares of the class are authorized.",
			"captableClassHolding.classType":    "ClassType is COMMON or PREFERRED.",
			"captableClassHolding.issued":       "Issued is how many shares of the class have been issued.",
			"captableClassHolding.name":         "Name is the class name.",
			"captableClassHolding.shareClassId": "ShareClassID is the share class.",
			"captableConvertibles.notes":        "Notes is the convertible notes total.",
			"captableConvertibles.safes":        "Safes is the SAFEs total.",
			"captableHolding.fullyDiluted":      "FullyDiluted is shares plus options.",
			"captableHolding.name":              "Name is the stakeholder's name.",
			"captableHolding.options":           "Options is the shares under this stakeholder's non-terminal option grants.",
			"captableHolding.ownershipPct":      "OwnershipPct is fullyDiluted as a percentage of the company's\nfullyDilutedShares, rounded to two decimals; 0 when nothing is issued.",
			"captableHolding.shares":            "Shares is the shares this stakeholder holds by certificate.",
			"captableHolding.stakeholderId":     "StakeholderID is the stakeholder.",
			"captableInstrumentTotal.capital":   "Capital is the total capital across those instruments.",
			"captableInstrumentTotal.count":     "Count is how many instruments there are.",
			"captableRoundTotals.count":         "Count is how many rounds the company has recorded.",
			"captableRoundTotals.totalRaised":   "TotalRaised is the sum of every round's raised amount.",
			"captableSummary.byShareClass":      "ByShareClass is each share class's authorized-versus-issued position, in\nclass creation order.",
			"captableSummary.byStakeholder":     "ByStakeholder is each stakeholder's position, largest holding first.",
			"captableSummary.company":           "Company names the company the cap table is computed for.",
			"captableSummary.convertibles":      "Convertibles is the capital on SAFEs and notes that have not converted.",
			"captableSummary.rounds":            "Rounds is the fundraising rollup.",
			"captableSummary.totals":            "Totals is the company-wide share count.",
			"captableSummaryCompany.id":         "ID is the company id, which is the tenant's own org id.",
			"captableSummaryCompany.name":       "Name is the company's legal name.",
			"captableTotals.fullyDilutedShares": "FullyDilutedShares is outstandingShares plus grantedOptions.",
			"captableTotals.grantedOptions":     "GrantedOptions is the shares under non-terminal option grants — grants that\nare EXERCISED, EXPIRED or CANCELLED are excluded, so nothing double-counts.",
			"captableTotals.outstandingShares":  "OutstandingShares is the sum of every issued share certificate.",
			"captableTotals.shareClasses":       "ShareClasses is how many share classes the company has authorized.",
			"captableTotals.stakeholders":       "Stakeholders is how many stakeholders the company has.",
		},
	})
	zip.Describe("PATCH /v1/captable/stakeholders/:id", zip.Doc{
		Description: "UpdateStakeholder changes one of the caller org's stakeholders. It is a\nPARTIAL update: only the fields the request names are written, and a field\nsent as null clears that column. A request that names no updatable field is\nrefused, and an id this org does not hold is not found.\n\nThe values are stored as sent. Unlike adding a stakeholder, this route does\nnot check the email's shape or the type and relationship vocabularies, so it\ncan record a value that adding one would have rejected.",
		Fields: map[string]string{
			"captableStakeholderPatch.city":                "City is the stakeholder's city.",
			"captableStakeholderPatch.currentRelationship": "CurrentRelationship is how the stakeholder relates to the company, e.g.\nFOUNDER, INVESTOR or EMPLOYEE. This route stores it as sent — unlike\nadding a stakeholder, it is not checked against the vocabulary.",
			"captableStakeholderPatch.email":               "Email is the stakeholder's email. This route stores it as sent — unlike\nadding a stakeholder, it is not checked for shape or uniqueness.",
			"captableStakeholderPatch.id":                  "ID is the stakeholder to update. It is the path segment: the URL is the\naddressing authority, and the org it is resolved in comes from the\ncaller's principal, so an id from another tenant is simply not found.",
			"captableStakeholderPatch.institutionName":     "InstitutionName names the institution, when the stakeholder is one.",
			"captableStakeholderPatch.name":                "Name is the stakeholder's full name.",
			"captableStakeholderPatch.stakeholderType":     "StakeholderType is INDIVIDUAL or INSTITUTION. This route stores it as\nsent — unlike adding a stakeholder, it is not checked against the\nvocabulary.",
			"captableStakeholderPatch.state":               "State is the stakeholder's state or province.",
			"captableStakeholderPatch.streetAddress":       "StreetAddress is the stakeholder's street address.",
			"captableStakeholderPatch.taxId":               "TaxID is the stakeholder's tax identifier.",
			"captableStakeholderPatch.zipcode":             "Zipcode is the stakeholder's postal code.",
			"captableUpdated.message":                      "Message is the human sentence the cap table wrote, e.g. \"Company updated\".",
			"captableUpdated.success":                      "Success is true when the update was applied.",
		},
	})
	zip.Describe("POST /v1/captable/rounds/:id/close", zip.Doc{
		Description: "CloseRound closes one of the caller org's fundraising rounds, recording the\nclose date and moving its status to CLOSED. Only an OPEN round can be closed:\na round that is already closed — like an id this org does not hold — is not\nfound. Closing a round does not change what was invested in it.",
		Fields: map[string]string{
			"captableRoundCloseRequest.closeDate": "CloseDate is the date to record the round as closed on. Optional: omitted,\nnull or empty records TODAY. Any JSON scalar is accepted and stored as its\ntext, and the text is stored unparsed, so a caller that wants an ISO date\nsends one.",
			"captableRoundCloseRequest.id":        "ID is the round to close. It is the path segment: the URL is the\naddressing authority, and the org it is resolved in comes from the\ncaller's principal, so an id from another tenant is simply not found.",
			"captableUpdated.message":             "Message is the human sentence the cap table wrote, e.g. \"Company updated\".",
			"captableUpdated.success":             "Success is true when the update was applied.",
		},
	})
	zip.Describe("PUT /v1/captable/company", zip.Doc{
		Description: "UpdateCompany sets the caller org's company name and incorporation details.\nThe name is required; the three incorporation fields are optional and each is\nstored as empty when omitted, so a call that sends only a name CLEARS them.\nThe company row itself is seeded when the tenant's store first opens, so this\nnever creates one.",
		Fields: map[string]string{
			"captableCompanyUpdate.incorporationCountry": "IncorporationCountry is the ISO country the entity is incorporated in.\nOptional; omitted, null or empty clears it. Any JSON scalar is accepted\nand stored as its text.",
			"captableCompanyUpdate.incorporationState":   "IncorporationState is the state or province of incorporation. Optional;\nomitted, null or empty clears it. Any JSON scalar is accepted and stored\nas its text.",
			"captableCompanyUpdate.incorporationType":    "IncorporationType is the entity kind, e.g. LLC or C_CORP. Optional;\nomitted, null or empty clears it. Any JSON scalar is accepted and stored\nas its text.",
			"captableCompanyUpdate.name":                 "Name is the company's legal name. Required, and it must be a non-empty\nstring — anything else is refused with the cap table's own validation\nerror.",
			"captableUpdated.message":                    "Message is the human sentence the cap table wrote, e.g. \"Company updated\".",
			"captableUpdated.success":                    "Success is true when the update was applied.",
		},
	})
}
