/**
 * The papers' tables, from runs/ and ablations/ — LaTeX out, nothing typed.
 *
 * Writes into ../../../papers/tables/ (hanzoai/papers checked out beside cloud):
 *   locomo-ablation.tex   every retrieval row on all ten conversations and on test
 *   locomo-minilm.tex     the same rows with all-MiniLM-L6-v2 vectors at k=10
 *   sweep.tex             the dev search: parameter, range, start, chosen
 *   conv.tex              LoCoMo-Conv: unreleased; the proxy check that stands in
 *   locomo-answers.tex    answer rows per reader (when runs/locomo-* carry metrics)
 *   mab-fc.tex            MemoryAgentBench FC per size (when runs/mab-* carry metrics)
 *   coverage.tex          write-side coverage (when a coverage run exists)
 * A table whose runs are missing is left as the placeholder it already is.
 *
 *   node tables.mjs [--out=/path/to/papers/tables]
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'

const arg = (k, d) => { const m = process.argv.find((a) => a.startsWith(`--${k}=`)); return m ? m.slice(k.length + 3) : d }
const here = new URL('.', import.meta.url)
const OUT = arg('out', new URL('../../../papers/tables/', here).pathname)
const read = (p) => JSON.parse(readFileSync(p, 'utf8'))
const run = (name) => { const p = new URL(`./runs/${name}/metrics.json`, here); return existsSync(p) ? read(p) : null }
const runs = existsSync(new URL('./runs/', here)) ? readdirSync(new URL('./runs/', here)) : []
const pct = (x, d = 1) => x == null ? '\\ldots' : (x * 100).toFixed(d)
const mean = (v) => (v && typeof v === 'object' && 'mean' in v ? v.mean : v)
const esc = (s) => String(s).replace(/&/g, '\\&').replace(/%/g, '\\%').replace(/_/g, '\\_')
const write = (name, body, note) => { writeFileSync(`${OUT}/${name}`, `% generated by hanzoai/cloud bench/brain/tables.mjs — ${note}\n${body}`); console.log(`wrote ${name}`) }

const ROWS = ['semantic-only', 'lexical', 'facts', 'entities', 'timeline', 'adjacency', 'typed-graph', 'iterative-hops', 'full-facets', 'failed-prf', 'failed-multi-query-rrf', 'failed-chain-search', 'failed-surface-entities', 'failed-global-rrf']
const LABEL = { 'semantic-only': 'cosine over turns', lexical: '+ BM25', facts: '+ atomic fact index', entities: '+ canonical entities', timeline: '+ timeline', adjacency: '+ adjacency', 'typed-graph': '+ typed expansion', 'iterative-hops': '+ second hop from resolved state', 'full-facets': '+ query facets (full)',
  'failed-prf': 'pseudo-relevance feedback', 'failed-multi-query-rrf': 'multi-query, reciprocal-rank fusion', 'failed-chain-search': 'chain search (top turn as query)', 'failed-surface-entities': 'surface-entity expansion', 'failed-global-rrf': 'global reciprocal-rank fusion' }

// ── retrieval ablation: all ten and test, k=20, LoCoMo facts
function ablation(split, embed = '', k = 20) {
  const rows = []
  for (const r of ROWS) { const m = run(`locomo-retrieval-${split}-${r}-locomo${embed ? '-' + embed : ''}`); if (!m) continue; const s = m.summary
    const c = (cat, key) => pct(mean(s[cat]?.[key]))
    rows.push(`${LABEL[r]} & ${c('1', `all@${k}`)} & ${c('1', `any@${k}`)} & ${c('4', `all@${k}`)} & ${c('2', `all@${k}`)} & ${c('3', `all@${k}`)} & ${pct(mean(s.all?.[`recall@${k}`]))} & ${pct(mean(s.all?.[`ndcg@${k}`]))} & ${pct(mean(s.all?.supported))} & ${s.all?.examined?.toFixed(0) ?? '\\ldots'} & ${s.all?.p50?.toFixed(2) ?? '\\ldots'} \\\\`) }
  return rows
}
for (const [split, embed, k, file, note] of [['all', '', 20, 'locomo-ablation.tex', 'all ten conversations, k=20, LoCoMo facts, frozen weights'], ['test', '', 20, 'locomo-ablation-test.tex', 'test split (conversations 3–9), k=20, frozen at the dev sweep'], ['all', 'minilm', 10, 'locomo-minilm.tex', 'all-MiniLM-L6-v2 vectors, k=10, LoCoMo-Conv protocol embedder']]) {
  const rows = ablation(split, embed, k); if (!rows.length) continue
  const failedAt = rows.findIndex((r) => /pseudo|multi-query|chain|surface|global/.test(r))
  const body = `\\begin{tabular}{lrrrrrrrrrr}\n\\toprule\n & \\multicolumn{2}{c}{multi-hop} & single & temporal & open & all & & & pool & p50 \\\\\n\\cmidrule(lr){2-3}\nConfiguration & ALL@${k} & ANY@${k} & ALL@${k} & ALL@${k} & ALL@${k} & R@${k} & nDCG & supported & cands & ms \\\\\n\\midrule\n${rows.slice(0, failedAt < 0 ? rows.length : failedAt).join('\n')}\n${failedAt >= 0 ? '\\midrule\n' + rows.slice(failedAt).join('\n') + '\n' : ''}\\bottomrule\n\\end{tabular}\n`
  write(file, body, note)
}

// ── by k, the frozen configuration on test and on all ten (multi-hop ALL, ANY)
{
  const rows = []
  for (const [split, name] of [['test', 'test split'], ['all', 'all ten']]) { const m = run(`locomo-retrieval-${split}-iterative-hops-locomo`); if (!m) continue; const s = m.summary
    rows.push(`${name}, multi-hop ALL & ${pct(mean(s['1']?.['all@5']))} & ${pct(mean(s['1']?.['all@10']))} & ${pct(mean(s['1']?.['all@20']))} \\\\`)
    rows.push(`${name}, multi-hop ANY & ${pct(mean(s['1']?.['any@5']))} & ${pct(mean(s['1']?.['any@10']))} & ${pct(mean(s['1']?.['any@20']))} \\\\`)
    rows.push(`${name}, single-hop ALL & ${pct(mean(s['4']?.['all@5']))} & ${pct(mean(s['4']?.['all@10']))} & ${pct(mean(s['4']?.['all@20']))} \\\\`) }
  if (rows.length) write('locomo-byk.tex', `\\begin{tabular}{lrrr}\n\\toprule\nfrozen configuration & $k=5$ & $k=10$ & $k=20$ \\\\\n\\midrule\n${rows.join('\n')}\n\\bottomrule\n\\end{tabular}\n`, 'the frozen engine by k; a number quoted from here carries its k')
}

// ── the sweep
const sweepFile = new URL('./ablations/sweep-locomo.json', here), frozenFile = new URL('./ablations/frozen-locomo.json', here)
if (existsSync(sweepFile) && existsSync(frozenFile)) {
  const s = read(sweepFile), z = read(frozenFile), first = s.evaluations[0]
  const GRID = { 'w.fact': '0.10–0.40', 'w.lex': '0–0.30', 'w.ent': '0–0.20', 'w.time': '0–0.12', 'w.adj': '0–0.10', 'w.exp': '0–0.15', 'w.hop': '0–0.45', 'w.facet': '0–0.30', 'budget.dense': '20–60', 'budget.fact': '10–30', 'budget.lex': '10–30', 'budget.hop': '5–15' }
  const NAME = { 'w.fact': 'fact weight', 'w.lex': 'BM25 weight', 'w.ent': 'entity weight', 'w.time': 'temporal weight', 'w.adj': 'adjacency weight', 'w.exp': 'expansion weight', 'w.hop': 'second-hop weight', 'w.facet': 'facet weight', 'budget.dense': 'dense pool', 'budget.fact': 'fact pool', 'budget.lex': 'BM25 pool', 'budget.hop': 'second-hop pool' }
  const rows = Object.keys(GRID).map((p) => { const [kind, key] = p.split('.'); const start = kind === 'w' ? first.w[key] : first.budget[key], chosen = kind === 'w' ? z.w[key] : z.budget[key]; return `${NAME[p]} & ${GRID[p]} & ${start} & ${chosen === start ? `${chosen}` : `\\textbf{${chosen}}`} \\\\` })
  const test = run('locomo-retrieval-test-iterative-hops-locomo')?.summary
  const body = `\\begin{tabular}{lrrr}\n\\toprule\nParameter & range searched & start & chosen \\\\\n\\midrule\n${rows.join('\n')}\n\\midrule\n\\multicolumn{4}{l}{dev objective (mean over categories of (ALL@20 + nDCG@20)/2): ${pct(first.objective)} $\\rightarrow$ ${pct(z.objective)} over ${s.evaluations.length} evaluations} \\\\\n\\multicolumn{4}{l}{frozen at commit \\texttt{${z.commit}}; test split, run once: multi-hop ALL@20 ${pct(mean(test?.['1']?.['all@20']))}, ANY@20 ${pct(mean(test?.['1']?.['any@20']))}, single-hop ALL@20 ${pct(mean(test?.['4']?.['all@20']))}} \\\\\n\\bottomrule\n\\end{tabular}\n`
  write('sweep.tex', body, 'dev split only (conversations 0–2); coordinate descent')
}

// ── LoCoMo-Conv: unreleased; the proxy sanity check
const units = run('conv-proxy-units-st-minilm-k10'), zen = run('conv-proxy-naive-rag-zenlm_zen-embedding-0.6b-k10'), mini = run('conv-proxy-naive-rag-all-minilm-k10')
if (units && mini) {
  const t = units.table, row = (name, key) => `${name} & ${pct(t[key + '·all']?.recall)} & ${pct(t[key + '·no-adversarial']?.recall)} & ${t[key + '·all']?.tokens?.toFixed(0)} \\\\`
  const body = `\\begin{tabular}{lrrr}\n\\toprule\nMemory unit, all-MiniLM-L6-v2, k=10 & R@10 all (1,977) & no adversarial (1,531) & tokens/q \\\\\n\\midrule\n${row('single turn', 'turn')}\n${row('2-turn exchange', 'w2')}\n${row('3-turn window', 'w3')}\n${row('5-turn window', 'w5')}\n\\midrule\nsingle turn, zen-embedding-0.6b & ${pct(zen?.table?.original?.recall)} & ${pct(zen?.table?.['original·no-adversarial']?.recall)} & ${zen?.table?.original?.tokens?.toFixed(0)} \\\\\n\\midrule\n\\multicolumn{4}{l}{paper's Naive RAG row: dialog ${units.paper_naive_rag.dialog}, implicit ${units.paper_naive_rag.implicit}, counterfactual ${units.paper_naive_rag.counterfactual}, composed ${units.paper_naive_rag.composed}} \\\\\n\\bottomrule\n\\end{tabular}\n`
  write('conv.tex', body, 'LoCoMo-Conv data is unreleased (github.com/MiuLab/LoCoMo-Conv answers 404); this is the paper\'s protocol on the original LoCoMo questions the rewrites came from')
}

// ── answers: one row per (reader, policy) with a summary block; p50 is the reader's own latency
const meta = (name) => { const p = new URL(`./runs/${name}/meta.json`, here); return existsSync(p) ? read(p) : {} }
const POLICY = { single: 'cosine @k', cer: 'first cut @k', context: 'engine @k', oracle: 'oracle gold' }
const ORDER = ['single', 'cer', 'context', 'oracle']
const answers = runs.filter((d) => /^locomo-(all|test|dev)-(single|cer|context|oracle)-k\d+-/.test(d)).map((d) => ({ d, m: run(d), meta: meta(d) })).filter((x) => x.m?.summary?.all?.f1)
if (answers.length) {
  answers.sort((a, b) => (a.meta.reader ?? '').localeCompare(b.meta.reader ?? '') || ORDER.indexOf(a.meta.policy) - ORDER.indexOf(b.meta.policy))
  const rows = answers.map(({ d, m, meta: t }) => { const s = m.summary.all; const cats = String(t.cats ?? ''); return `${POLICY[t.policy] ?? t.policy}${t.policy === 'oracle' ? '' : t.k ? `=${t.k}` : ''} & ${esc(t.reader ?? '')} & ${cats.replace(/,/g, '') === '1' ? 'multi-hop' : 'all four'} & ${s.n} & ${pct(s.f1.mean)} & ${pct(s.em.mean)} & ${pct(s.exact)} & ${pct(s.answered)} & ${s.tokens?.toFixed(0)} & ${(s.p50_ms / 1000).toFixed(1)} & [${pct(s.f1.lo)}, ${pct(s.f1.hi)}] \\\\` })
  write('locomo-answers.tex', `\\begin{tabular}{lllrrrrrrrr}\n\\toprule\nContext & Reader & Questions & n & F1 & EM & EXACT & ANSWERED & tokens/q & reader p50 s & 95\\% CI (F1) \\\\\n\\midrule\n${rows.join('\n')}\n\\bottomrule\n\\end{tabular}\n`, 'runs/locomo-*; EXACT = a gold turn in the context, ANSWERED = F1 ≥ 0.5 or exact; all ten conversations')
}
// ── MemoryAgentBench: one row per (configuration, reader) across sizes; dev (6k) and test merged into one line
// a run suffixed -v<n> is an earlier version kept for the record; the table carries the current one
const mab = runs.filter((d) => /^mab-(test|dev)-/.test(d) && !/-v\d+$/.test(d)).map((d) => run(d)).filter(Boolean)
if (mab.length) {
  const byKey = {}
  for (const m of mab) { const key = `${m.row}|${m.reader}`; const b = byKey[key] ??= { row: m.row, reader: m.reader, sizes: {} }; for (const [k, v] of Object.entries(m.by_size ?? {})) if (v.n >= 50) b.sizes[k] = v }
  const sizes = ['6k', '32k', '64k', '262k']; const cell = (b, k) => b.sizes[k] ? pct(b.sizes[k].substring_em) : '\\ldots'
  const pooled = (b, kind) => { const xs = sizes.map((z) => b.sizes[`${kind}_${z}`]).filter(Boolean); return xs.length === 4 ? pct(xs.reduce((a, v) => a + v.substring_em, 0) / 4) : '\\ldots' }
  const NAME = { noreader: 'resolver, latest wins', beam: 'typed search over the plans', beamx: 'typed search, exhaustive, lexical tie-break', beamr: 'typed search with one repair call' }
  const rows = Object.values(byKey).sort((a, b) => Object.keys(NAME).indexOf(a.row) - Object.keys(NAME).indexOf(b.row)).map((b) => `${esc(NAME[b.row] ?? b.row)} (${b.reader === 'none' ? 'no reader' : esc(b.reader)}) & ${sizes.map((z) => cell(b, 'sh_' + z)).join(' & ')} & ${pooled(b, 'sh')} & ${sizes.map((z) => cell(b, 'mh_' + z)).join(' & ')} & ${pooled(b, 'mh')} \\\\`)
  write('mab-fc.tex', `\\begin{tabular}{lrrrrrrrrrr}\n\\toprule\n & \\multicolumn{5}{c}{FC-SH} & \\multicolumn{5}{c}{FC-MH} \\\\\n\\cmidrule(lr){2-6}\\cmidrule(lr){7-11}\nConfiguration (reader) & 6k & 32k & 64k & 262k & pooled & 6k & 32k & 64k & 262k & pooled \\\\\n\\midrule\n${rows.join('\n')}\n\\midrule\n\\multicolumn{11}{l}{CAR (arXiv 2606.01435), pooled 6k--262k: 78.0 / 30.2 with gpt-4o-mini, 94.8 / 51.5 with gpt-4o; at 262k: 82 / 27 and 93 / 41} \\\\\n\\bottomrule\n\\end{tabular}\n`, 'runs/mab-*; substring exact match; 6k is the dev split, the rest test; pooled = mean of the four sizes as CAR reports')
}

// ── the code lane: RepoBench-R, both settings, test split, one row per configuration
{
  const codeDir = new URL('../code/runs/', here)
  const CODE_ROWS = ['dense-only', 'bm25-only', 'typed-links-only-no-model', 'dense-bm25', 'dense-typed-links', 'bm25-typed-links-no-model', 'full-dense-bm25-typed-links']
  const CODE_LABEL = { 'dense-only': 'dense only', 'bm25-only': 'BM25 only', 'typed-links-only-no-model': 'typed links only (no model)', 'dense-bm25': 'dense + BM25', 'dense-typed-links': 'dense + typed links', 'bm25-typed-links-no-model': 'BM25 + typed links (no model)', 'full-dense-bm25-typed-links': 'full: dense + BM25 + typed links' }
  const cell = (setting, split, r) => { const p = new URL(`../code/runs/repobench-r-${setting}-${split}-${r}/metrics.json`, here); if (!existsSync(p)) return null; const s = read(p).summary; return s }
  const rows = []
  for (const r of CODE_ROWS) { const a = cell('cff', 'test', r), b = cell('cfr', 'test', r); if (!a && !b) continue
    const c = (s, grp, k) => s ? pct(mean(s[grp]?.[k])) : '\\ldots'
    rows.push(`${CODE_LABEL[r]} & ${c(a, 'all', 'recall@1')} & ${c(a, 'all', 'recall@5')} & ${c(a, 'all', 'mrr')} & ${c(a, 'hard', 'recall@1')} & ${c(b, 'all', 'recall@1')} & ${c(b, 'all', 'recall@5')} & ${c(b, 'all', 'mrr')} & ${c(b, 'hard', 'recall@1')} \\\\`) }
  if (rows.length) write('code-repobench.tex', `\\begin{tabular}{lrrrrrrrr}\n\\toprule\n & \\multicolumn{4}{c}{cross-file-first (500)} & \\multicolumn{4}{c}{cross-file-random (500)} \\\\\n\\cmidrule(lr){2-5}\\cmidrule(lr){6-9}\nConfiguration & R@1 & R@5 & MRR & hard R@1 & R@1 & R@5 & MRR & hard R@1 \\\\\n\\midrule\n${rows.join('\n')}\n\\bottomrule\n\\end{tabular}\n`, 'RepoBench-R Python, test split (test_easy[0:250] + test_hard[0:250] per setting), all-MiniLM-L6-v2 for the dense generator, weights frozen on dev')
}
