// Code generated by zipdoc; DO NOT EDIT.

package nodes

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /v1/nodes", zip.Doc{
		Description: "Returns the caller org's currently connected bot nodes: what each one\ncalls itself, the platform it runs on, its agent version, when its socket was\nestablished, and the capabilities and commands it reported.\n\nOnly this org's nodes are listed — the org is half of every key in the table it\nreads — and only nodes attached to THIS replica, because the list is of live\nsockets rather than of registrations. The capability and command lists are the\nnode's own self-report: useful to show, never load-bearing, because what a node\nmay actually be asked to do is decided at the socket against the deployment's\nallowlist.",
		Fields: map[string]string{
			"nodeView.caps":        "Caps is the capability list the node reported. It is a self-report, useful\nto SHOW and never load-bearing: what a node may actually be asked to do is\ndecided at the socket by the deployment's allowlist.",
			"nodeView.commands":    "Commands is the command list the node reported. Same standing as Caps: a\nself-report, checked again at the socket before anything runs.",
			"nodeView.connectedAt": "ConnectedAt is when this node's socket was established, RFC3339 UTC.",
			"nodeView.displayName": "DisplayName is the human name the node reported for itself.",
			"nodeView.id":          "ID is the node's own identifier within the org — the value\nPOST /v1/nodes/{id}/invoke addresses it by.",
			"nodeView.platform":    "Platform is the operating system and architecture the node reported.",
			"nodeView.version":     "Version is the node agent's own version string.",
			"nodesView.nodes":      "Nodes is every node of the caller's org with a live socket to THIS replica,\nordered by id. A node connected to a different replica is not in it.",
		},
	})
}
