// Code generated by plane/gen; DO NOT EDIT.

// Package commerce is the typed client for the "commerce" app's internal ops.
//
// Every call here is a ZAP call BY NAME over the peer's unix socket — no URL, no
// env var, no HTTP round trip, and no way to reach the public edge by accident.
// That last one is not a style preference: commerce's own callers used to reach it
// through CLOUD_COMMERCE_HTTP_URL, which defaulted to the api.hanzo.ai edge —
// the SAME binary — so the forwarder re-entered itself and the billing gate died
// of it. A call by name cannot express that mistake.
//
// It depends on the CONTRACT (package plane) and never on commerce's implementation,
// so importing it costs a caller nothing but the types it is already sending.
package commerce

import (
	"context"

	"github.com/hanzoai/cloud/plane"
)

// App is the peer's name, which is also the socket it answers on. It is the
// ONE place this package spells it.
const App = "commerce"

// Ops is every op this peer answers, in the spelling the wire uses.
//
// It exists so a test can hold this generated surface against the LIVE plane
// registry and fail when they disagree — which is what lets this be generated
// from source without the document drifting away from the program. See
// plane_registry_test.go.
var Ops = []string{
	plane.FinanceAuthorize,
	plane.FinanceBalance,
	plane.FinanceCosts,
	plane.FinanceCredit,
	plane.FinanceRecord,
	plane.FinanceScopeRules,
	plane.FinanceSpend,
	plane.FinanceSubs,
	plane.FinanceTxns,
	plane.FinanceUsage,
	plane.StoreCurrent,
	plane.StoreListing,
}

// FinanceAuthorize authorize one prepaid spend.
//
// Calls plane.FinanceAuthorize on commerce over the peer plane.
func FinanceAuthorize(ctx context.Context, in *plane.AuthorizeIn) (*plane.Verdict, error) {
	return plane.Ask[plane.AuthorizeIn, plane.Verdict](ctx, App, plane.FinanceAuthorize, in)
}

// FinanceBalance spendable prepaid balance.
//
// Calls plane.FinanceBalance on commerce over the peer plane.
func FinanceBalance(ctx context.Context, in *plane.BalanceIn) (*plane.Balance, error) {
	return plane.Ask[plane.BalanceIn, plane.Balance](ctx, App, plane.FinanceBalance, in)
}

// FinanceCosts what we paid every vendor in a period.
//
// Calls plane.FinanceCosts on commerce over the peer plane.
func FinanceCosts(ctx context.Context, in *plane.CostsIn) (*plane.Costs, error) {
	return plane.Ask[plane.CostsIn, plane.Costs](ctx, App, plane.FinanceCosts, in)
}

// FinanceCredit credit one subject's prepaid ledger, exactly once per ref.
//
// Calls plane.FinanceCredit on commerce over the peer plane.
func FinanceCredit(ctx context.Context, in *plane.CreditIn) (*plane.Credited, error) {
	return plane.Ask[plane.CreditIn, plane.Credited](ctx, App, plane.FinanceCredit, in)
}

// FinanceRecord debit one metered act.
//
// Calls plane.FinanceRecord on commerce over the peer plane.
func FinanceRecord(ctx context.Context, in *plane.RecordIn) (*plane.Recorded, error) {
	return plane.Ask[plane.RecordIn, plane.Recorded](ctx, App, plane.FinanceRecord, in)
}

// FinanceScopeRules per-scope request-rate ceilings from this org's spend-alert rows.
//
// Calls plane.FinanceScopeRules on commerce over the peer plane.
func FinanceScopeRules(ctx context.Context) (*plane.ScopeRules, error) {
	return plane.Ask[struct{}, plane.ScopeRules](ctx, App, plane.FinanceScopeRules, &struct{}{})
}

// FinanceSpend metered consumption over a window, and the wallet behind it.
//
// Calls plane.FinanceSpend on commerce over the peer plane.
func FinanceSpend(ctx context.Context, in *plane.SpendIn) (*plane.Spend, error) {
	return plane.Ask[plane.SpendIn, plane.Spend](ctx, App, plane.FinanceSpend, in)
}

// FinanceSubs subscriptions for this org.
//
// Calls plane.FinanceSubs on commerce over the peer plane.
func FinanceSubs(ctx context.Context, in *plane.SubsIn) (*plane.Subs, error) {
	return plane.Ask[plane.SubsIn, plane.Subs](ctx, App, plane.FinanceSubs, in)
}

// FinanceTxns ledger entries for this org.
//
// Calls plane.FinanceTxns on commerce over the peer plane.
func FinanceTxns(ctx context.Context, in *plane.TxnsIn) (*plane.Txns, error) {
	return plane.Ask[plane.TxnsIn, plane.Txns](ctx, App, plane.FinanceTxns, in)
}

// FinanceUsage recorded debits for this org.
//
// Calls plane.FinanceUsage on commerce over the peer plane.
func FinanceUsage(ctx context.Context) (*plane.UsageRows, error) {
	return plane.Ask[struct{}, plane.UsageRows](ctx, App, plane.FinanceUsage, &struct{}{})
}

// StoreCurrent this org's storefront.
//
// Calls plane.StoreCurrent on commerce over the peer plane.
func StoreCurrent(ctx context.Context, in *plane.StoreIn) (*plane.Store, error) {
	return plane.Ask[plane.StoreIn, plane.Store](ctx, App, plane.StoreCurrent, in)
}

// StoreListing upsert one product listing.
//
// Calls plane.StoreListing on commerce over the peer plane.
func StoreListing(ctx context.Context, in *plane.ListingIn) (*plane.Listed, error) {
	return plane.Ask[plane.ListingIn, plane.Listed](ctx, App, plane.StoreListing, in)
}
