// Code generated by zipdoc; DO NOT EDIT.

package kv

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("github.com/hanzoai/cloud/apps/kv DELETE /v1/kv/:bucket", zip.Doc{
		Description: "Removes one bucket of the caller's org — every key and every\nrevision with it — and answers 204 with no body. 404 when the org has no\nbucket of that name.",
		Fields: map[string]string{
			"bucketRef.bucket": "Bucket is the bucket's name, from the path.",
		},
	})
	zip.Describe("github.com/hanzoai/cloud/apps/kv DELETE /v1/kv/:bucket/:key", zip.Doc{
		Description: "Delete removes one key — a delete marker in the key's history, so watchers\nsee it and Get answers 404 — and answers 204 with no body. 404 when the\nbucket does not exist.",
		Fields: map[string]string{
			"keyRef.bucket": "Bucket is the bucket, from the path.",
			"keyRef.key":    "Key is the key, from the path.",
		},
	})
	zip.Describe("github.com/hanzoai/cloud/apps/kv GET /v1/kv/:bucket/:key", zip.Doc{
		Description: "Get returns one key's current value and revision. 404 when the bucket does\nnot exist, the key was never written, or its latest revision is a delete.",
		Fields: map[string]string{
			"keyRef.bucket":     "Bucket is the bucket, from the path.",
			"keyRef.key":        "Key is the key, from the path.",
			"kvEntry.created":   "Created is when this revision was written, RFC3339.",
			"kvEntry.key":       "Key is the entry's key.",
			"kvEntry.operation": "Operation is what wrote the revision: put, del or purge.",
			"kvEntry.revision":  "Revision is the entry's revision in the bucket.",
			"kvEntry.value":     "Value is the value as UTF-8 text; empty for delete and purge markers.",
		},
	})
	zip.Describe("github.com/hanzoai/cloud/apps/kv GET /v1/kv/:bucket/:key/history", zip.Doc{
		Description: "History returns one key's retained revisions, oldest first — every put and\nevery delete marker up to the bucket's History depth. 404 when the bucket\ndoes not exist or the key was never written.",
		Fields: map[string]string{
			"keyRef.bucket":     "Bucket is the bucket, from the path.",
			"keyRef.key":        "Key is the key, from the path.",
			"kvEntry.created":   "Created is when this revision was written, RFC3339.",
			"kvEntry.key":       "Key is the entry's key.",
			"kvEntry.operation": "Operation is what wrote the revision: put, del or purge.",
			"kvEntry.revision":  "Revision is the entry's revision in the bucket.",
			"kvEntry.value":     "Value is the value as UTF-8 text; empty for delete and purge markers.",
			"kvPage.data":       "Data are the key's retained revisions.",
		},
	})
	zip.Describe("github.com/hanzoai/cloud/apps/kv POST /v1/kv/:bucket", zip.Doc{
		Description: "Creates a KV bucket and returns it. A bucket is keyed state on\nthe same durable plane as the streams: each key holds up to History\nrevisions, entries can expire by TTL, and watchers on the NATS port see every\nwrite. 409 when the org already has a bucket of that name.",
		Fields: map[string]string{
			"bucketRecord.bucket":  "Bucket is the bucket's name within the org.",
			"bucketRecord.history": "History is how many revisions each key keeps.",
			"bucketRecord.ttl":     "TTL is the entry expiry in seconds; 0 means none.",
			"bucketRecord.values":  "Values is how many values the bucket holds right now.",
			"bucketWrite.bucket":   "Bucket is the bucket's name within the org, from the path: 1–64 of\n[A-Za-z0-9_], no dash.",
			"bucketWrite.history":  "History is how many revisions each key keeps, 1–64. 0 means 1.",
			"bucketWrite.maxValue": "MaxValue caps one value's size in bytes. 0 or less means the server's\nceiling.",
			"bucketWrite.ttl":      "TTL expires entries after this many SECONDS. 0 means no expiry.",
		},
		Example: json.RawMessage(`{"history":5,"ttl":3600}`),
	})
	zip.Describe("github.com/hanzoai/cloud/apps/kv PUT /v1/kv/:bucket/:key", zip.Doc{
		Description: "Put sets one key to one value and returns the revision the write created.\nWrites are versioned: each put is a new revision and the bucket retains up to\nits History of them per key.",
		Fields: map[string]string{
			"kvAck.revision": "Revision is the revision the write created.",
			"kvWrite.bucket": "Bucket is the bucket, from the path.",
			"kvWrite.key":    "Key is the key, from the path.",
			"kvWrite.value":  "Value is the value, carried verbatim as UTF-8 text (typically JSON).",
		},
		Example: json.RawMessage(`{"value":"{\"theme\":\"dark\"}"}`),
	})
}
