// cd.go — what cd.hanzo.ai has DONE with the declarations.
//
// declare.go writes the desired state; this reads the reconciliation of it. They
// are different facts and the surface keeps them apart on purpose: "the file
// says v3" and "CD has applied commit abc and the workload is Healthy" answer
// different questions, and a board that blends them cannot report drift — which
// is the only thing a GitOps board is for.
//
// ── the object ──────────────────────────────────────────────────────────────
//
// A Hanzo CD Application is `apps.hanzo.ai/v1alpha1` (NOT argoproj.io — nothing
// has ever served that group here; a GVR naming it comes back "the server
// doesn't have a resource type", which a caller treating any error as absence
// reads as an empty plane). They are generated by the `fleet` ApplicationSet and
// live in its namespace, `hanzo-cd`. Reading exactly that namespace rather than
// the cluster is what lets the platform service hold a namespaced Role instead
// of a ClusterRole for this.
//
// ── the confinement, and its honest limit ───────────────────────────────────
//
// A CD Application's owner is its DESTINATION namespace — which, an org being
// its name, IS the org — and every Application object lives in hanzo-cd
// regardless of whose app it tracks. So unlike the fleet board, which confines
// at the SCAN before any CR is listed, this can only confine on the way out: the
// API list is unavoidably fleet-wide because the objects are not partitioned by
// owner. A non-super caller therefore never SEES another org's row, but the read
// that produced it was not itself narrowed.
// That is a property of CD's data model, not a choice here, and it is stated
// rather than hidden because the difference matters to anyone reasoning about
// what a compromised platform process could observe.
//
// ── SECOND READER, NAMED ────────────────────────────────────────────────────
//
// apps/deploy holds another projection of this same CR (observeGitOpsApp,
// serving GET /v1/deploy/gitops for a SuperAdmin, and the cd.hanzo.ai console's
// ArgoCD-shaped surface). Two projections of one CR is one more than there
// should be, and this file does not pretend otherwise: it reads a deliberately
// NARROWER set of fields — the ones a declaration board joins on — rather than
// re-deriving deploy's full ApplicationTree, so the overlap is the smallest it
// can be while the two apps remain separate processes. Consolidating them is a
// cross-app move (a plane op on deploy, or a leaf both import) and belongs in
// its own change with its own review.

package platform

import (
	"context"
	"net/http"
	"sort"
	"strings"

	"github.com/hanzoai/cloud"
	"github.com/hanzoai/cloud/apps/k8s"
	"github.com/hanzoai/namespace"
	"github.com/zap-proto/zip"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// cdNamespace is where the fleet ApplicationSet generates its Applications. It
// is the ApplicationSet's own namespace (universe
// infra/k8s/hanzo-cd/applicationset-fleet.yaml), and naming it here is what
// bounds the access this subsystem needs to one namespace.
const cdNamespace = "hanzo-cd"

// CDApp is one Application: what CD was told to reconcile, and what it did.
//
// Only the fields a declaration board joins on. The full ArgoCD projection —
// resource trees, sync windows, revision metadata — is the cd.hanzo.ai console's
// surface (/v1/deploy), and duplicating it here would be a second answer to a
// question that already has one.
type CDApp struct {
	// Name is the Application name the generator mints: <namespace>-<app>. It is
	// the join key against a Declaration.
	Name string `json:"name"`
	// Namespace is the DESTINATION namespace as the CR declares it — where the
	// workload lands. For a fleet Application that is the org, but this is the
	// OBSERVED field and not our model of it: the two can disagree, and a board
	// whose whole job is drift must be able to show that they do.
	Namespace string `json:"namespace"`
	// Project is the AppProject fence the sync is admitted under.
	Project string `json:"project"`
	// Path is the values file CD renders against, relative to the chart source.
	Path string `json:"path,omitempty"`

	// Sync is CD's verdict on git-versus-cluster: Synced, OutOfSync, or Unknown.
	Sync string `json:"sync"`
	// Revision is the universe commit CD last applied. Empty means it has not
	// applied one — never assume it means main.
	Revision string `json:"revision,omitempty"`
	// Health is the workload's verdict: Healthy, Progressing, Degraded, Missing.
	Health string `json:"health"`
	// Message is why, when Health is not Healthy.
	Message string `json:"message,omitempty"`
	// ReconciledAt is when CD last compared this Application.
	ReconciledAt string `json:"reconciledAt,omitempty"`

	// Automated is whether CD applies git without being asked. It is
	// cd.automated in the values file, rendered by the ApplicationSet's
	// templatePatch — false means the Application reports drift and nothing moves.
	Automated bool `json:"automated"`
	// SelfHeal is whether CD also corrects drift the cluster introduced.
	SelfHeal bool `json:"selfHeal"`

	// Phase is the last sync operation's phase (Running, Succeeded, Failed) and
	// OperationMessage is its message. A Failed phase with a Synced verdict is
	// the shape a stuck Application takes.
	Phase            string `json:"phase,omitempty"`
	OperationMessage string `json:"operationMessage,omitempty"`
}

// cdApps lists the Applications this caller may observe.
//
// An unreachable plane is 503 and NEVER an empty list. "CD has nothing" and "CD
// could not be asked" are opposite facts, and a board that renders them
// identically reports a healthy empty fleet during an outage — the exact lie
// fleetReady already refuses to tell for the workload board.
//
// A cluster with no CD installed is the one case that IS empty: an absent
// resource type means the plane is not there to have an opinion.
func cdApps(s *cloud.Service[fleetState], ctx context.Context, p fleetPrincipal) ([]CDApp, error) {
	if err := fleetReady(s); err != nil {
		return nil, err
	}
	list, err := s.State.dyn.Resource(k8s.CDApplications).Namespace(cdNamespace).List(ctx, metav1.ListOptions{})
	switch {
	case apierrors.IsNotFound(err):
		// The CRD is not served: Hanzo CD is not installed on this cluster. That
		// is an observation, so an empty plane is the honest answer.
		return []CDApp{}, nil
	case apierrors.IsForbidden(err):
		return nil, zip.Errorf(http.StatusServiceUnavailable,
			"platform cd: the platform service may not read %s in %s — grant it and this board answers",
			k8s.CDApplications.Resource, cdNamespace)
	case err != nil:
		s.Log.Error("cd list failed", "resource", k8s.CDApplications.Resource, "namespace", cdNamespace, "err", err)
		return nil, zip.Errorf(http.StatusBadGateway, "platform cd: could not read the delivery plane")
	}

	out := make([]CDApp, 0, len(list.Items))
	for i := range list.Items {
		a := observeCDApp(&list.Items[i])
		if !p.Super && !owns(a.Namespace, p.org) {
			continue
		}
		out = append(out, a)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

// observeCDApp projects one Application CR. Every read is total: a field the CR
// does not carry yields the zero value, never a panic and never a guess. An
// Application CD has never reconciled has no status at all, and that is exactly
// what an empty Sync/Health reports.
func observeCDApp(cr *unstructured.Unstructured) CDApp {
	obj := cr.Object
	a := CDApp{
		Name:      cr.GetName(),
		Namespace: nested(obj, "spec", "destination", "namespace"),
		Project:   nested(obj, "spec", "project"),

		Sync:         nested(obj, "status", "sync", "status"),
		Revision:     nested(obj, "status", "sync", "revision"),
		Health:       nested(obj, "status", "health", "status"),
		Message:      nested(obj, "status", "health", "message"),
		ReconciledAt: nested(obj, "status", "reconciledAt"),

		Phase:            nested(obj, "status", "operationState", "phase"),
		OperationMessage: nested(obj, "status", "operationState", "message"),
	}
	// The values file, as the generator wrote it into the Helm source. It is the
	// link back to a Declaration for anyone reading one Application on its own.
	if files, ok, _ := unstructured.NestedStringSlice(obj, "spec", "source", "helm", "valueFiles"); ok && len(files) > 0 {
		a.Path = strings.TrimPrefix(nested(obj, "spec", "source", "path")+"/"+files[0], "/")
	}
	// automated is a BLOCK, not a boolean: its presence is the switch. selfHeal
	// is a field inside it and is read only when the block is there, so an
	// Application with no automation never reports selfHeal true.
	if auto, ok, _ := unstructured.NestedMap(obj, "spec", "syncPolicy", "automated"); ok {
		a.Automated = true
		if v, found := auto["selfHeal"].(bool); found {
			a.SelfHeal = v
		}
	}
	return a
}

// owns is the confinement rule: an org's Applications are the ones landing in
// the namespace that IS its name, and a reserved namespace is never any
// customer's however its org is spelled.
//
// ★ BOTH SIDES ARE CANONICALISED, and that is the whole of this function.
// A namespace is namespace.Sanitize(org) — that is how the write path built it —
// while p.org is the RAW `owner` claim. Comparing the two directly applies the
// slugger to ONE side of an authorization test, and an asymmetric compare is a
// collision waiting to be named: for org "Acme" the directory is
// "acme-<hash>", so the raw claim never matches its OWN rows, and any org whose
// raw name IS the literal string "acme-<hash>" matches them instead. The slugger
// is public code, so that value is offline-computable by anyone. Red proved it
// end to end (red_fence_poc_test.go); apps/platform/runner.go's own ownedBy
// comment warns about exactly this class.
//
// Sanitize is INJECTIVE, so canonicalising both sides is not merely symmetric,
// it is collision-free: two distinct orgs never share a slug, therefore never
// share a namespace, therefore never read each other.
func owns(ns, org string) bool {
	slug := namespace.Sanitize(org)
	return slug != "" && ns == slug && !reserved(ns)
}

// nested reads a string at a path, or "" if any segment is absent or not a
// string. One helper, so no caller of this file writes its own three-value
// unwrap and forgets the `ok`.
func nested(obj map[string]any, fields ...string) string {
	v, ok, err := unstructured.NestedString(obj, fields...)
	if !ok || err != nil {
		return ""
	}
	return v
}
