// Code generated by zipdoc; DO NOT EDIT.

package marketing

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("DELETE /v1/marketing/audiences/:id", zip.Doc{
		Description: "deleteAudience removes one of the caller org's audiences and answers 204. It\ndeletes the saved filter only — no customer, event or enrollment is touched.",
		Fields: map[string]string{
			"AudienceRef.id": "ID is the audience id from the path, as returned by create.",
		},
		Example: json.RawMessage(`{"id":"aud_4c1e9b7a2d6f0538e4a7c9b1d3f5027a"}`),
	})
	zip.Describe("DELETE /v1/marketing/calendar/:id", zip.Doc{
		Description: "deleteCalendarPost removes one of the caller org's posts and answers 204. A\npost already published is deleted from the calendar only — nothing is\nretracted from the network it went out on.",
		Fields: map[string]string{
			"PostRef.id": "ID is the post id from the path, as returned by create.",
		},
		Example: json.RawMessage(`{"id":"cal_1d7f3b9e5a2c8046f1b3d5a7c9e02468"}`),
	})
	zip.Describe("DELETE /v1/marketing/campaigns/:id", zip.Doc{
		Description: "deleteCampaign removes one of the caller org's campaigns and answers 204. A\ncampaign belonging to another org reads as not found and is left untouched.",
		Fields: map[string]string{
			"CampaignRef.id": "ID is the campaign id from the path, as returned by create.",
		},
		Example: json.RawMessage(`{"id":"camp_9f2a1c7d4e8b0a6f3d2c5b1e7a9f4c60"}`),
	})
	zip.Describe("DELETE /v1/marketing/suppressions", zip.Doc{
		Description: "removeSuppression re-subscribes an address on one channel and answers 204. An\naddress that is not on the list reads as not found.",
		Fields: map[string]string{
			"Suppression.address":   "Address is the recipient, normalized (lower-cased, trimmed) so an opt-out\ncannot be slipped past on a case or whitespace difference. Required.",
			"Suppression.channel":   "Channel is the surface opted out of: email, sms, social, meta, google or\ntiktok. Empty means email. Opting out of one leaves the others reachable.",
			"Suppression.createdAt": "CreatedAt is unix seconds, server-assigned.",
			"Suppression.reason":    "Reason is a free-text note, capped at 1024 bytes. The public one-click\nendpoint records \"one-click unsubscribe\".",
		},
		Example: json.RawMessage(`{"channel":"email","address":"person@example.com"}`),
	})
	zip.Describe("GET /v1/marketing/audiences", zip.Doc{
		Description: "listAudiences returns the org's saved audiences, most recently updated first.",
		Fields: map[string]string{
			"Audience.createdAt":  "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"Audience.event":      "Event is the analytics event a member must have fired. EMPTY MEANS NO\nFILTER: the audience is then every mailable customer in the org, and no\nwarehouse is consulted.",
			"Audience.id":         "ID is the server-assigned audience id (\"aud_\" + 128 random bits).",
			"Audience.name":       "Name is the audience's label. Required, trimmed, capped at 1024 bytes.",
			"Audience.windowDays": "WindowDays is how far back the event counts, ending now. 0 means 30 and\nnothing above 3650 is honoured. Ignored when Event is empty.",
			"AudienceList.data":   "Data is the page; an empty array when the org has saved no audience.",
			"Page.limit":          "Limit caps the rows returned; 0 means 200 and nothing above 1000 is honoured.",
		},
		Example: json.RawMessage(`{"limit":50}`),
	})
	zip.Describe("GET /v1/marketing/audiences/:id", zip.Doc{
		Description: "getAudience returns one of the caller org's saved audiences. An audience\nbelonging to another org reads as not found.",
		Fields: map[string]string{
			"Audience.createdAt":  "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"Audience.event":      "Event is the analytics event a member must have fired. EMPTY MEANS NO\nFILTER: the audience is then every mailable customer in the org, and no\nwarehouse is consulted.",
			"Audience.id":         "ID is the server-assigned audience id (\"aud_\" + 128 random bits).",
			"Audience.name":       "Name is the audience's label. Required, trimmed, capped at 1024 bytes.",
			"Audience.windowDays": "WindowDays is how far back the event counts, ending now. 0 means 30 and\nnothing above 3650 is honoured. Ignored when Event is empty.",
			"AudienceRef.id":      "ID is the audience id from the path, as returned by create.",
		},
		Example: json.RawMessage(`{"id":"aud_4c1e9b7a2d6f0538e4a7c9b1d3f5027a"}`),
	})
	zip.Describe("GET /v1/marketing/audiences/:id/preview", zip.Doc{
		Description: "previewAudience evaluates the cohort LIVE — the same resolution an enrollment\nwould run — and reports how big it is and how many real mailboxes it reaches.\nIt is the honest answer to \"is this send worth making\": a cohort of 500 that\nmails 3 says so, in deliverable and unmatched. Nothing is sent.",
		Fields: map[string]string{
			"AudiencePreview.available":   "Available is false when the roster or the warehouse could not be read; the\ncounts are then zero because nothing was measured, not because the cohort\nis empty, and Reason says which read failed.",
			"AudiencePreview.count":       "Count is the cohort size: distinct warehouse identifiers for an event\naudience, mailable customers for an event-less (whole-org) one.",
			"AudiencePreview.deliverable": "Deliverable is how many de-duplicated addresses a send would reach, and\nUnmatched how many cohort identifiers named no customer. Unmatched is\nreported rather than hidden: it is the honest explanation for a cohort of\n500 that mails 3.",
			"AudiencePreview.sample":      "Sample is up to 1000 cohort IDENTIFIERS — never addresses, which product\nanalytics does not hold. Empty for an event-less (whole-org) audience.",
			"AudiencePreview.source":      "Source names where the cohort was read: the events table for an event\naudience, \"iam:<org>\" for the whole-org one.",
			"AudienceRef.id":              "ID is the audience id from the path, as returned by create.",
		},
		Example:  json.RawMessage(`{"id":"aud_4c1e9b7a2d6f0538e4a7c9b1d3f5027a"}`),
		Response: json.RawMessage(`{"available":true,"count":500,"deliverable":3,"unmatched":497,"sample":["u_1","u_2"],"source":"hanzo.events"}`),
	})
	zip.Describe("GET /v1/marketing/calendar", zip.Doc{
		Description: "listCalendarPosts returns the org's calendar, soonest scheduled first,\noptionally narrowed to one status.",
		Fields: map[string]string{
			"CalendarPost.body":        "Body is the post text. Required.",
			"CalendarPost.channel":     "Channel is the target network: x, facebook, instagram, linkedin, tiktok,\nyoutube or threads. Required — a post must name where it goes.",
			"CalendarPost.createdAt":   "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"CalendarPost.error":       "Error is the exact reason the last publish attempt failed — the honest\nrecord behind a \"failed\" status, never a faked success.",
			"CalendarPost.id":          "ID is the server-assigned post id (\"cal_\" + 128 random bits).",
			"CalendarPost.publishedAt": "PublishedAt is when the publish succeeded; 0 until it does.",
			"CalendarPost.scheduledAt": "ScheduledAt is the unix publish time; 0 leaves the post a draft, and any\nvalue makes it \"scheduled\" for the durable sweep to pick up.",
			"CalendarPost.status":      "Status is draft, scheduled, published, failed or canceled. Server-owned.",
			"CalendarPost.title":       "Title is the post's internal label, capped at 1024 bytes.",
			"PostQuery.limit":          "Limit caps the rows returned; 0 means 200 and nothing above 1000 is honoured.",
			"PostQuery.status":         "Status keeps only posts in that state (draft, scheduled, published,\nfailed, canceled). Empty means every post.",
		},
		Example: json.RawMessage(`{"status":"scheduled","limit":50}`),
	})
	zip.Describe("GET /v1/marketing/calendar/:id", zip.Doc{
		Description: "getCalendarPost returns one of the caller org's posts, including the exact\nerror behind a failed publish. A post belonging to another org reads as not\nfound.",
		Fields: map[string]string{
			"CalendarPost.body":        "Body is the post text. Required.",
			"CalendarPost.channel":     "Channel is the target network: x, facebook, instagram, linkedin, tiktok,\nyoutube or threads. Required — a post must name where it goes.",
			"CalendarPost.createdAt":   "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"CalendarPost.error":       "Error is the exact reason the last publish attempt failed — the honest\nrecord behind a \"failed\" status, never a faked success.",
			"CalendarPost.id":          "ID is the server-assigned post id (\"cal_\" + 128 random bits).",
			"CalendarPost.publishedAt": "PublishedAt is when the publish succeeded; 0 until it does.",
			"CalendarPost.scheduledAt": "ScheduledAt is the unix publish time; 0 leaves the post a draft, and any\nvalue makes it \"scheduled\" for the durable sweep to pick up.",
			"CalendarPost.status":      "Status is draft, scheduled, published, failed or canceled. Server-owned.",
			"CalendarPost.title":       "Title is the post's internal label, capped at 1024 bytes.",
			"PostRef.id":               "ID is the post id from the path, as returned by create.",
		},
		Example: json.RawMessage(`{"id":"cal_1d7f3b9e5a2c8046f1b3d5a7c9e02468"}`),
	})
	zip.Describe("GET /v1/marketing/campaigns", zip.Doc{
		Description: "listCampaigns returns the org's campaigns, most recently updated first,\noptionally narrowed to one lifecycle status.",
		Fields: map[string]string{
			"Campaign.budget":      "Budget and Spend are minor units (USD cents), clamped to >= 0.",
			"Campaign.channel":     "Channel is the delivery surface: email, sms, social, meta, google or\ntiktok. Empty means email.",
			"Campaign.createdAt":   "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"Campaign.id":          "ID is the server-assigned campaign id (\"camp_\" + 128 random bits).",
			"Campaign.name":        "Name is the campaign's label. Required, trimmed, capped at 1024 bytes.",
			"Campaign.objective":   "Objective is the free-text goal (\"signups\"), capped at 1024 bytes.",
			"Campaign.scheduledAt": "ScheduledAt is the unix send time; 0 means unscheduled. Setting it on a\ncampaign with no explicit status makes that status \"scheduled\".",
			"Campaign.status":      "Status is the lifecycle: draft, scheduled, active, paused or completed.\nEmpty means draft.",
			"CampaignList.data":    "Data is the page; an empty array when the org has no matching campaign.",
			"CampaignQuery.limit":  "Limit caps the rows returned; 0 means 200 and nothing above 1000 is honoured.",
			"CampaignQuery.status": "Status keeps only campaigns in that lifecycle state (draft, scheduled,\nactive, paused, completed). Empty means every campaign.",
		},
		Example: json.RawMessage(`{"status":"active","limit":25}`),
	})
	zip.Describe("GET /v1/marketing/campaigns/:id", zip.Doc{
		Description: "getCampaign returns one of the caller org's campaigns. A campaign belonging to\nanother org reads as not found.",
		Fields: map[string]string{
			"Campaign.budget":      "Budget and Spend are minor units (USD cents), clamped to >= 0.",
			"Campaign.channel":     "Channel is the delivery surface: email, sms, social, meta, google or\ntiktok. Empty means email.",
			"Campaign.createdAt":   "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"Campaign.id":          "ID is the server-assigned campaign id (\"camp_\" + 128 random bits).",
			"Campaign.name":        "Name is the campaign's label. Required, trimmed, capped at 1024 bytes.",
			"Campaign.objective":   "Objective is the free-text goal (\"signups\"), capped at 1024 bytes.",
			"Campaign.scheduledAt": "ScheduledAt is the unix send time; 0 means unscheduled. Setting it on a\ncampaign with no explicit status makes that status \"scheduled\".",
			"Campaign.status":      "Status is the lifecycle: draft, scheduled, active, paused or completed.\nEmpty means draft.",
			"CampaignRef.id":       "ID is the campaign id from the path, as returned by create.",
		},
		Example: json.RawMessage(`{"id":"camp_9f2a1c7d4e8b0a6f3d2c5b1e7a9f4c60"}`),
	})
	zip.Describe("GET /v1/marketing/promos", zip.Doc{
		Description: "listPromos returns every promo the deployment offers with its live counters:\nhow many orgs have redeemed it and how many redemptions remain under the cap.\nThe promos are fleet-wide, not per-org — only the counters move.",
		Fields: map[string]string{
			"Promo.active":         "Active is false for a promo that is no longer offered; an inactive promo\nquotes as ineligible and refuses to redeem.",
			"Promo.code":           "Code is the promo id, e.g. \"first1000\".",
			"Promo.createdAt":      "CreatedAt is unix seconds.",
			"Promo.description":    "Description is the human-readable offer.",
			"Promo.maxRedemptions": "MaxRedemptions is the hard fleet-wide cap; the redemption past it is\ndeclined.",
			"Promo.percentOff":     "PercentOff is the discount applied to ONE month's list price.",
			"Promo.plans":          "Plans is the csv of eligible plan ids (\"pro,max,team\").",
			"Promo.teamSeatCap":    "TeamSeatCap is how many Team seats bill at the promo rate; seats beyond it\nbill at list.",
			"PromoStatus.redeemed": "Redeemed is how many orgs have taken it, Remaining how many are left under\nthe fleet-wide cap.",
		},
		Response: json.RawMessage(`{"data":[{"promo":{"code":"first1000","percentOff":90,"maxRedemptions":1000,"active":true},"redeemed":137,"remaining":863}]}`),
	})
	zip.Describe("GET /v1/marketing/promos/:code/eligibility", zip.Doc{
		Description: "quotePromo prices a promo against a plan and seat count. It is PURE: nothing\nis redeemed, credited or counted, so it is safe to call from a pricing page on\nevery keystroke. An inactive promo or an exhausted cap quotes ineligible with\nthe reason rather than erroring.",
		Fields: map[string]string{
			"Quote.code":       "Code, Plan and Seats echo what was quoted.",
			"Quote.eligible":   "Eligible says whether a redeem would be accepted right now; Reason says\nwhy not when it would not.",
			"Quote.listCents":  "ListCents is the undiscounted month price, ChargeCents what would be\ncharged, DiscountCents the difference — all in USD cents.",
			"Quote.remaining":  "Remaining is how many redemptions are left under the fleet-wide cap.",
			"QuoteQuery.code":  "Code is the promo code from the path.",
			"QuoteQuery.plan":  "Plan is the plan being priced: pro, max or team. Anything else (including\nthe free Developer plan) has no list price and so nothing to discount.",
			"QuoteQuery.seats": "Seats is the Team seat count; 0 means 1, and it is ignored for the\nsingle-seat plans.",
		},
		Example:  json.RawMessage(`{"code":"first1000","plan":"team","seats":12}`),
		Response: json.RawMessage(`{"code":"first1000","plan":"team","seats":12,"eligible":true,"listCents":19900,"chargeCents":418900,"discountCents":179100,"remaining":863}`),
	})
	zip.Describe("GET /v1/marketing/promos/:code/redemption", zip.Doc{
		Description: "getRedemption returns the caller org's OWN redemption of a promo — an\norg-scoped read, so it can never surface another tenant's. Not found when this\norg has not redeemed it.",
		Fields: map[string]string{
			"PromoRef.code":            "Code is the promo code from the path, e.g. \"first1000\".",
			"Redemption.code":          "Code is the promo redeemed.",
			"Redemption.creditCents":   "CreditCents is the discount value credited to the org's wallet — the promo\nis realized as a NON-CASH credit, not a subscription coupon.",
			"Redemption.creditEntryId": "CreditEntryID is the finance ledger entry that credit landed in.",
			"Redemption.plan":          "Plan and Seats are what was redeemed against.",
			"Redemption.redeemedAt":    "RedeemedAt is unix seconds.",
		},
		Example: json.RawMessage(`{"code":"first1000"}`),
	})
	zip.Describe("GET /v1/marketing/sequences", zip.Doc{
		Description: "listSequences returns the org's drip sequences, most recently updated first.",
		Fields: map[string]string{
			"Page.limit":         "Limit caps the rows returned; 0 means 200 and nothing above 1000 is honoured.",
			"Sequence.createdAt": "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"Sequence.id":        "ID is the server-assigned sequence id (\"seq_\" + 128 random bits).",
			"Sequence.name":      "Name is the sequence's label. Required, trimmed, capped at 1024 bytes.",
			"Sequence.status":    "Status is the lifecycle: draft, active or archived. Empty means draft, and\nONLY an active sequence accepts enrollments.",
			"SequenceList.data":  "Data is the page; an empty array when the org has no sequence.",
		},
		Example: json.RawMessage(`{"limit":50}`),
	})
	zip.Describe("GET /v1/marketing/sequences/:id", zip.Doc{
		Description: "getSequence returns one of the caller org's sequences together with its steps\nin send order. A sequence belonging to another org reads as not found.",
		Fields: map[string]string{
			"Sequence.createdAt": "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"Sequence.id":        "ID is the server-assigned sequence id (\"seq_\" + 128 random bits).",
			"Sequence.name":      "Name is the sequence's label. Required, trimmed, capped at 1024 bytes.",
			"Sequence.status":    "Status is the lifecycle: draft, active or archived. Empty means draft, and\nONLY an active sequence accepts enrollments.",
			"SequenceRef.id":     "ID is the sequence id from the path, as returned by create.",
			"SequenceView.steps": "Steps are in send order (idx ascending); empty for a sequence with no\nmessages yet, which enrolls fine and completes immediately.",
			"Step.body":          "Body is the message text. Required. The signed one-click unsubscribe link\nis appended to it at send time.",
			"Step.createdAt":     "CreatedAt is unix seconds, server-assigned.",
			"Step.delaySeconds":  "DelaySeconds is how long after the previous step this one sends (after\nenrollment, for step 0).",
			"Step.id":            "ID is the server-assigned step id (\"step_\" + 128 random bits).",
			"Step.idx":           "Idx is the step's 0-based position, assigned by appending: a new step\nalways lands after the last one.",
			"Step.sequenceId":    "SequenceID is the sequence this step belongs to.",
			"Step.subject":       "Subject is the email subject line, capped at 1024 bytes.",
		},
		Example: json.RawMessage(`{"id":"seq_7b3e5a1c9d024f68b0a3e7c5d9f1a248"}`),
	})
	zip.Describe("GET /v1/marketing/sequences/:id/enrollments", zip.Doc{
		Description: "listEnrollments returns who is walking one sequence, most recently enrolled\nfirst, with each walk's current step and next due time.",
		Fields: map[string]string{
			"Enrollment.address":     "Address is the normalized (lower-cased, trimmed) recipient.",
			"Enrollment.channel":     "Channel is the delivery surface the steps go out on.",
			"Enrollment.currentStep": "CurrentStep is the index of the step that sends next.",
			"Enrollment.enrolledAt":  "EnrolledAt and UpdatedAt are unix seconds.",
			"Enrollment.id":          "ID is the server-assigned enrollment id (\"enr_\" + 128 random bits).",
			"Enrollment.nextRunAt":   "NextRunAt is the unix time the current step comes due; 0 once the walk has\nended. It IS the schedule — durable in SQLite, so it survives restarts.",
			"Enrollment.sequenceId":  "SequenceID is the sequence being walked.",
			"Enrollment.status":      "Status is active, completed or canceled.",
			"EnrollmentQuery.id":     "ID is the sequence id from the path.",
			"EnrollmentQuery.limit":  "Limit caps the rows returned; 0 means 200 and nothing above 1000 is honoured.",
		},
		Example: json.RawMessage(`{"id":"seq_7b3e5a1c9d024f68b0a3e7c5d9f1a248","limit":100}`),
	})
	zip.Describe("GET /v1/marketing/sequences/:id/steps", zip.Doc{
		Description: "listSteps returns one sequence's steps in send order.",
		Fields: map[string]string{
			"SequenceRef.id":    "ID is the sequence id from the path, as returned by create.",
			"Step.body":         "Body is the message text. Required. The signed one-click unsubscribe link\nis appended to it at send time.",
			"Step.createdAt":    "CreatedAt is unix seconds, server-assigned.",
			"Step.delaySeconds": "DelaySeconds is how long after the previous step this one sends (after\nenrollment, for step 0).",
			"Step.id":           "ID is the server-assigned step id (\"step_\" + 128 random bits).",
			"Step.idx":          "Idx is the step's 0-based position, assigned by appending: a new step\nalways lands after the last one.",
			"Step.sequenceId":   "SequenceID is the sequence this step belongs to.",
			"Step.subject":      "Subject is the email subject line, capped at 1024 bytes.",
		},
		Example: json.RawMessage(`{"id":"seq_7b3e5a1c9d024f68b0a3e7c5d9f1a248"}`),
	})
	zip.Describe("GET /v1/marketing/summary", zip.Doc{
		Description: "summary rolls up the caller org's campaigns: how many there are, how many are\nactive, and the summed budget and spend in cents.",
		Fields: map[string]string{
			"Summary.budget":    "Budget and Spend are the summed campaign budget and spend, in cents.",
			"Summary.campaigns": "Campaigns is how many campaigns the org has, Active how many are running.",
		},
		Response: json.RawMessage(`{"campaigns":12,"active":3,"budget":500000,"spend":128400}`),
	})
	zip.Describe("GET /v1/marketing/suppressions", zip.Doc{
		Description: "listSuppressions returns the org's opt-out list, newest first — everyone the\nsend gate will refuse to deliver to.",
		Fields: map[string]string{
			"Page.limit":            "Limit caps the rows returned; 0 means 200 and nothing above 1000 is honoured.",
			"Suppression.address":   "Address is the recipient, normalized (lower-cased, trimmed) so an opt-out\ncannot be slipped past on a case or whitespace difference. Required.",
			"Suppression.channel":   "Channel is the surface opted out of: email, sms, social, meta, google or\ntiktok. Empty means email. Opting out of one leaves the others reachable.",
			"Suppression.createdAt": "CreatedAt is unix seconds, server-assigned.",
			"Suppression.reason":    "Reason is a free-text note, capped at 1024 bytes. The public one-click\nendpoint records \"one-click unsubscribe\".",
		},
		Example: json.RawMessage(`{"limit":100}`),
	})
	zip.Describe("GET /v1/marketing/unsubscribe", zip.Doc{
		Description: "unsubscribe is the PUBLIC one-click endpoint (no principal): a recipient\nclicks the signed link in an email footer. The token binds (org, channel,\naddress), so a caller can only opt OUT exactly the tuple it was minted for —\nnever another address and never another org. An invalid token is refused, and\na deployment with no KMS-sealed key refuses rather than accepting anything.",
		Fields: map[string]string{
			"UnsubscribeInput.address": "Address is the recipient to opt out.",
			"UnsubscribeInput.channel": "Channel is the surface to opt out of.",
			"UnsubscribeInput.org":     "Org is the org the link was minted for.",
			"UnsubscribeInput.token":   "Token is the HMAC over (org, channel, address). It is the ONLY authority\nhere — there is no principal — so it binds the request to one tuple and\nnothing else.",
		},
		Example:  json.RawMessage(`{"org":"acme","channel":"email","address":"person@example.com","token":"9f2a…"}`),
		Response: json.RawMessage(`{"unsubscribed":true,"address":"person@example.com","channel":"email"}`),
	})
	zip.Describe("POST /v1/marketing/audiences", zip.Doc{
		Description: "createAudience saves a cohort filter for the caller's org. Name is required.\nOmitting event saves the WHOLE-ORG audience — every mailable customer — which\nneeds no analytics warehouse; naming one narrows that roster to the customers\nwho fired it within windowDays.",
		Fields: map[string]string{
			"Audience.createdAt":  "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"Audience.event":      "Event is the analytics event a member must have fired. EMPTY MEANS NO\nFILTER: the audience is then every mailable customer in the org, and no\nwarehouse is consulted.",
			"Audience.id":         "ID is the server-assigned audience id (\"aud_\" + 128 random bits).",
			"Audience.name":       "Name is the audience's label. Required, trimmed, capped at 1024 bytes.",
			"Audience.windowDays": "WindowDays is how far back the event counts, ending now. 0 means 30 and\nnothing above 3650 is honoured. Ignored when Event is empty.",
		},
		Example: json.RawMessage(`{"name":"Model users, last 30d","event":"model.invoked","windowDays":30}`),
	})
	zip.Describe("POST /v1/marketing/calendar", zip.Doc{
		Description: "createCalendarPost adds a post to the content calendar. Channel and body are\nrequired. A scheduledAt in the future makes the post \"scheduled\" and the\ndurable sweep publishes it when it comes due — claimed once, so a post\npublishes at most once; without one it stays a draft.",
		Fields: map[string]string{
			"CalendarPost.body":        "Body is the post text. Required.",
			"CalendarPost.channel":     "Channel is the target network: x, facebook, instagram, linkedin, tiktok,\nyoutube or threads. Required — a post must name where it goes.",
			"CalendarPost.createdAt":   "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"CalendarPost.error":       "Error is the exact reason the last publish attempt failed — the honest\nrecord behind a \"failed\" status, never a faked success.",
			"CalendarPost.id":          "ID is the server-assigned post id (\"cal_\" + 128 random bits).",
			"CalendarPost.publishedAt": "PublishedAt is when the publish succeeded; 0 until it does.",
			"CalendarPost.scheduledAt": "ScheduledAt is the unix publish time; 0 leaves the post a draft, and any\nvalue makes it \"scheduled\" for the durable sweep to pick up.",
			"CalendarPost.status":      "Status is draft, scheduled, published, failed or canceled. Server-owned.",
			"CalendarPost.title":       "Title is the post's internal label, capped at 1024 bytes.",
		},
		Example: json.RawMessage(`{"title":"Launch day","body":"Hanzo Cloud is live.","channel":"x","scheduledAt":1780000000}`),
	})
	zip.Describe("POST /v1/marketing/calendar/:id/publish", zip.Doc{
		Description: "publishCalendarPost publishes a post NOW, synchronously, whatever its\nschedule. No social connector is wired today, so every channel answers an\nhonest 501 naming the seam a real one would plug into, and the post is\nrecorded failed with that exact reason — never a faked \"published\".",
		Fields: map[string]string{
			"CalendarPost.body":        "Body is the post text. Required.",
			"CalendarPost.channel":     "Channel is the target network: x, facebook, instagram, linkedin, tiktok,\nyoutube or threads. Required — a post must name where it goes.",
			"CalendarPost.createdAt":   "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"CalendarPost.error":       "Error is the exact reason the last publish attempt failed — the honest\nrecord behind a \"failed\" status, never a faked success.",
			"CalendarPost.id":          "ID is the server-assigned post id (\"cal_\" + 128 random bits).",
			"CalendarPost.publishedAt": "PublishedAt is when the publish succeeded; 0 until it does.",
			"CalendarPost.scheduledAt": "ScheduledAt is the unix publish time; 0 leaves the post a draft, and any\nvalue makes it \"scheduled\" for the durable sweep to pick up.",
			"CalendarPost.status":      "Status is draft, scheduled, published, failed or canceled. Server-owned.",
			"CalendarPost.title":       "Title is the post's internal label, capped at 1024 bytes.",
			"PostRef.id":               "ID is the post id from the path, as returned by create.",
		},
		Example: json.RawMessage(`{"id":"cal_1d7f3b9e5a2c8046f1b3d5a7c9e02468"}`),
	})
	zip.Describe("POST /v1/marketing/campaigns", zip.Doc{
		Description: "createCampaign registers a campaign in the caller's org. Name is required;\nchannel defaults to email and status to draft, and a future scheduledAt with\nno explicit status makes the campaign \"scheduled\". Budget and spend are cents\nand are clamped to >= 0. The id, createdAt and updatedAt of the input are\nignored — the server assigns them.",
		Fields: map[string]string{
			"Campaign.budget":      "Budget and Spend are minor units (USD cents), clamped to >= 0.",
			"Campaign.channel":     "Channel is the delivery surface: email, sms, social, meta, google or\ntiktok. Empty means email.",
			"Campaign.createdAt":   "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"Campaign.id":          "ID is the server-assigned campaign id (\"camp_\" + 128 random bits).",
			"Campaign.name":        "Name is the campaign's label. Required, trimmed, capped at 1024 bytes.",
			"Campaign.objective":   "Objective is the free-text goal (\"signups\"), capped at 1024 bytes.",
			"Campaign.scheduledAt": "ScheduledAt is the unix send time; 0 means unscheduled. Setting it on a\ncampaign with no explicit status makes that status \"scheduled\".",
			"Campaign.status":      "Status is the lifecycle: draft, scheduled, active, paused or completed.\nEmpty means draft.",
		},
		Example: json.RawMessage(`{"name":"Spring Launch","channel":"meta","objective":"signups","budget":50000,"scheduledAt":1780000000}`),
	})
	zip.Describe("POST /v1/marketing/campaigns/:id/schedule", zip.Doc{
		Description: "scheduleCampaign sets a campaign's send time and moves it to \"scheduled\". A\nscheduledAt of 0 clears the schedule and returns it to \"draft\".",
		Fields: map[string]string{
			"Campaign.budget":           "Budget and Spend are minor units (USD cents), clamped to >= 0.",
			"Campaign.channel":          "Channel is the delivery surface: email, sms, social, meta, google or\ntiktok. Empty means email.",
			"Campaign.createdAt":        "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"Campaign.id":               "ID is the server-assigned campaign id (\"camp_\" + 128 random bits).",
			"Campaign.name":             "Name is the campaign's label. Required, trimmed, capped at 1024 bytes.",
			"Campaign.objective":        "Objective is the free-text goal (\"signups\"), capped at 1024 bytes.",
			"Campaign.scheduledAt":      "ScheduledAt is the unix send time; 0 means unscheduled. Setting it on a\ncampaign with no explicit status makes that status \"scheduled\".",
			"Campaign.status":           "Status is the lifecycle: draft, scheduled, active, paused or completed.\nEmpty means draft.",
			"ScheduleInput.id":          "ID is the campaign id from the path.",
			"ScheduleInput.scheduledAt": "ScheduledAt is the unix send time. 0 clears the schedule.",
		},
		Example: json.RawMessage(`{"id":"camp_9f2a1c7d4e8b0a6f3d2c5b1e7a9f4c60","scheduledAt":1780000000}`),
	})
	zip.Describe("POST /v1/marketing/promos/:code/redeem", zip.Doc{
		Description: "redeemPromo redeems the promo for the caller's org, crediting the discount\nvalue to its wallet through the finance ledger. Three guards run under one\nlock so the cap cannot be raced past: the fleet-wide redemption cap, one\nredemption per org, and one per payment instrument.\n\nIt is IDEMPOTENT: an org that already redeemed gets its original redemption\nback with alreadyRedeemed true and is not credited twice.",
		Fields: map[string]string{
			"RedeemInput.code":             "Code is the promo code from the path.",
			"RedeemInput.instrument":       "Instrument identifies the payment method. It is the anti-farming key: one\nredemption per instrument, fleet-wide.",
			"RedeemInput.plan":             "Plan is the plan being redeemed against: pro, max or team.",
			"RedeemInput.seats":            "Seats is the Team seat count; 0 means 1. Seats beyond the promo's\nteamSeatCap bill at list.",
			"RedeemResult.alreadyRedeemed": "AlreadyRedeemed is true when this org had already taken the promo and the\ncall was an idempotent replay — nothing was credited a second time.",
			"RedeemResult.chargeCents":     "ChargeCents is what month one costs after the discount, DiscountCents the\ncredit that produced it.",
			"Redemption.code":              "Code is the promo redeemed.",
			"Redemption.creditCents":       "CreditCents is the discount value credited to the org's wallet — the promo\nis realized as a NON-CASH credit, not a subscription coupon.",
			"Redemption.creditEntryId":     "CreditEntryID is the finance ledger entry that credit landed in.",
			"Redemption.plan":              "Plan and Seats are what was redeemed against.",
			"Redemption.redeemedAt":        "RedeemedAt is unix seconds.",
		},
		Example: json.RawMessage(`{"code":"first1000","plan":"pro","seats":1,"instrument":"pm_1QxYz2AbCdEf"}`),
	})
	zip.Describe("POST /v1/marketing/sequences", zip.Doc{
		Description: "createSequence registers a drip sequence in the caller's org. Name is\nrequired; status defaults to draft, and a sequence must be ACTIVE before it\nwill accept enrollments. The id, createdAt and updatedAt of the input are\nignored — the server assigns them.",
		Fields: map[string]string{
			"Sequence.createdAt": "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"Sequence.id":        "ID is the server-assigned sequence id (\"seq_\" + 128 random bits).",
			"Sequence.name":      "Name is the sequence's label. Required, trimmed, capped at 1024 bytes.",
			"Sequence.status":    "Status is the lifecycle: draft, active or archived. Empty means draft, and\nONLY an active sequence accepts enrollments.",
		},
		Example: json.RawMessage(`{"name":"Trial onboarding","status":"draft"}`),
	})
	zip.Describe("POST /v1/marketing/sequences/:id/enroll", zip.Doc{
		Description: "enroll adds one contact or a whole audience to a sequence and schedules the\nfirst step for each. The sequence must be ACTIVE (a draft sends nothing), and\nthe request must name exactly one of address or audienceId.\n\nEnrolling is ALL this does: the message itself is sent later by the drip\nengine, through the suppression gate, so an opted-out customer can be enrolled\nhere and still never be mailed. Re-posting is safe — an address this sequence\nalready took is counted in alreadyEnrolled and never double-dripped — which is\nwhat makes retrying a partially-applied announcement a resume rather than a\nsecond send.",
		Fields: map[string]string{
			"EnrollInput.address":          "Address is a single recipient, normalized (lower-cased, trimmed) before\nuse. Give this OR audienceId, never both and never neither.",
			"EnrollInput.audienceId":       "AudienceID fans the sequence out over a saved audience, resolved live to\nthe org's mailable customers. Email only.",
			"EnrollInput.channel":          "Channel is the delivery surface; empty means email. An audience resolves\nmailboxes, so an audience enroll must be email.",
			"EnrollInput.id":               "ID is the sequence id from the path.",
			"EnrollResult.alreadyEnrolled": "AlreadyEnrolled is how many this sequence had already taken and were left\nalone.",
			"EnrollResult.enrolled":        "Enrolled is how many started a walk on this call.",
			"EnrollResult.enrollmentId":    "EnrollmentID names the walk, and is present ONLY for a single-address\nenroll — a fan-out has many, and reporting one of them would be a lie.",
			"EnrollResult.resolved":        "Resolved is how many addresses the request named — 1 for an address, the\naudience's deliverable count for an audience.",
		},
		Example:  json.RawMessage(`{"audienceId":"aud_4c1e9b7a2d6f0538e4a7c9b1d3f5027a","channel":"email"}`),
		Response: json.RawMessage(`{"resolved":412,"enrolled":409,"alreadyEnrolled":3}`),
	})
	zip.Describe("POST /v1/marketing/sequences/:id/enrollments/:eid/cancel", zip.Doc{
		Description: "cancelEnrollment stops one walk mid-sequence and answers 204: no further step\nis sent, and steps already delivered are not recalled. Only an ACTIVE\nenrollment can be canceled — one already completed or canceled reads as not\nfound.",
		Fields: map[string]string{
			"EnrollmentRef.eid": "EID is the enrollment id from the path, as returned by a single-address\nenroll.",
			"EnrollmentRef.id":  "ID is the sequence id from the path.",
		},
		Example: json.RawMessage(`{"id":"seq_7b3e5a1c9d024f68b0a3e7c5d9f1a248","eid":"enr_2a8d6f0b4c1e9375a0d2f6b8c4e19f73"}`),
	})
	zip.Describe("POST /v1/marketing/sequences/:id/status", zip.Doc{
		Description: "setSequenceStatus flips draft/active/archived — the activation gate for\nsending, since only an active sequence accepts enrollments. It does not touch\nenrollments already walking: archiving stops new ones, not in-flight ones.",
		Fields: map[string]string{
			"SequenceStatus.id":     "ID is the sequence id from the path.",
			"SequenceStatus.status": "Status is draft, active or archived. Required; there is no default here,\nunlike on create. Only an active sequence accepts enrollments.",
		},
		Example: json.RawMessage(`{"id":"seq_7b3e5a1c9d024f68b0a3e7c5d9f1a248","status":"active"}`),
	})
	zip.Describe("POST /v1/marketing/sequences/:id/steps", zip.Doc{
		Description: "addStep appends a message to the END of a sequence: the new step's idx is one\npast the last, so steps arrive in the order they are added. Body is required\nand delaySeconds must be >= 0. Adding a step does not disturb enrollments\nalready walking — one that has passed this index simply never sees it.",
		Fields: map[string]string{
			"Step.body":              "Body is the message text. Required. The signed one-click unsubscribe link\nis appended to it at send time.",
			"Step.createdAt":         "CreatedAt is unix seconds, server-assigned.",
			"Step.delaySeconds":      "DelaySeconds is how long after the previous step this one sends (after\nenrollment, for step 0).",
			"Step.id":                "ID is the server-assigned step id (\"step_\" + 128 random bits).",
			"Step.idx":               "Idx is the step's 0-based position, assigned by appending: a new step\nalways lands after the last one.",
			"Step.sequenceId":        "SequenceID is the sequence this step belongs to.",
			"Step.subject":           "Subject is the email subject line, capped at 1024 bytes.",
			"StepInput.body":         "Body is the message text. Required.",
			"StepInput.delaySeconds": "DelaySeconds is how long after the previous step this one sends (after\nenrollment, for the first step). Must be >= 0.",
			"StepInput.id":           "SequenceID is the sequence id from the path (the route's :id).",
			"StepInput.subject":      "Subject is the email subject line, capped at 1024 bytes.",
		},
		Example: json.RawMessage(`{"delaySeconds":86400,"subject":"Day 1: your first model call","body":"Here is how to make your first request…"}`),
	})
	zip.Describe("POST /v1/marketing/suppressions", zip.Doc{
		Description: "addSuppression records an opt-out for the org (admin / self-service\nmanagement). Address is required; channel defaults to email. It is idempotent:\nre-suppressing the same tuple keeps the original record rather than erroring.\nFrom here on the ONE send gate refuses that recipient on that channel.",
		Fields: map[string]string{
			"Suppression.address":   "Address is the recipient, normalized (lower-cased, trimmed) so an opt-out\ncannot be slipped past on a case or whitespace difference. Required.",
			"Suppression.channel":   "Channel is the surface opted out of: email, sms, social, meta, google or\ntiktok. Empty means email. Opting out of one leaves the others reachable.",
			"Suppression.createdAt": "CreatedAt is unix seconds, server-assigned.",
			"Suppression.reason":    "Reason is a free-text note, capped at 1024 bytes. The public one-click\nendpoint records \"one-click unsubscribe\".",
		},
		Example: json.RawMessage(`{"channel":"email","address":"person@example.com","reason":"asked support to stop"}`),
	})
	zip.Describe("PUT /v1/marketing/calendar/:id", zip.Doc{
		Description: "updateCalendarPost replaces a post's editable fields. It is a full write, not\na patch, and it RESETS the lifecycle from the schedule: a scheduledAt makes\nthe post \"scheduled\" again and none makes it a draft — so editing a failed\npost requeues it rather than leaving it stuck.",
		Fields: map[string]string{
			"CalendarPost.body":        "Body is the post text. Required.",
			"CalendarPost.channel":     "Channel is the target network: x, facebook, instagram, linkedin, tiktok,\nyoutube or threads. Required — a post must name where it goes.",
			"CalendarPost.createdAt":   "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"CalendarPost.error":       "Error is the exact reason the last publish attempt failed — the honest\nrecord behind a \"failed\" status, never a faked success.",
			"CalendarPost.id":          "ID is the server-assigned post id (\"cal_\" + 128 random bits).",
			"CalendarPost.publishedAt": "PublishedAt is when the publish succeeded; 0 until it does.",
			"CalendarPost.scheduledAt": "ScheduledAt is the unix publish time; 0 leaves the post a draft, and any\nvalue makes it \"scheduled\" for the durable sweep to pick up.",
			"CalendarPost.status":      "Status is draft, scheduled, published, failed or canceled. Server-owned.",
			"CalendarPost.title":       "Title is the post's internal label, capped at 1024 bytes.",
		},
		Example: json.RawMessage(`{"title":"Launch day","body":"Hanzo Cloud is live — try it free.","channel":"x","scheduledAt":1780003600}`),
	})
	zip.Describe("PUT /v1/marketing/campaigns/:id", zip.Doc{
		Description: "updateCampaign replaces a campaign's editable fields. It is a full write, not\na patch: every field takes the value in the body, and an omitted one is\ncleared. The id comes from the path — the body cannot retarget another\ncampaign — and createdAt is never rewritten.",
		Fields: map[string]string{
			"Campaign.budget":      "Budget and Spend are minor units (USD cents), clamped to >= 0.",
			"Campaign.channel":     "Channel is the delivery surface: email, sms, social, meta, google or\ntiktok. Empty means email.",
			"Campaign.createdAt":   "CreatedAt and UpdatedAt are unix seconds, both server-assigned.",
			"Campaign.id":          "ID is the server-assigned campaign id (\"camp_\" + 128 random bits).",
			"Campaign.name":        "Name is the campaign's label. Required, trimmed, capped at 1024 bytes.",
			"Campaign.objective":   "Objective is the free-text goal (\"signups\"), capped at 1024 bytes.",
			"Campaign.scheduledAt": "ScheduledAt is the unix send time; 0 means unscheduled. Setting it on a\ncampaign with no explicit status makes that status \"scheduled\".",
			"Campaign.status":      "Status is the lifecycle: draft, scheduled, active, paused or completed.\nEmpty means draft.",
		},
		Example: json.RawMessage(`{"name":"Spring Launch","channel":"meta","status":"active","objective":"signups","budget":50000,"spend":12500}`),
	})
}
