// Code generated by plane/gen; DO NOT EDIT.

// Package iam is the typed client for the "iam" app's internal ops.
//
// Every call here is a ZAP call BY NAME over the peer's unix socket — no URL, no
// env var, no HTTP round trip, and no way to reach the public edge by accident.
// That last one is not a style preference: iam's own callers used to reach it
// through CLOUD_COMMERCE_HTTP_URL, which defaulted to the api.hanzo.ai edge —
// the SAME binary — so the forwarder re-entered itself and the billing gate died
// of it. A call by name cannot express that mistake.
//
// It depends on the CONTRACT (package plane) and never on iam's implementation,
// so importing it costs a caller nothing but the types it is already sending.
package iam

import (
	"context"

	"github.com/hanzoai/cloud/plane"
)

// App is the peer's name, which is also the socket it answers on. It is the
// ONE place this package spells it.
const App = "iam"

// Ops is every op this peer answers, in the spelling the wire uses.
//
// It exists so a test can hold this generated surface against the LIVE plane
// registry and fail when they disagree — which is what lets this be generated
// from source without the document drifting away from the program. See
// plane_registry_test.go.
var Ops = []string{
	plane.IAMApproval,
	plane.IAMEmail,
	plane.IAMGrant,
	plane.IAMMailable,
	plane.IAMMembers,
	plane.IAMProjects,
	plane.IAMRoles,
	plane.IAMSeats,
}

// IAMApproval whether the caller is off the waitlist.
//
// Calls plane.IAMApproval on iam over the peer plane.
func IAMApproval(ctx context.Context) (*plane.Approval, error) {
	return plane.Ask[struct{}, plane.Approval](ctx, App, plane.IAMApproval, &struct{}{})
}

// IAMEmail the caller's address, and whether they have proved it.
//
// Calls plane.IAMEmail on iam over the peer plane.
func IAMEmail(ctx context.Context) (*plane.Email, error) {
	return plane.Ask[struct{}, plane.Email](ctx, App, plane.IAMEmail, &struct{}{})
}

// IAMGrant record that a user may act in a scope of the caller's org.
//
// Calls plane.IAMGrant on iam over the peer plane.
func IAMGrant(ctx context.Context, in *plane.GrantIn) (*struct{}, error) {
	return plane.Ask[plane.GrantIn, struct{}](ctx, App, plane.IAMGrant, in)
}

// IAMMailable who this org may mail.
//
// Calls plane.IAMMailable on iam over the peer plane.
func IAMMailable(ctx context.Context) (*plane.Roster, error) {
	return plane.Ask[struct{}, plane.Roster](ctx, App, plane.IAMMailable, &struct{}{})
}

// IAMMembers who may act in one scope of the caller's org.
//
// Calls plane.IAMMembers on iam over the peer plane.
func IAMMembers(ctx context.Context, in *plane.Scope) (*plane.Memberships, error) {
	return plane.Ask[plane.Scope, plane.Memberships](ctx, App, plane.IAMMembers, in)
}

// IAMProjects projects this org owns.
//
// Calls plane.IAMProjects on iam over the peer plane.
func IAMProjects(ctx context.Context) (*plane.Projects, error) {
	return plane.Ask[struct{}, plane.Projects](ctx, App, plane.IAMProjects, &struct{}{})
}

// IAMRoles the caller's role names in their own org.
//
// Calls plane.IAMRoles on iam over the peer plane.
func IAMRoles(ctx context.Context) (*plane.Roles, error) {
	return plane.Ask[struct{}, plane.Roles](ctx, App, plane.IAMRoles, &struct{}{})
}

// IAMSeats the caller's org's billable people.
//
// Calls plane.IAMSeats on iam over the peer plane.
func IAMSeats(ctx context.Context) (*plane.Seats, error) {
	return plane.Ask[struct{}, plane.Seats](ctx, App, plane.IAMSeats, &struct{}{})
}
