// Code generated by zipdoc; DO NOT EDIT.

package catalog

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /v1/catalog", zip.Doc{
		Description: "Browse searches AND browses the cross-org catalog: every project, app and site\nthe fleet has built, whichever org built it.\n\nIt reads TWO corpora and returns them as one page — the published,\nworld-readable catalog that every caller sees, plus the caller's OWN org's\nprivate entries when the request carries a validated principal. Each row says\nwhich it came from in `scope`, so a client can warn before sharing a link. An\nanonymous caller simply gets the published one; no filter can ever widen a\ncaller into another tenant's corpus, because the query that would return it is\nnever run for them.\n\nA request with no q is a browse rather than a search, and both answer the same\nshape: the page, the total before paging, and the facet counts over the whole\nmatching set.",
		Fields: map[string]string{
			"Entry.archetype":       "Archetype is WHAT KIND OF THING this is, from a closed and ordered list —\nmodel | contract | chain | sdk | template | infra | site | app — derived from\nthe repository's own topics, name and description, first match winning, and\nalways `site` for a deployed site. It is DERIVED, never guessed by a model,\nbecause a wrong archetype hides a row from the browse rail more thoroughly\nthan a missing one does. Empty when no topic matched: unclassified, not\nuncategorisable.",
			"Entry.description":     "Description is the repository's own one-line GitHub description, carried\nverbatim. It comes from the SOURCE half of a row, so a site that was never\nmatched to a repository has none, and nothing here is written by us.",
			"Entry.forkable":        "Forkable is NOT omitempty: false is an answer here, not a missing field.\nOmitted, a client could not tell \"you cannot fork this\" from \"nobody said\".",
			"Entry.id":              "ID is \"<org>/<name>\" and is the corpus's primary key: a re-published entry\nupdates in place under it rather than accumulating duplicates, so it is the\none handle stable enough to link to or to name in a `template` filter. Two\norgs can spell the same id, and `canonical` picks which one keeps it.",
			"Entry.kind":            "repo | site",
			"Entry.language":        "Language is the repository's primary implementation language as GitHub\ncomputes it (\"Go\", \"TypeScript\"), and the case is GitHub's. Empty for a site\nwith no source half and for a repository GitHub could not classify.",
			"Entry.license":         "License is the terms that upstream work carries, in whichever form the half\nthat credited it had: an SPDX id (\"MIT\", \"Apache-2.0\") on a GitHub fork,\nfree text on a site whose publisher declared it. GitHub's NOASSERTION — \"we\ncould not identify it\" — reads as none rather than as a licence by that name.\nSo empty means UNDECLARED and never unencumbered, and Upstream is what says\nwhether the question applies at all.",
			"Entry.name":            "Name is the short identifier inside the org — the repository's name, or the\nsite's slug — and is the half of ID after the slash. Not a display name;\nTitle is.",
			"Entry.note":            "Note is why a row is NOT in the published catalog, set by the admission gate\n(gate.go) on the sites it holds back. It is the difference between a demo\nthat silently vanished from the public lens and one whose owner can read the\nreason and fix it. A published row never carries one.",
			"Entry.org":             "hanzo | lux | zoo",
			"Entry.origin":          "Origin is WHAT THIS IS TO YOU: template | community | third-party | product\n(origin.go owns the four nouns and derives them). Not omitempty, for the\nsame reason Forkable is not: every row has an answer, and a missing one is\nexactly the flattening this field exists to end.",
			"Entry.repo":            "source",
			"Entry.scope":           "Scope is provenance, not storage: \"public\" for a row from the published\ncorpus, \"org\" for one only this caller can see. A UI that cannot tell them\napart cannot warn before sharing a link.",
			"Entry.stars":           "Stars is GitHub's stargazer count for the source repository, read at the last\nsync and never accumulated here. It is not a ranking — the page sorts on\nUpdated — but it is the tiebreak when two orgs claim one ID. Absent for a\nsite with no repository behind it, and for a repository nobody has starred.",
			"Entry.template":        "lineage, if forked from one",
			"Entry.title":           "Title is what to SHOW. A site's human name wins where it has one; a repo row\nfalls back to the repository name, so on a repo this usually just repeats\nName. Absent only for a site whose project was never named — render Name.",
			"Entry.updated":         "Updated is when the thing last MOVED, as RFC 3339 in UTC: a repository's last\npush, or a site's last deploy. The page is ordered on it, most recent first,\nby comparing these strings — so the format is load-bearing and not cosmetic.\nAbsent means the source reported no timestamp, and such a row sorts last.",
			"Entry.upstream":        "Upstream/License credit the third-party work an entry was published from:\nthe difference between \"this org built it\" and \"somebody else built it and\nwe are showing it to you\".\n\nWHO built it is Org, above — the account that paid for the project. There\nwas once a separate admin-gated `official` boolean here claiming the same\nthing, and because it was gated it disagreed: apps Hanzo wrote and hosts\nwere published by a script holding an ordinary org token, so it stayed\nfalse on all of them and this directory filed our own work as somebody\nelse's. A field that restates an unforgeable fact can only ever be the\nwrong copy of it.",
			"Entry.url":             "live, if it is deployed",
			"browseQuery.archetype": "Archetype narrows to one project archetype. Case-insensitive.",
			"browseQuery.forkable":  "Forkable is tri-state: \"true\" selects the forkable rows, \"false\" selects the\nrest, and anything else — including absent — applies no filter at all.",
			"browseQuery.kind":      "Kind narrows to repo | site. Case-insensitive.",
			"browseQuery.language":  "Language narrows to one implementation language. Case-insensitive.",
			"browseQuery.limit":     "Limit caps the page at 200, default 50. A value that is not a non-negative\ninteger falls back to the default.",
			"browseQuery.offset":    "Offset is where the page starts, default 0, with the same tolerance.",
			"browseQuery.org":       "Org narrows to one builder org: hanzo | lux | zoo. Case-insensitive.",
			"browseQuery.origin":    "Origin narrows to what a row IS to you: template | community | third-party |\nproduct. This is the axis the two hanzo.app lanes are cut on.",
			"browseQuery.q":         "Q is the free-text query the lexical index scores relevance on. Empty is a\nbrowse rather than a search — the same request either way.",
			"browseQuery.template":  "Template narrows a lane to ONE lineage: the id of the parent everything\nreturned was forked from.",
			"catalogPage.data":      "Data is the page of matching entries, most recently updated first.",
			"catalogPage.facets":    "Facets counts the whole matching set along every browse axis, so a rail a\nclient renders is a rail that has results behind it. Keyed axis → value → count.",
			"catalogPage.total":     "Total is how many entries matched BEFORE paging — what a pager sizes itself on.",
		},
		Example: json.RawMessage(`{"origin":"template","language":"typescript","forkable":"true","limit":"20"}`),
	})
}
