// Code generated by client/gen; DO NOT EDIT.

// Package commerce is the typed client for the "commerce" app's internal ops.
//
// Every call here is a ZAP call BY NAME over the peer's unix socket — no URL, no
// env var, no HTTP round trip, and no way to reach the public edge by accident.
// That last one is not a style preference: commerce's own callers used to reach it
// through CLOUD_COMMERCE_HTTP_URL, which defaulted to the api.hanzo.ai edge —
// the SAME binary — so the forwarder re-entered itself and the billing gate died
// of it. A call by name cannot express that mistake.
//
// It depends on the CONTRACT (package client) and never on commerce's implementation,
// so importing it costs a caller nothing but the types it is already sending.
package commerce

import (
	"context"

	"github.com/hanzoai/cloud/client"
)

// App is the peer's name, which is also the socket it answers on. It is the
// ONE place this package spells it.
const App = "commerce"

// Ops is every op this peer answers, in the spelling the wire uses.
//
// It exists so a test can hold this generated surface against the LIVE plane
// registry and fail when they disagree — which is what lets this be generated
// from source without the document drifting away from the program. See
// plane_registry_test.go.
var Ops = []string{
	client.BillingAccountMembers,
	client.BillingAccounts,
	client.BillingAlertAmend,
	client.BillingAlertDrop,
	client.BillingAlertRaise,
	client.BillingAlerts,
	client.BillingAutoRecharge,
	client.BillingAutoRechargeSet,
	client.BillingCapAuthorize,
	client.BillingCreditBalance,
	client.BillingCreditBreakdown,
	client.BillingCredits,
	client.BillingCryptoDeposit,
	client.BillingCryptoMint,
	client.BillingCryptoOptions,
	client.BillingInvoiceCollect,
	client.BillingInvoiceIssue,
	client.BillingInvoicePDF,
	client.BillingInvoiceRaise,
	client.BillingInvoiceRead,
	client.BillingInvoiceVoid,
	client.BillingInvoices,
	client.BillingMethodDetach,
	client.BillingMethodSave,
	client.BillingMethods,
	client.BillingMode,
	client.BillingPayouts,
	client.BillingPlans,
	client.BillingRate,
	client.BillingRecharge,
	client.BillingRollup,
	client.BillingSettings,
	client.BillingSubscribe,
	client.BillingSubscriptionCancel,
	client.BillingSubscriptionReactivate,
	client.BillingSubscriptions,
	client.BillingTier,
	client.BillingTopup,
	client.BillingTopupCard,
	client.BillingTransaction,
	client.BillingTransactions,
	client.BillingWire,
	client.CatalogRefresh,
	client.FinanceAuthorize,
	client.FinanceBalance,
	client.FinanceCosts,
	client.FinanceCredit,
	client.FinanceRecord,
	client.FinanceScopeRules,
	client.FinanceSpend,
	client.FinanceSubs,
	client.FinanceTxns,
	client.FinanceUsage,
	client.StoreCurrent,
	client.StoreListing,
}

// BillingAccountMembers the roster of one billing account.
//
// Calls client.BillingAccountMembers on commerce over the peer plane.
func BillingAccountMembers(ctx context.Context, in *client.HoldersIn) (*client.Holders, error) {
	return client.Call[client.HoldersIn, client.Holders](ctx, App, client.BillingAccountMembers, in)
}

// BillingAccounts the caller's billing accounts.
//
// Calls client.BillingAccounts on commerce over the peer plane.
func BillingAccounts(ctx context.Context, in *client.CallerIn) (*client.Accounts, error) {
	return client.Call[client.CallerIn, client.Accounts](ctx, App, client.BillingAccounts, in)
}

// BillingAlertAmend change one spend cap.
//
// Calls client.BillingAlertAmend on commerce over the peer plane.
func BillingAlertAmend(ctx context.Context, in *client.AlertPatch) (*client.Alert, error) {
	return client.Call[client.AlertPatch, client.Alert](ctx, App, client.BillingAlertAmend, in)
}

// BillingAlertDrop remove one spend cap.
//
// Calls client.BillingAlertDrop on commerce over the peer plane.
func BillingAlertDrop(ctx context.Context, in *client.AlertRef) (*client.Dropped, error) {
	return client.Call[client.AlertRef, client.Dropped](ctx, App, client.BillingAlertDrop, in)
}

// BillingAlertRaise open a spend cap.
//
// Calls client.BillingAlertRaise on commerce over the peer plane.
func BillingAlertRaise(ctx context.Context, in *client.AlertSpec) (*client.Alert, error) {
	return client.Call[client.AlertSpec, client.Alert](ctx, App, client.BillingAlertRaise, in)
}

// BillingAlerts this org's spend caps.
//
// Calls client.BillingAlerts on commerce over the peer plane.
func BillingAlerts(ctx context.Context, in *client.SubjectIn) (*client.Alerts, error) {
	return client.Call[client.SubjectIn, client.Alerts](ctx, App, client.BillingAlerts, in)
}

// BillingAutoRecharge this org's auto-reload rule.
//
// Calls client.BillingAutoRecharge on commerce over the peer plane.
func BillingAutoRecharge(ctx context.Context) (*client.AutoRecharge, error) {
	return client.Call[struct{}, client.AutoRecharge](ctx, App, client.BillingAutoRecharge, &struct{}{})
}

// BillingAutoRechargeSet set this org's auto-reload rule.
//
// Calls client.BillingAutoRechargeSet on commerce over the peer plane.
func BillingAutoRechargeSet(ctx context.Context, in *client.AutoRechargeEdit) (*client.AutoRecharge, error) {
	return client.Call[client.AutoRechargeEdit, client.AutoRecharge](ctx, App, client.BillingAutoRechargeSet, in)
}

// BillingCapAuthorize whether one proposed spend fits inside this org's caps.
//
// Calls client.BillingCapAuthorize on commerce over the peer plane.
func BillingCapAuthorize(ctx context.Context, in *client.CapIn) (*client.CapVerdict, error) {
	return client.Call[client.CapIn, client.CapVerdict](ctx, App, client.BillingCapAuthorize, in)
}

// BillingCreditBalance spendable credit, per currency.
//
// Calls client.BillingCreditBalance on commerce over the peer plane.
func BillingCreditBalance(ctx context.Context, in *client.SubjectIn) (*client.CreditBalance, error) {
	return client.Call[client.SubjectIn, client.CreditBalance](ctx, App, client.BillingCreditBalance, in)
}

// BillingCreditBreakdown spendable credit, split by grant tag.
//
// Calls client.BillingCreditBreakdown on commerce over the peer plane.
func BillingCreditBreakdown(ctx context.Context, in *client.SubjectIn) (*client.CreditBreakdown, error) {
	return client.Call[client.SubjectIn, client.CreditBreakdown](ctx, App, client.BillingCreditBreakdown, in)
}

// BillingCredits a subject's credit grants.
//
// Calls client.BillingCredits on commerce over the peer plane.
func BillingCredits(ctx context.Context, in *client.SubjectIn) (*client.CreditGrants, error) {
	return client.Call[client.SubjectIn, client.CreditGrants](ctx, App, client.BillingCredits, in)
}

// BillingCryptoDeposit read one deposit intent back.
//
// Calls client.BillingCryptoDeposit on commerce over the peer plane.
func BillingCryptoDeposit(ctx context.Context, in *client.CryptoDepositIn) (*client.CryptoDeposit, error) {
	return client.Call[client.CryptoDepositIn, client.CryptoDeposit](ctx, App, client.BillingCryptoDeposit, in)
}

// BillingCryptoMint issue a deposit address for one payer and asset.
//
// Calls client.BillingCryptoMint on commerce over the peer plane.
func BillingCryptoMint(ctx context.Context, in *client.CryptoMintIn) (*client.CryptoDeposit, error) {
	return client.Call[client.CryptoMintIn, client.CryptoDeposit](ctx, App, client.BillingCryptoMint, in)
}

// BillingCryptoOptions chains and tokens the crypto rail accepts.
//
// Calls client.BillingCryptoOptions on commerce over the peer plane.
func BillingCryptoOptions(ctx context.Context) (*client.CryptoOptions, error) {
	return client.Call[struct{}, client.CryptoOptions](ctx, App, client.BillingCryptoOptions, &struct{}{})
}

// BillingInvoiceCollect collect an issued invoice from credits, balance, then card.
//
// Calls client.BillingInvoiceCollect on commerce over the peer plane.
func BillingInvoiceCollect(ctx context.Context, in *client.InvoiceRef) (*client.Collected, error) {
	return client.Call[client.InvoiceRef, client.Collected](ctx, App, client.BillingInvoiceCollect, in)
}

// BillingInvoiceIssue issue a draft invoice, making it collectible.
//
// Calls client.BillingInvoiceIssue on commerce over the peer plane.
func BillingInvoiceIssue(ctx context.Context, in *client.InvoiceRef) (*client.Invoice, error) {
	return client.Call[client.InvoiceRef, client.Invoice](ctx, App, client.BillingInvoiceIssue, in)
}

// BillingInvoicePDF render one invoice as a PDF.
//
// Calls client.BillingInvoicePDF on commerce over the peer plane.
func BillingInvoicePDF(ctx context.Context, in *client.InvoiceRef) (*client.Document, error) {
	return client.Call[client.InvoiceRef, client.Document](ctx, App, client.BillingInvoicePDF, in)
}

// BillingInvoiceRaise raise a draft invoice against a customer.
//
// Calls client.BillingInvoiceRaise on commerce over the peer plane.
func BillingInvoiceRaise(ctx context.Context, in *client.RaiseIn) (*client.Invoice, error) {
	return client.Call[client.RaiseIn, client.Invoice](ctx, App, client.BillingInvoiceRaise, in)
}

// BillingInvoiceRead read one invoice.
//
// Calls client.BillingInvoiceRead on commerce over the peer plane.
func BillingInvoiceRead(ctx context.Context, in *client.InvoiceRef) (*client.Invoice, error) {
	return client.Call[client.InvoiceRef, client.Invoice](ctx, App, client.BillingInvoiceRead, in)
}

// BillingInvoiceVoid void a draft or issued invoice.
//
// Calls client.BillingInvoiceVoid on commerce over the peer plane.
func BillingInvoiceVoid(ctx context.Context, in *client.InvoiceRef) (*client.Invoice, error) {
	return client.Call[client.InvoiceRef, client.Invoice](ctx, App, client.BillingInvoiceVoid, in)
}

// BillingInvoices invoices for this subject.
//
// Calls client.BillingInvoices on commerce over the peer plane.
func BillingInvoices(ctx context.Context, in *client.InvoicesIn) (*client.Invoices, error) {
	return client.Call[client.InvoicesIn, client.Invoices](ctx, App, client.BillingInvoices, in)
}

// BillingMethodDetach remove one saved payment method.
//
// Calls client.BillingMethodDetach on commerce over the peer plane.
func BillingMethodDetach(ctx context.Context, in *client.MethodRef) (*client.Detachment, error) {
	return client.Call[client.MethodRef, client.Detachment](ctx, App, client.BillingMethodDetach, in)
}

// BillingMethodSave save a payment method for a subject.
//
// Calls client.BillingMethodSave on commerce over the peer plane.
func BillingMethodSave(ctx context.Context, in *client.MethodSaveIn) (*client.Rendered, error) {
	return client.Call[client.MethodSaveIn, client.Rendered](ctx, App, client.BillingMethodSave, in)
}

// BillingMethods cards and accounts a subject has on file.
//
// Calls client.BillingMethods on commerce over the peer plane.
func BillingMethods(ctx context.Context, in *client.MethodsIn) (*client.Rendered, error) {
	return client.Call[client.MethodsIn, client.Rendered](ctx, App, client.BillingMethods, in)
}

// BillingMode move this org between test and live money.
//
// Calls client.BillingMode on commerce over the peer plane.
func BillingMode(ctx context.Context, in *client.ModeIn) (*client.Mode, error) {
	return client.Call[client.ModeIn, client.Mode](ctx, App, client.BillingMode, in)
}

// BillingPayouts outbound payouts for this org.
//
// Calls client.BillingPayouts on commerce over the peer plane.
func BillingPayouts(ctx context.Context) (*client.Payouts, error) {
	return client.Call[struct{}, client.Payouts](ctx, App, client.BillingPayouts, &struct{}{})
}

// BillingPlans the public plan catalog.
//
// Calls client.BillingPlans on commerce over the peer plane.
func BillingPlans(ctx context.Context, in *client.PlansIn) (*client.Rendered, error) {
	return client.Call[client.PlansIn, client.Rendered](ctx, App, client.BillingPlans, in)
}

// BillingRate what one unit of a metered product costs.
//
// Calls client.BillingRate on commerce over the peer plane.
func BillingRate(ctx context.Context, in *client.RateIn) (*client.Rate, error) {
	return client.Call[client.RateIn, client.Rate](ctx, App, client.BillingRate, in)
}

// BillingRecharge recharge every org that has fallen below its threshold.
//
// Calls client.BillingRecharge on commerce over the peer plane.
func BillingRecharge(ctx context.Context) (*client.Recharge, error) {
	return client.Call[struct{}, client.Recharge](ctx, App, client.BillingRecharge, &struct{}{})
}

// BillingRollup a subject's month against their plan, and the wallet beside it.
//
// Calls client.BillingRollup on commerce over the peer plane.
func BillingRollup(ctx context.Context, in *client.RollupIn) (*client.Rollup, error) {
	return client.Call[client.RollupIn, client.Rollup](ctx, App, client.BillingRollup, in)
}

// BillingSettings public processor configuration for this org.
//
// Calls client.BillingSettings on commerce over the peer plane.
func BillingSettings(ctx context.Context) (*client.PaymentConfig, error) {
	return client.Call[struct{}, client.PaymentConfig](ctx, App, client.BillingSettings, &struct{}{})
}

// BillingSubscribe buy a plan with a card.
//
// Calls client.BillingSubscribe on commerce over the peer plane.
func BillingSubscribe(ctx context.Context, in *client.SaleIn) (*client.Sold, error) {
	return client.Call[client.SaleIn, client.Sold](ctx, App, client.BillingSubscribe, in)
}

// BillingSubscriptionCancel end a subscription.
//
// Calls client.BillingSubscriptionCancel on commerce over the peer plane.
func BillingSubscriptionCancel(ctx context.Context, in *client.SubscriptionRef) (*client.Subscription, error) {
	return client.Call[client.SubscriptionRef, client.Subscription](ctx, App, client.BillingSubscriptionCancel, in)
}

// BillingSubscriptionReactivate put a canceled subscription back on its plan.
//
// Calls client.BillingSubscriptionReactivate on commerce over the peer plane.
func BillingSubscriptionReactivate(ctx context.Context, in *client.SubscriptionRef) (*client.Subscription, error) {
	return client.Call[client.SubscriptionRef, client.Subscription](ctx, App, client.BillingSubscriptionReactivate, in)
}

// BillingSubscriptions the plans a subject holds.
//
// Calls client.BillingSubscriptions on commerce over the peer plane.
func BillingSubscriptions(ctx context.Context, in *client.SubsIn) (*client.Subscriptions, error) {
	return client.Call[client.SubsIn, client.Subscriptions](ctx, App, client.BillingSubscriptions, in)
}

// BillingTier what a subject's plan allows and what they can spend.
//
// Calls client.BillingTier on commerce over the peer plane.
func BillingTier(ctx context.Context, in *client.TierIn) (*client.Tier, error) {
	return client.Call[client.TierIn, client.Tier](ctx, App, client.BillingTier, in)
}

// BillingTopup charge a saved card and credit the wallet.
//
// Calls client.BillingTopup on commerce over the peer plane.
func BillingTopup(ctx context.Context, in *client.SavedCardIn) (*client.Charged, error) {
	return client.Call[client.SavedCardIn, client.Charged](ctx, App, client.BillingTopup, in)
}

// BillingTopupCard charge a single-use card token and credit the wallet.
//
// Calls client.BillingTopupCard on commerce over the peer plane.
func BillingTopupCard(ctx context.Context, in *client.CardIn) (*client.Charged, error) {
	return client.Call[client.CardIn, client.Charged](ctx, App, client.BillingTopupCard, in)
}

// BillingTransaction one ledger entry by its id.
//
// Calls client.BillingTransaction on commerce over the peer plane.
func BillingTransaction(ctx context.Context, in *client.TransactionRef) (*client.Transaction, error) {
	return client.Call[client.TransactionRef, client.Transaction](ctx, App, client.BillingTransaction, in)
}

// BillingTransactions one page of a subject's ledger.
//
// Calls client.BillingTransactions on commerce over the peer plane.
func BillingTransactions(ctx context.Context, in *client.TransactionsIn) (*client.Transactions, error) {
	return client.Call[client.TransactionsIn, client.Transactions](ctx, App, client.BillingTransactions, in)
}

// BillingWire receiving bank details for a wire top-up.
//
// Calls client.BillingWire on commerce over the peer plane.
func BillingWire(ctx context.Context, in *client.WireIn) (*client.WireInstructions, error) {
	return client.Call[client.WireIn, client.WireInstructions](ctx, App, client.BillingWire, in)
}

// CatalogRefresh refresh the model catalog by reading the upstream provider.
//
// Calls client.CatalogRefresh on commerce over the peer plane.
func CatalogRefresh(ctx context.Context) (*client.Refreshed, error) {
	return client.Call[struct{}, client.Refreshed](ctx, App, client.CatalogRefresh, &struct{}{})
}

// FinanceAuthorize authorize one prepaid spend.
//
// Calls client.FinanceAuthorize on commerce over the peer plane.
func FinanceAuthorize(ctx context.Context, in *client.AuthorizeIn) (*client.Verdict, error) {
	return client.Call[client.AuthorizeIn, client.Verdict](ctx, App, client.FinanceAuthorize, in)
}

// FinanceBalance spendable prepaid balance.
//
// Calls client.FinanceBalance on commerce over the peer plane.
func FinanceBalance(ctx context.Context, in *client.BalanceIn) (*client.Balance, error) {
	return client.Call[client.BalanceIn, client.Balance](ctx, App, client.FinanceBalance, in)
}

// FinanceCosts what we paid every vendor in a period.
//
// Calls client.FinanceCosts on commerce over the peer plane.
func FinanceCosts(ctx context.Context, in *client.CostsIn) (*client.Costs, error) {
	return client.Call[client.CostsIn, client.Costs](ctx, App, client.FinanceCosts, in)
}

// FinanceCredit credit one subject's prepaid ledger, exactly once per ref.
//
// Calls client.FinanceCredit on commerce over the peer plane.
func FinanceCredit(ctx context.Context, in *client.CreditIn) (*client.Credited, error) {
	return client.Call[client.CreditIn, client.Credited](ctx, App, client.FinanceCredit, in)
}

// FinanceRecord debit one metered act.
//
// Calls client.FinanceRecord on commerce over the peer plane.
func FinanceRecord(ctx context.Context, in *client.RecordIn) (*client.Recorded, error) {
	return client.Call[client.RecordIn, client.Recorded](ctx, App, client.FinanceRecord, in)
}

// FinanceScopeRules per-scope request-rate ceilings from this org's spend-alert rows.
//
// Calls client.FinanceScopeRules on commerce over the peer plane.
func FinanceScopeRules(ctx context.Context) (*client.ScopeRules, error) {
	return client.Call[struct{}, client.ScopeRules](ctx, App, client.FinanceScopeRules, &struct{}{})
}

// FinanceSpend metered consumption over a window, and the wallet behind it.
//
// Calls client.FinanceSpend on commerce over the peer plane.
func FinanceSpend(ctx context.Context, in *client.SpendIn) (*client.Spend, error) {
	return client.Call[client.SpendIn, client.Spend](ctx, App, client.FinanceSpend, in)
}

// FinanceSubs subscriptions for this org.
//
// Calls client.FinanceSubs on commerce over the peer plane.
func FinanceSubs(ctx context.Context, in *client.SubsIn) (*client.Subs, error) {
	return client.Call[client.SubsIn, client.Subs](ctx, App, client.FinanceSubs, in)
}

// FinanceTxns ledger entries for this org.
//
// Calls client.FinanceTxns on commerce over the peer plane.
func FinanceTxns(ctx context.Context, in *client.TxnsIn) (*client.Txns, error) {
	return client.Call[client.TxnsIn, client.Txns](ctx, App, client.FinanceTxns, in)
}

// FinanceUsage recorded debits for this org.
//
// Calls client.FinanceUsage on commerce over the peer plane.
func FinanceUsage(ctx context.Context) (*client.UsageRows, error) {
	return client.Call[struct{}, client.UsageRows](ctx, App, client.FinanceUsage, &struct{}{})
}

// StoreCurrent this org's storefront.
//
// Calls client.StoreCurrent on commerce over the peer plane.
func StoreCurrent(ctx context.Context, in *client.StoreIn) (*client.Store, error) {
	return client.Call[client.StoreIn, client.Store](ctx, App, client.StoreCurrent, in)
}

// StoreListing upsert one product listing.
//
// Calls client.StoreListing on commerce over the peer plane.
func StoreListing(ctx context.Context, in *client.ListingIn) (*client.Listed, error) {
	return client.Call[client.ListingIn, client.Listed](ctx, App, client.StoreListing, in)
}
