// Code generated by zipdoc; DO NOT EDIT.

package web3

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /v1/chains", zip.Doc{
		Description: "Reports the chains this deployment can reach. The list is the\ndeclared registry, so it is exactly what /v1/rpc will accept — a chain that\nappears here is one this deployment actually has an upstream for.",
		Fields: map[string]string{
			"Chain.chainId":    "ChainID is the EIP-155 id, so a caller can check it matches the wallet\nthey are about to sign with.",
			"Chain.id":         "ID is the URL name: the value of :chain.",
			"Chain.name":       "Name is for humans.",
			"chainList.chains": "Chains is every chain this deployment is configured to reach, sorted by\nid. Empty when none are configured — never a fabricated entry.",
		},
	})
	zip.Describe("GET /v1/chains/:chain", zip.Doc{
		Description: "Reports one chain and whether its upstream is answering. An\nunreachable chain is still a 200 with live:false — the chain is configured,\nwhich is a different fact from the chain being up, and a 502 here would make\na console page error rather than show the outage.",
		Fields: map[string]string{
			"Chain.chainId":      "ChainID is the EIP-155 id, so a caller can check it matches the wallet\nthey are about to sign with.",
			"Chain.id":           "ID is the URL name: the value of :chain.",
			"Chain.name":         "Name is for humans.",
			"chainRef.chain":     "Chain is the registry id, as in /v1/chains/lux.",
			"chainStatus.height": "Height is the latest block, omitted when the chain did not answer rather\nthan reported as zero — a zero height is a real value on a fresh chain.",
			"chainStatus.live":   "Live is whether the upstream answered eth_blockNumber.",
		},
	})
	zip.Describe("GET /v1/tokens/:chain/:address", zip.Doc{
		Description: "Reads an address's native balance on a chain.\n\nERC-20 positions are NOT enumerated here: eth_getBalance answers the native\none, but \"every token this address holds\" is an indexer question — there is no\nRPC call that answers it, and walking a token list would return a number that\nsilently omits whatever the list missed. explorer owns the indexer\nrelationship; this returns the balance the chain itself can prove.",
		Fields: map[string]string{
			"balances.address": "Address is the account they belong to.",
			"balances.chain":   "Chain is the chain the balances were read from.",
			"balances.native":  "Native is the chain's own currency, as a 0x-quantity — the RPC's own\nencoding, not a float, because a wei value does not survive float64.",
			"tokenRef.address": "Address is the account, 0x-prefixed.",
			"tokenRef.chain":   "Chain is the registry id.",
		},
	})
	zip.Describe("POST /v1/rpc/:chain", zip.Doc{
		Description: "Forwards a JSON-RPC call to the named chain and returns its answer\nunchanged. Only declared chains are reachable, and only to a caller with a\nvalidated principal — this is the deployment's upstream, not an open relay.",
		Fields: map[string]string{
			"rpcIn.chain":   "Chain is the registry id, from the URL.",
			"rpcIn.id":      "ID is echoed back untouched.",
			"rpcIn.jsonrpc": "JSONRPC must be \"2.0\" when present.",
			"rpcIn.method":  "Method is the RPC method, e.g. eth_getBalance.",
			"rpcIn.params":  "Params is the method's parameters, passed through unread.",
		},
	})
}
