package world

// allowedRSSHosts is the RSS/Atom feed host allowlist — the SSRF guard for
// fetchRSS. It is ported VERBATIM from world/api/rss-proxy.js ALLOWED_DOMAINS
// (the canonical ~180-domain list). A feed URL whose host is absent here is
// refused at both the PUT boundary (sanitizeFeeds) and at fetch time, so a
// pipeline can never coerce the pod into fetching an arbitrary internal host.
//
// Kept as a set for O(1) membership. This is the ONE source of truth for feed
// hosts in the backend; the frontend list is the upstream it is ported from.
var allowedRSSHosts = map[string]struct{}{
	"feeds.bbci.co.uk":         {},
	"www.theguardian.com":      {},
	"feeds.npr.org":            {},
	"news.google.com":          {},
	"www.aljazeera.com":        {},
	"rss.cnn.com":              {},
	"hnrss.org":                {},
	"feeds.arstechnica.com":    {},
	"www.theverge.com":         {},
	"www.cnbc.com":             {},
	"feeds.marketwatch.com":    {},
	"www.defenseone.com":       {},
	"breakingdefense.com":      {},
	"www.bellingcat.com":       {},
	"techcrunch.com":           {},
	"huggingface.co":           {},
	"www.technologyreview.com": {},
	"rss.arxiv.org":            {},
	"export.arxiv.org":         {},
	"www.federalreserve.gov":   {},
	"www.sec.gov":              {},
	"www.whitehouse.gov":       {},
	"www.state.gov":            {},
	"www.defense.gov":          {},
	"home.treasury.gov":        {},
	"www.justice.gov":          {},
	"tools.cdc.gov":            {},
	"www.fema.gov":             {},
	"www.dhs.gov":              {},
	"www.thedrive.com":         {},
	"krebsonsecurity.com":      {},
	"finance.yahoo.com":        {},
	"thediplomat.com":          {},
	"venturebeat.com":          {},
	"foreignpolicy.com":        {},
	"www.ft.com":               {},
	"openai.com":               {},
	"www.reutersagency.com":    {},
	"feeds.reuters.com":        {},
	"rsshub.app":               {},
	"asia.nikkei.com":          {},
	"www.cfr.org":              {},
	"www.csis.org":             {},
	"www.politico.com":         {},
	"www.brookings.edu":        {},
	"layoffs.fyi":              {},
	"www.defensenews.com":      {},
	"www.foreignaffairs.com":   {},
	"www.atlanticcouncil.org":  {},
	// Tech variant domains
	"www.zdnet.com":        {},
	"www.techmeme.com":     {},
	"www.darkreading.com":  {},
	"www.schneier.com":     {},
	"rss.politico.com":     {},
	"www.anandtech.com":    {},
	"www.tomshardware.com": {},
	"www.semianalysis.com": {},
	"feed.infoq.com":       {},
	"thenewstack.io":       {},
	"devops.com":           {},
	"dev.to":               {},
	"lobste.rs":            {},
	"changelog.com":        {},
	"seekingalpha.com":     {},
	"news.crunchbase.com":  {},
	"www.saastr.com":       {},
	"feeds.feedburner.com": {},
	// Additional tech variant domains
	"www.producthunt.com":  {},
	"www.axios.com":        {},
	"github.blog":          {},
	"githubnext.com":       {},
	"mshibanami.github.io": {},
	"www.engadget.com":     {},
	"news.mit.edu":         {},
	"dev.events":           {},
	// VC blogs
	"www.ycombinator.com":      {},
	"a16z.com":                 {},
	"review.firstround.com":    {},
	"www.sequoiacap.com":       {},
	"www.nfx.com":              {},
	"www.aaronsw.com":          {},
	"bothsidesofthetable.com":  {},
	"www.lennysnewsletter.com": {},
	"stratechery.com":          {},
	// Regional startup news
	"www.eu-startups.com": {},
	"tech.eu":             {},
	"sifted.eu":           {},
	"www.techinasia.com":  {},
	"kr-asia.com":         {},
	"techcabal.com":       {},
	"disrupt-africa.com":  {},
	"lavca.org":           {},
	"contxto.com":         {},
	"inc42.com":           {},
	"yourstory.com":       {},
	// Funding & VC
	"pitchbook.com":      {},
	"www.cbinsights.com": {},
	// Accelerators
	"www.techstars.com": {},
	// Middle East & Regional News
	"english.alarabiya.net":  {},
	"www.arabnews.com":       {},
	"www.timesofisrael.com":  {},
	"www.haaretz.com":        {},
	"www.scmp.com":           {},
	"kyivindependent.com":    {},
	"www.themoscowtimes.com": {},
	"feeds.24.com":           {},
	"feeds.capi24.com":       {}, // News24 redirect destination
	// International News Sources
	"www.france24.com":        {},
	"www.euronews.com":        {},
	"www.lemonde.fr":          {},
	"rss.dw.com":              {},
	"www.africanews.com":      {},
	"www.lasillavacia.com":    {},
	"www.channelnewsasia.com": {},
	"www.thehindu.com":        {},
	// International Organizations
	"news.un.org":         {},
	"www.iaea.org":        {},
	"www.who.int":         {},
	"www.cisa.gov":        {},
	"www.crisisgroup.org": {},
	// Think Tanks & Research
	"rusi.org":                  {},
	"warontherocks.com":         {},
	"www.aei.org":               {},
	"responsiblestatecraft.org": {},
	"www.fpri.org":              {},
	"jamestown.org":             {},
	"www.chathamhouse.org":      {},
	"ecfr.eu":                   {},
	"www.gmfus.org":             {},
	"www.wilsoncenter.org":      {},
	"www.lowyinstitute.org":     {},
	"www.mei.edu":               {},
	"www.stimson.org":           {},
	"www.cnas.org":              {},
	"carnegieendowment.org":     {},
	"www.rand.org":              {},
	"fas.org":                   {},
	"www.armscontrol.org":       {},
	"www.nti.org":               {},
	"thebulletin.org":           {},
	"www.iss.europa.eu":         {},
	// Economic & Food Security
	"www.fao.org":   {},
	"worldbank.org": {},
	"www.imf.org":   {},
	// Additional
	"news.ycombinator.com": {},
	// Finance variant
	"www.coindesk.com":  {},
	"cointelegraph.com": {},
}
