package company

import (
	"bytes"
	"fmt"
	"text/template"
	"time"
)

// templates.go generates the formation documents from the formation record. These
// are generated drafts rendered from the org's chosen structure, jurisdiction,
// name, and founders — the instruments a founder reviews and signs, NOT filed
// government records (the actual state filing is the FilingProvider seam). Each doc
// is rendered to Markdown bytes and pushed into the tenant's data room; the doc set
// depends on the entity type.

// genDoc is one rendered formation document.
type genDoc struct {
	Name        string
	ContentType string
	Data        []byte
}

// docTemplate pairs a filename with its template body. The body is executed against
// a *Formation plus a small helper map (year, etc.).
type docTemplate struct {
	name string
	tmpl string
}

// docsForStructure returns the document set for a structure. C-Corps get a
// Certificate of Incorporation + Bylaws + a founder stock purchase agreement; LLCs
// (including DAO-LLCs) get Articles of Organization + an Operating Agreement. Both
// get an incorporator/organizer action and a cap-table summary.
func docsForStructure(s Structure) []docTemplate {
	common := []docTemplate{{"cap-table-summary.md", tmplCapTable}}
	switch s {
	case StructureCCorp:
		return append([]docTemplate{
			{"certificate-of-incorporation.md", tmplCertificateOfIncorporation},
			{"bylaws.md", tmplBylaws},
			{"action-of-incorporator.md", tmplActionOfIncorporator},
			{"founder-stock-purchase.md", tmplFounderStock},
		}, common...)
	case StructureLLC, StructureDAOLLC:
		return append([]docTemplate{
			{"articles-of-organization.md", tmplArticlesOfOrganization},
			{"operating-agreement.md", tmplOperatingAgreement},
		}, common...)
	default:
		return common
	}
}

// renderFormationDocs renders every document for the formation's structure. It fails
// if the structure has no template set (an unknown structure never reaches here
// because guardStructureChosen validates it).
func renderFormationDocs(f *Formation) ([]genDoc, error) {
	set := docsForStructure(f.Structure)
	if len(set) == 0 {
		return nil, fmt.Errorf("no document templates for structure %q", f.Structure)
	}
	data := map[string]any{
		"F":    f,
		"Year": time.Now().Year(),
		"Date": time.Now().Format("January 2, 2006"),
	}
	funcs := template.FuncMap{
		// pct converts basis points to a percentage (100 bps == 1%).
		"pct": func(bps int) float64 { return float64(bps) / 100.0 },
	}
	out := make([]genDoc, 0, len(set))
	for _, dt := range set {
		t, err := template.New(dt.name).Funcs(funcs).Parse(dt.tmpl)
		if err != nil {
			return nil, fmt.Errorf("parse template %s: %w", dt.name, err)
		}
		var buf bytes.Buffer
		if err := t.Execute(&buf, data); err != nil {
			return nil, fmt.Errorf("render %s: %w", dt.name, err)
		}
		out = append(out, genDoc{Name: dt.name, ContentType: "text/markdown", Data: buf.Bytes()})
	}
	return out, nil
}

const tmplHeader = `> DRAFT — generated by Hanzo Company for review and signature. Not a filed government record; the state filing is performed by the filing partner.

`

const tmplCertificateOfIncorporation = tmplHeader + `# Certificate of Incorporation of {{.F.Name}}

**Jurisdiction:** State of {{if eq (printf "%s" .F.Jurisdiction) "DE"}}Delaware{{else}}Wyoming{{end}}
**Entity type:** C Corporation
**Date:** {{.Date}}

## Article I — Name
The name of the corporation is **{{.F.Name}}**.

## Article II — Registered Office
The corporation's registered office is located in the State of {{if eq (printf "%s" .F.Jurisdiction) "DE"}}Delaware{{else}}Wyoming{{end}}.

## Article III — Purpose
To engage in any lawful act or activity for which corporations may be organized.

## Article IV — Authorized Stock
The corporation is authorized to issue 10,000,000 shares of Common Stock, par value $0.0001 per share.

## Article V — Incorporator / Founders
{{range .F.Founders}}- {{.Name}} <{{.Email}}> — {{.EquityBps}} bps
{{end}}
`

const tmplBylaws = tmplHeader + `# Bylaws of {{.F.Name}}

Adopted {{.Date}}.

## 1. Offices
The corporation may have offices at such places as the Board of Directors determines.

## 2. Stockholders
Annual and special meetings of stockholders shall be held as provided herein.

## 3. Board of Directors
The business and affairs of the corporation shall be managed by its Board of Directors.

## 4. Officers
The officers of the corporation shall be a President, a Secretary, and a Treasurer.

## 5. Stock Certificates
Shares shall be represented by certificates or issued in uncertificated (book-entry) form recorded on the corporation's cap table.
`

const tmplActionOfIncorporator = tmplHeader + `# Action by Incorporator of {{.F.Name}}

The undersigned, being the incorporator of **{{.F.Name}}**, adopts the following resolutions as of {{.Date}}:

1. The Certificate of Incorporation is hereby adopted.
2. The Bylaws are hereby adopted.
3. The following persons are the initial founders and stockholders:
{{range .F.Founders}}   - {{.Name}} <{{.Email}}>
{{end}}
`

const tmplFounderStock = tmplHeader + `# Founder Stock Purchase Agreement — {{.F.Name}}

This agreement records the purchase of Common Stock by each founder as of {{.Date}}.

| Founder | Email | Ownership (bps) |
|---|---|---|
{{range .F.Founders}}| {{.Name}} | {{.Email}} | {{.EquityBps}} |
{{end}}

Shares vest per the company's standard schedule unless otherwise agreed. Total authorized: 10,000,000 shares of Common Stock.
`

const tmplArticlesOfOrganization = tmplHeader + `# Articles of Organization of {{.F.Name}}

**Jurisdiction:** State of {{if eq (printf "%s" .F.Jurisdiction) "DE"}}Delaware{{else}}Wyoming{{end}}
**Entity type:** {{if eq (printf "%s" .F.Structure) "dao-llc"}}DAO LLC{{else}}Limited Liability Company{{end}}
**Date:** {{.Date}}

## Article I — Name
The name of the limited liability company is **{{.F.Name}}**.

## Article II — Registered Office
The company's registered office is located in the State of {{if eq (printf "%s" .F.Jurisdiction) "DE"}}Delaware{{else}}Wyoming{{end}}.

## Article III — Management
The company is member-managed{{if eq (printf "%s" .F.Structure) "dao-llc"}}, with governance exercised through the company's on-chain governance mechanism as described in the Operating Agreement (Wyoming DAO LLC){{end}}.

## Article IV — Members
{{range .F.Founders}}- {{.Name}} <{{.Email}}> — {{.EquityBps}} bps membership interest
{{end}}
`

const tmplOperatingAgreement = tmplHeader + `# Operating Agreement of {{.F.Name}}

Effective {{.Date}}.

## 1. Formation
The members form a {{if eq (printf "%s" .F.Structure) "dao-llc"}}DAO LLC{{else}}Limited Liability Company{{end}} under the laws of {{if eq (printf "%s" .F.Jurisdiction) "DE"}}Delaware{{else}}Wyoming{{end}}.

## 2. Membership Interests
| Member | Email | Interest (bps) |
|---|---|---|
{{range .F.Founders}}| {{.Name}} | {{.Email}} | {{.EquityBps}} |
{{end}}

## 3. Management
{{if eq (printf "%s" .F.Structure) "dao-llc"}}The company is a Wyoming DAO LLC. Management is exercised through the company's smart-contract governance; this Operating Agreement incorporates the on-chain rules by reference, and in a conflict the algorithmically-expressed rules govern to the extent permitted by W.S. 17-31.{{else}}The company is member-managed. Decisions are made by a majority of membership interests unless otherwise stated.{{end}}

## 4. Capital and Distributions
Distributions are made in proportion to membership interests.
`

const tmplCapTable = tmplHeader + `# Cap Table Summary — {{.F.Name}}

As of {{.Date}}. Structure: {{.F.Structure}}. Jurisdiction: {{.F.Jurisdiction}}.

| Founder | Email | Ownership (bps) | Ownership (%) |
|---|---|---|---|
{{range .F.Founders}}| {{.Name}} | {{.Email}} | {{.EquityBps}} | {{printf "%.2f" (pct .EquityBps)}} |
{{end}}

This summary is seeded into the company's cap table (captable) at equity genesis and anchored on-chain.
`
