// Package legal mounts the ORG-SCOPED legal-document surface (/v1/legal): a versioned,
// org-overridable library of standardized templates, a PURE merge-field generation
// engine that renders those templates from the org's own company/cap-table data, a
// KMS-sealed store for the generated documents, and the e-signature + filing seams
// that carry a document to execution — all on the shared audit plane.
//
// THE BOUNDARY (a design invariant, enforced in the engine and the data model). Hanzo
// Legal MANAGES documents; it does NOT give legal advice, and it does NOT determine
// that a document is legally valid or sufficient. A generated document is a DRAFT
// rendered from the org's inputs; the legal determination belongs to the org's
// counsel. Formation and securities templates carry a mandatory counsel-review notice
// (CounselReview) that the engine prepends to every rendered document — the platform
// can never emit such a document without it. There is no "legally_valid" state in the
// model; a document is draft / out_for_signature / signed / voided, nothing more.
//
// WHAT IT COMPOSES (DRY):
//   - text/template  the PURE renderer (deterministic: no clock, no I/O — same inputs
//     yield identical bytes, so a rendered contract is reproducible).
//   - cek            encryption at rest for the document store (a rendered contract
//     carries names + terms and is sealed on disk).
//   - the Esign / Filing seams (providers.go) — provider-agnostic, honest-stub default,
//     config-driven real provider — mirroring the company formation seams.
//   - audit.Recorder the ONE tamper-evident trail (deps.Audit); every generate / sign /
//     file action is recorded, referencing opaque document ids.
package legal

// APIDisclaimer rides on every generation/template response — the boundary made
// visible on the wire (distinct from CounselNotice, which is embedded IN the rendered
// document).
const APIDisclaimer = "Hanzo Legal generates documents from your inputs and manages their lifecycle. " +
	"It is document tooling, not legal advice, and does not determine that a document is legally valid — " +
	"have your counsel review before execution."

// CounselNotice is prepended to every rendered document whose template is marked
// CounselReview (all formation and securities instruments). It is the boundary made
// visible on the document itself: a generated draft, for counsel review, not legal
// advice or a determination of validity.
const CounselNotice = "> DRAFT — generated by Hanzo Legal from your inputs for review by your counsel. " +
	"This is document tooling, not legal advice, and is not a determination that the document is " +
	"legally valid or sufficient. Have your attorney review before execution.\n\n"

// Category groups the template library by the corporate need it serves. Orthogonal to
// company formation (which generates the incorporation instruments from a Formation);
// Legal owns the general engine and the ongoing-operations catalog.
type Category string

const (
	CategoryFormation Category = "formation" // IP assignment, 83(b) election, ...
	CategoryEquity    Category = "equity"    // SAFE, subscription, option grant, ...
	CategoryOps       Category = "ops"       // NDA, MSA, SOW, offer letter, ...
	CategorySales     Category = "sales"     // ToS, privacy policy, DPA, ...
)

func validCategory(c Category) bool {
	switch c {
	case CategoryFormation, CategoryEquity, CategoryOps, CategorySales:
		return true
	}
	return false
}

// counselRequired reports whether a category is one whose documents MUST carry the
// counsel-review notice — formation instruments and securities (equity). It is the ONE
// source of truth for the boundary, coupled to the CATEGORY rather than a per-template
// flag, so a new org template in one of these categories can never generate a
// securities-class document without the notice.
func counselRequired(c Category) bool {
	return c == CategoryFormation || c == CategoryEquity
}

// Field declares one merge field a template consumes: the key used in the template
// body ({{.key}}) and a human label. Every declared field is REQUIRED — the engine
// fails closed on a missing one rather than rendering a blank into a contract.
type Field struct {
	Key   string `json:"key"`
	Label string `json:"label"`
}

// Template is one standardized document template. Body is a text/template source that
// references its Fields as {{.key}}. Version increments on each org override; a
// built-in has Version 1 and Origin "builtin". CounselReview marks the formation and
// securities instruments that must carry CounselNotice.
type Template struct {
	ID            string   `json:"id"`
	Category      Category `json:"category"`
	Title         string   `json:"title"`
	Version       int      `json:"version"`
	Origin        string   `json:"origin"` // builtin | org
	CounselReview bool     `json:"counselReview"`
	Fields        []Field  `json:"fields"`
	Body          string   `json:"body"`
}

// DocStatus is the lifecycle of a generated document. There is deliberately no
// "legally_valid" value — validity is counsel's determination, not the platform's.
type DocStatus string

const (
	StatusDraft     DocStatus = "draft"             // generated, not yet sent for signature
	StatusOutForSig DocStatus = "out_for_signature" // an e-signature request is open
	StatusSigned    DocStatus = "signed"            // the e-signature provider reported completion
	StatusVoided    DocStatus = "voided"            // withdrawn before execution
)

// Document is a generated legal document. Body is the rendered content — sealed at
// rest by the cek store, returned only to the owning org. It records which template
// version produced it (so a document is reproducible and auditable) and its signature
// lifecycle.
type Document struct {
	ID              string    `json:"id"`
	Org             string    `json:"org"`
	TemplateID      string    `json:"templateId"`
	TemplateVersion int       `json:"templateVersion"`
	Category        Category  `json:"category"`
	Title           string    `json:"title"`
	ContentType     string    `json:"contentType"`
	Body            string    `json:"body,omitempty"`
	Status          DocStatus `json:"status"`
	EsignProvider   string    `json:"esignProvider,omitempty"`
	EsignRef        string    `json:"esignRef,omitempty"`
	CreatedAt       int64     `json:"createdAt"`
	UpdatedAt       int64     `json:"updatedAt"`
	SignedAt        int64     `json:"signedAt,omitempty"`
}

// FilingStatus mirrors the company formation filing seam: honest states, no
// fabricated filing id when no partner is wired.
type FilingStatus string

const (
	FilingManual    FilingStatus = "manual"    // no partner wired — file through a registered agent
	FilingSubmitted FilingStatus = "submitted" // a partner accepted the submission
	FilingFiled     FilingStatus = "filed"     // the state accepted the filing
	FilingRejected  FilingStatus = "rejected"  // the state/partner rejected it
)

// Filing tracks a state/agency filing of one or more generated documents. It is a
// TRACKING record: the platform does not file autonomously; the honest default state
// is "manual" (file through your registered agent) until a filing partner is wired.
type Filing struct {
	ID           string       `json:"id"`
	Org          string       `json:"org"`
	DocumentIDs  []string     `json:"documentIds"`
	Jurisdiction string       `json:"jurisdiction,omitempty"`
	Provider     string       `json:"provider"`
	Status       FilingStatus `json:"status"`
	Note         string       `json:"note,omitempty"`
	CreatedAt    int64        `json:"createdAt"`
	UpdatedAt    int64        `json:"updatedAt"`
}
