// Package legal is the paperwork your company needs, drafted, signed and filed.
//
// The ORG-SCOPED legal-document surface (/v1/legal): a versioned,
// org-overridable library of standardized templates, a PURE merge-field
// generation engine that renders those templates from the org's own
// company/cap-table data, a KMS-sealed store for the generated documents, and
// the e-signature + filing seams that carry a document to execution — all on
// the shared audit plane.
//
// THE BOUNDARY (a design invariant, enforced in the engine and the data model). Hanzo
// Legal MANAGES documents; it does NOT give legal advice, and it does NOT determine
// that a document is legally valid or sufficient. A generated document is a DRAFT
// rendered from the org's inputs; the legal determination belongs to the org's
// counsel. Formation and securities templates carry a mandatory counsel-review notice
// (CounselReview) that the engine prepends to every rendered document — the platform
// can never emit such a document without it. There is no "legally_valid" state in the
// model; a document is draft / out_for_signature / signed / voided, nothing more.
//
// WHAT IT COMPOSES (DRY):
//   - text/template  the PURE renderer (deterministic: no clock, no I/O — same inputs
//     yield identical bytes, so a rendered contract is reproducible).
//   - cek            encryption at rest for the document store (a rendered contract
//     carries names + terms and is sealed on disk).
//   - the Esign / Filing seams (providers.go) — provider-agnostic, honest-stub default,
//     config-driven real provider — mirroring the company formation seams.
//   - audit.Recorder the ONE tamper-evident trail (deps.Audit); every generate / sign /
//     file action is recorded, referencing opaque document ids.
package legal

// APIDisclaimer rides on every generation/template response — the boundary made
// visible on the wire (distinct from CounselNotice, which is embedded IN the rendered
// document).
const APIDisclaimer = "Hanzo Legal generates documents from your inputs and manages their lifecycle. " +
	"It is document tooling, not legal advice, and does not determine that a document is legally valid — " +
	"have your counsel review before execution."

// CounselNotice is prepended to every rendered document whose template is marked
// CounselReview (all formation and securities instruments). It is the boundary made
// visible on the document itself: a generated draft, for counsel review, not legal
// advice or a determination of validity.
const CounselNotice = "> DRAFT — generated by Hanzo Legal from your inputs for review by your counsel. " +
	"This is document tooling, not legal advice, and is not a determination that the document is " +
	"legally valid or sufficient. Have your attorney review before execution.\n\n"

// Category groups the template library by the corporate need it serves. Orthogonal to
// company formation (which generates the incorporation instruments from a Formation);
// Legal owns the general engine and the ongoing-operations catalog.
type Category string

const (
	CategoryFormation Category = "formation" // IP assignment, 83(b) election, ...
	CategoryEquity    Category = "equity"    // SAFE, subscription, option grant, ...
	CategoryOps       Category = "ops"       // NDA, MSA, SOW, offer letter, ...
	CategorySales     Category = "sales"     // ToS, privacy policy, DPA, ...
)

func validCategory(c Category) bool {
	switch c {
	case CategoryFormation, CategoryEquity, CategoryOps, CategorySales:
		return true
	}
	return false
}

// counselRequired reports whether a category is one whose documents MUST carry the
// counsel-review notice — formation instruments and securities (equity). It is the ONE
// source of truth for the boundary, coupled to the CATEGORY rather than a per-template
// flag, so a new org template in one of these categories can never generate a
// securities-class document without the notice.
func counselRequired(c Category) bool {
	return c == CategoryFormation || c == CategoryEquity
}

// Field declares one merge field a template consumes: the key used in the template
// body ({{.key}}) and a human label. Every declared field is REQUIRED — the engine
// fails closed on a missing one rather than rendering a blank into a contract.
type Field struct {
	// Key is the identifier the body substitutes ({{.key}}) and the key a
	// generation's data map must carry. snake_case by convention across the
	// built-ins — effective_date, company_name, governing_law. An override whose
	// body references a key no Field declares is refused on save.
	Key string `json:"key"`
	// Label is the human prompt for whoever fills the value in — "Governing law
	// (state)". It never reaches the rendered document; only Key does.
	Label string `json:"label"`
}

// Template is one standardized document template, resolved for an org: its own
// override if it has saved one, else the built-in.
type Template struct {
	// ID is the template's stable id and the path segment that addresses it —
	// "nda", "msa", "safe". An override keeps the built-in's id, so the id names
	// the DOCUMENT KIND rather than a particular version of it.
	ID string `json:"id"`
	// Category is the corporate need the template serves: formation, equity, ops or
	// sales. Formation and equity are the securities-class categories, which is what
	// forces CounselReview.
	Category Category `json:"category"`
	// Title is the display name, e.g. "Mutual Non-Disclosure Agreement". A generated
	// document inherits it.
	Title string `json:"title"`
	// Version is which version of this template the caller resolved to, and what a
	// generated document records so it stays reproducible. A built-in is version 1;
	// an org's first override is 2 and each save increments, so an override version
	// never collides with the built-in's.
	Version int `json:"version"`
	// Origin is "builtin" for a template the platform ships or "org" for one this
	// org saved. It separates the catalog every tenant sees from this tenant's own.
	Origin string `json:"origin"`
	// CounselReview marks a template whose rendered documents open with
	// CounselNotice. It can be raised but never lowered, and the engine also raises
	// it for any formation or equity template whatever the flag says — so no org can
	// render a securities-class document without the notice.
	CounselReview bool `json:"counselReview"`
	// Fields declares the merge fields Body consumes, each with its human label.
	// Every one is REQUIRED at generation: a missing or blank value is refused
	// rather than rendered as a silent blank into a contract.
	Fields []Field `json:"fields"`
	// Body is the text/template source, markdown, referencing each declared field as
	// {{.key}}. Rendering is pure — no clock, no I/O — so a template version and a
	// data map always produce identical bytes. Only the single-template read carries
	// it; the catalog listing does not.
	Body string `json:"body"`
}

// DocStatus is the lifecycle of a generated document. There is deliberately no
// "legally_valid" value — validity is counsel's determination, not the platform's.
type DocStatus string

const (
	StatusDraft     DocStatus = "draft"             // generated, not yet sent for signature
	StatusOutForSig DocStatus = "out_for_signature" // an e-signature request is open
	StatusSigned    DocStatus = "signed"            // the e-signature provider reported completion
	StatusVoided    DocStatus = "voided"            // withdrawn before execution
)

// Document is a generated legal document. Body is the rendered content — sealed at
// rest by the cek store, returned only to the owning org. It records which template
// version produced it (so a document is reproducible and auditable) and its signature
// lifecycle.
type Document struct {
	ID              string    `json:"id"`
	Org             string    `json:"org"`
	TemplateID      string    `json:"templateId"`
	TemplateVersion int       `json:"templateVersion"`
	Category        Category  `json:"category"`
	Title           string    `json:"title"`
	ContentType     string    `json:"contentType"`
	Body            string    `json:"body,omitempty"`
	Status          DocStatus `json:"status"`
	EsignProvider   string    `json:"esignProvider,omitempty"`
	EsignRef        string    `json:"esignRef,omitempty"`
	CreatedAt       int64     `json:"createdAt"`
	UpdatedAt       int64     `json:"updatedAt"`
	SignedAt        int64     `json:"signedAt,omitempty"`
}

// FilingStatus mirrors the company formation filing seam: honest states, no
// fabricated filing id when no partner is wired.
type FilingStatus string

const (
	FilingManual    FilingStatus = "manual"    // no partner wired — file through a registered agent
	FilingSubmitted FilingStatus = "submitted" // a partner accepted the submission
	FilingFiled     FilingStatus = "filed"     // the state accepted the filing
	FilingRejected  FilingStatus = "rejected"  // the state/partner rejected it
)

// Filing tracks a state/agency filing of one or more generated documents. It is a
// TRACKING record: the platform does not file autonomously; the honest default state
// is "manual" (file through your registered agent) until a filing partner is wired.
type Filing struct {
	// ID is the filing's server-minted handle, "filing_"-prefixed. It is OURS, not
	// the state's — a state file number arrives only from a real filing partner.
	ID string `json:"id"`
	// Org owns the filing. Every query is scoped to it, so another tenant's filing
	// is indistinguishable from a missing one.
	Org string `json:"org"`
	// DocumentIDs are the generated documents this filing covers. At least one, and
	// each must already belong to Org — a filing can never reach across tenants.
	DocumentIDs []string `json:"documentIds"`
	// Jurisdiction is the state or agency the filing is for, as the caller wrote it
	// ("DE"). Free text, not validated against a list. Absent when the caller sent
	// none.
	Jurisdiction string `json:"jurisdiction,omitempty"`
	// Provider is the filing partner that took the submission, or "manual" when no
	// partner is wired on this deployment.
	Provider string `json:"provider"`
	// Status is where the filing stands: manual (no partner wired — file through
	// your registered agent), submitted (a partner accepted it), filed (the state
	// accepted it) or rejected.
	Status FilingStatus `json:"status"`
	// Note is the provider's explanation of Status, in prose meant for a person. On
	// the manual default it says the documents were generated for signature and the
	// org files them through its registered agent. Absent when the provider offered
	// nothing.
	Note string `json:"note,omitempty"`
	// CreatedAt is when the filing was recorded, in unix seconds.
	CreatedAt int64 `json:"createdAt"`
	// UpdatedAt is when it last changed, in unix seconds. Equal to CreatedAt until a
	// provider reports movement.
	UpdatedAt int64 `json:"updatedAt"`
}
