// Code generated by zipdoc; DO NOT EDIT.

package webhook

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("github.com/hanzoai/cloud/apps/webhook DELETE /v1/webhook/:id", zip.Doc{
		Description: "Removes one of the caller org's webhook endpoints and answers\n204 with no body. Delivery stops immediately and the endpoint's signing secret\nis gone with it; its recorded delivery history goes too. An id another org owns\nreads as not found.",
		Example:     json.RawMessage(`{"id":"wh_9f8c1d2e"}`),
	})
	zip.Describe("github.com/hanzoai/cloud/apps/webhook GET /v1/webhook", zip.Doc{
		Description: "Returns every webhook endpoint the caller's org has registered,\nnewest first, each with its 7-day delivery and failure counts. Signing secrets\nare redacted here — a secret leaves the server only on create and on rotate.\nThe listing is physically org-scoped, so another tenant's endpoints are not\nreachable from this route at all.",
		Fields: map[string]string{
			"Endpoint.created":      "CreatedAt is when the endpoint was registered, RFC3339 in UTC — stored in that\nspelling because it sorts as a string.",
			"Endpoint.deliveries7d": "Deliveries7d is how many deliveries SETTLED in the trailing 7 days — the\nattempts that ended ok or failed, so a delivery still retrying is in neither\ncounter yet. It is counted from the log at read time rather than stored, and\nit is filled only on a list or a get; a create answers 0 because there is no\nhistory, which is why it is never omitted.",
			"Endpoint.description":  "Description is the operator's own label for the endpoint. Never sent anywhere.",
			"Endpoint.events":       "Events are the subject patterns this endpoint subscribes to\n(\"commerce.order.>\"). An EMPTY list means every event, not none.",
			"Endpoint.failures7d":   "Failures7d is how many of those settled as failed — the subscriber never\naccepted it and no further attempt will be made. It is the numerator to\nDeliveries7d, over the same window.",
			"Endpoint.id":           "ID is the endpoint's handle, server-minted and stable for its life. It is what\nevery other route here addresses.",
			"Endpoint.org":          "Org is the tenant that owns the endpoint, taken from the validated principal\nrather than from any request field.",
			"Endpoint.secret":       "Secret is the HMAC-SHA256 signing key a subscriber recomputes the signature\nwith. It is returned exactly ONCE, on create: a later read of the endpoint\nomits it, so a lost secret is replaced rather than recovered.",
			"Endpoint.status":       "Status is \"active\" or \"disabled\" — nothing else is accepted. A disabled\nendpoint keeps its subscription and receives no deliveries, except a manual\ntest send, which goes out anyway.",
			"Endpoint.updated":      "UpdatedAt is when its url, events, status or description last changed.",
			"Endpoint.url":          "URL is where the POST goes. Changing it is the one edit that redirects an\norg's events, which is why it is never bindable from a query string.",
			"endpointList.data":     "Data is the org's endpoints, newest first, each with its signing secret\nREDACTED — the secret leaves the server only on create and on rotate.",
		},
	})
	zip.Describe("github.com/hanzoai/cloud/apps/webhook GET /v1/webhook/:id", zip.Doc{
		Description: "Returns one of the caller org's webhook endpoints with its 7-day\ndelivery and failure counts, signing secret redacted. An id another org owns\nreads as not found, so the response cannot confirm that it exists.",
		Fields: map[string]string{
			"Endpoint.created":      "CreatedAt is when the endpoint was registered, RFC3339 in UTC — stored in that\nspelling because it sorts as a string.",
			"Endpoint.deliveries7d": "Deliveries7d is how many deliveries SETTLED in the trailing 7 days — the\nattempts that ended ok or failed, so a delivery still retrying is in neither\ncounter yet. It is counted from the log at read time rather than stored, and\nit is filled only on a list or a get; a create answers 0 because there is no\nhistory, which is why it is never omitted.",
			"Endpoint.description":  "Description is the operator's own label for the endpoint. Never sent anywhere.",
			"Endpoint.events":       "Events are the subject patterns this endpoint subscribes to\n(\"commerce.order.>\"). An EMPTY list means every event, not none.",
			"Endpoint.failures7d":   "Failures7d is how many of those settled as failed — the subscriber never\naccepted it and no further attempt will be made. It is the numerator to\nDeliveries7d, over the same window.",
			"Endpoint.id":           "ID is the endpoint's handle, server-minted and stable for its life. It is what\nevery other route here addresses.",
			"Endpoint.org":          "Org is the tenant that owns the endpoint, taken from the validated principal\nrather than from any request field.",
			"Endpoint.secret":       "Secret is the HMAC-SHA256 signing key a subscriber recomputes the signature\nwith. It is returned exactly ONCE, on create: a later read of the endpoint\nomits it, so a lost secret is replaced rather than recovered.",
			"Endpoint.status":       "Status is \"active\" or \"disabled\" — nothing else is accepted. A disabled\nendpoint keeps its subscription and receives no deliveries, except a manual\ntest send, which goes out anyway.",
			"Endpoint.updated":      "UpdatedAt is when its url, events, status or description last changed.",
			"Endpoint.url":          "URL is where the POST goes. Changing it is the one edit that redirects an\norg's events, which is why it is never bindable from a query string.",
		},
		Example: json.RawMessage(`{"id":"wh_9f8c1d2e"}`),
	})
	zip.Describe("github.com/hanzoai/cloud/apps/webhook GET /v1/webhook/:id/deliveries", zip.Doc{
		Description: "Returns one endpoint's per-attempt delivery log, newest first —\nthe record of what was sent, what the subscriber answered, and how long it\ntook. One event that retried three times appears as three rows sharing a\ndelivery id. It is org-scoped exactly like every other route here: the endpoint\nlookup only ever finds THIS org's endpoint, so another org's id is a 404 and\nnever a window onto its logs.",
		Fields: map[string]string{
			"DeliveryRow.attempt":     "Attempt is which try this row is, starting at 1. The ladder waits 1s, then 5s,\nthen 25s before the next one.",
			"DeliveryRow.created":     "Created is when the attempt was made, RFC3339 in UTC.",
			"DeliveryRow.delivery":    "DeliveryID groups the attempts for ONE event to ONE endpoint. Rows sharing it\nare the same delivery being retried, not separate events.",
			"DeliveryRow.durationMs":  "DurationMs is how long this attempt took end to end, in MILLISECONDS.",
			"DeliveryRow.endpoint":    "EndpointID is which subscriber this attempt was for.",
			"DeliveryRow.error":       "Error says what went wrong on a non-ok attempt. Empty on success.",
			"DeliveryRow.httpStatus":  "HTTPStatus is what the subscriber answered. ZERO means it never answered — a\nrefused connection, a DNS failure or a timeout — which is why a zero here is\nnot a 200.",
			"DeliveryRow.status":      "Status is \"ok\" when the subscriber accepted it, \"retrying\" while a further\nattempt will follow, and \"failed\" when none will. Exactly one row of a delivery\nis terminal.",
			"DeliveryRow.subject":     "Subject is the event that was delivered (\"commerce.order.created\"). A manual\ntest send carries \"webhook.test\".",
			"deliveryList.data":       "Data is the matching attempts, newest first.",
			"listDeliveriesIn.limit":  "Limit caps how many attempts come back: default 50, maximum 200. A value\nthat is not a positive integer reads as the default.",
			"listDeliveriesIn.status": "Status narrows the log to one outcome: \"ok\", \"retrying\" or \"failed\".\nEmpty returns every attempt.",
		},
		Example: json.RawMessage(`{"id":"wh_9f8c1d2e","status":"failed","limit":100}`),
	})
	zip.Describe("github.com/hanzoai/cloud/apps/webhook POST /v1/webhook", zip.Doc{
		Description: "Registers a new webhook subscription for the caller's org and\nanswers 201 with the endpoint INCLUDING its freshly minted signing secret.\nThis is one of only two responses that ever carry that secret (the other is\nrotate) — store it now, because no later read returns it. The org is stamped by\nthe server from the validated principal, so a body can never register an\nendpoint in another tenant.",
		Fields: map[string]string{
			"Endpoint.created":             "CreatedAt is when the endpoint was registered, RFC3339 in UTC — stored in that\nspelling because it sorts as a string.",
			"Endpoint.deliveries7d":        "Deliveries7d is how many deliveries SETTLED in the trailing 7 days — the\nattempts that ended ok or failed, so a delivery still retrying is in neither\ncounter yet. It is counted from the log at read time rather than stored, and\nit is filled only on a list or a get; a create answers 0 because there is no\nhistory, which is why it is never omitted.",
			"Endpoint.description":         "Description is the operator's own label for the endpoint. Never sent anywhere.",
			"Endpoint.events":              "Events are the subject patterns this endpoint subscribes to\n(\"commerce.order.>\"). An EMPTY list means every event, not none.",
			"Endpoint.failures7d":          "Failures7d is how many of those settled as failed — the subscriber never\naccepted it and no further attempt will be made. It is the numerator to\nDeliveries7d, over the same window.",
			"Endpoint.id":                  "ID is the endpoint's handle, server-minted and stable for its life. It is what\nevery other route here addresses.",
			"Endpoint.org":                 "Org is the tenant that owns the endpoint, taken from the validated principal\nrather than from any request field.",
			"Endpoint.secret":              "Secret is the HMAC-SHA256 signing key a subscriber recomputes the signature\nwith. It is returned exactly ONCE, on create: a later read of the endpoint\nomits it, so a lost secret is replaced rather than recovered.",
			"Endpoint.status":              "Status is \"active\" or \"disabled\" — nothing else is accepted. A disabled\nendpoint keeps its subscription and receives no deliveries, except a manual\ntest send, which goes out anyway.",
			"Endpoint.updated":             "UpdatedAt is when its url, events, status or description last changed.",
			"Endpoint.url":                 "URL is where the POST goes. Changing it is the one edit that redirects an\norg's events, which is why it is never bindable from a query string.",
			"createEndpointIn.description": "Description is a free-text label for the console. Optional, clipped to 1024 bytes.",
			"createEndpointIn.events":      "Events are NATS subject patterns to subscribe to (e.g. \"commerce.order.>\").\nAn empty or omitted list means EVERY event on the platform bus. Max 64\npatterns, each max 256 bytes.",
			"createEndpointIn.status":      "Status is \"active\" or \"disabled\". Empty defaults to active. A disabled\nendpoint receives no bus deliveries, but can still be exercised with\nPOST /v1/webhook/{id}/test.",
			"createEndpointIn.url":         "URL is the https:// address each matching event is POSTed to. Required,\nmax 2048 bytes; http:// and every other scheme is refused, because a\nwebhook carries signed event data and must not travel in the clear.",
		},
		Example: json.RawMessage(`{"url":"https://acme.example/hooks/hanzo","events":["commerce.order.>"],"description":"order pipeline"}`),
	})
	zip.Describe("github.com/hanzoai/cloud/apps/webhook POST /v1/webhook/:id/secret", zip.Doc{
		Description: "Mints a NEW HMAC signing secret for the endpoint and answers the\nendpoint WITH it — the only other response besides create that ever carries a\nsecret. The old secret stops working the instant this returns: every subsequent\ndelivery signs with the new one, with no overlap window. Call it when the\nsubscriber is ready to swap the value on its side, not before.",
		Fields: map[string]string{
			"Endpoint.created":      "CreatedAt is when the endpoint was registered, RFC3339 in UTC — stored in that\nspelling because it sorts as a string.",
			"Endpoint.deliveries7d": "Deliveries7d is how many deliveries SETTLED in the trailing 7 days — the\nattempts that ended ok or failed, so a delivery still retrying is in neither\ncounter yet. It is counted from the log at read time rather than stored, and\nit is filled only on a list or a get; a create answers 0 because there is no\nhistory, which is why it is never omitted.",
			"Endpoint.description":  "Description is the operator's own label for the endpoint. Never sent anywhere.",
			"Endpoint.events":       "Events are the subject patterns this endpoint subscribes to\n(\"commerce.order.>\"). An EMPTY list means every event, not none.",
			"Endpoint.failures7d":   "Failures7d is how many of those settled as failed — the subscriber never\naccepted it and no further attempt will be made. It is the numerator to\nDeliveries7d, over the same window.",
			"Endpoint.id":           "ID is the endpoint's handle, server-minted and stable for its life. It is what\nevery other route here addresses.",
			"Endpoint.org":          "Org is the tenant that owns the endpoint, taken from the validated principal\nrather than from any request field.",
			"Endpoint.secret":       "Secret is the HMAC-SHA256 signing key a subscriber recomputes the signature\nwith. It is returned exactly ONCE, on create: a later read of the endpoint\nomits it, so a lost secret is replaced rather than recovered.",
			"Endpoint.status":       "Status is \"active\" or \"disabled\" — nothing else is accepted. A disabled\nendpoint keeps its subscription and receives no deliveries, except a manual\ntest send, which goes out anyway.",
			"Endpoint.updated":      "UpdatedAt is when its url, events, status or description last changed.",
			"Endpoint.url":          "URL is where the POST goes. Changing it is the one edit that redirects an\norg's events, which is why it is never bindable from a query string.",
		},
		Example: json.RawMessage(`{"id":"wh_9f8c1d2e"}`),
	})
	zip.Describe("github.com/hanzoai/cloud/apps/webhook POST /v1/webhook/:id/test", zip.Doc{
		Description: "Sends ONE signed test event to the endpoint right now and answers\nthe outcome inline, so the console can show whether the subscriber is reachable\nwithout waiting for real traffic. It takes the same attempt path the bus\ndispatcher takes — one attempt, 10s timeout, no retry ladder — and records the\nresult in the endpoint's delivery log. It works on a DISABLED endpoint too:\nvalidating one you have paused is the whole point.",
		Fields: map[string]string{
			"testResult.delivered":  "Delivered is whether the subscriber accepted the test POST. It is the whole\nanswer: the send is synchronous and is not retried.",
			"testResult.durationMs": "DurationMs is how long the single attempt took, in MILLISECONDS.",
			"testResult.error":      "Error says what stopped it. Empty when delivered.",
			"testResult.httpStatus": "HTTPStatus is what the subscriber answered, or 0 if it never answered.",
		},
		Example: json.RawMessage(`{"id":"wh_9f8c1d2e"}`),
	})
	zip.Describe("github.com/hanzoai/cloud/apps/webhook PUT /v1/webhook/:id", zip.Doc{
		Description: "Replaces the editable fields of one of the caller org's\nendpoints — url, events, status and description — and answers the stored row\nwith its secret redacted. It is a full replace, not a patch: an omitted field\nis written as its empty value, and an omitted or empty events list resubscribes\nthe endpoint to EVERY event. The signing secret and the creation time are\nimmutable here; rotate the secret with POST /v1/webhook/{id}/secret.",
		Fields: map[string]string{
			"Endpoint.created":             "CreatedAt is when the endpoint was registered, RFC3339 in UTC — stored in that\nspelling because it sorts as a string.",
			"Endpoint.deliveries7d":        "Deliveries7d is how many deliveries SETTLED in the trailing 7 days — the\nattempts that ended ok or failed, so a delivery still retrying is in neither\ncounter yet. It is counted from the log at read time rather than stored, and\nit is filled only on a list or a get; a create answers 0 because there is no\nhistory, which is why it is never omitted.",
			"Endpoint.description":         "Description is the operator's own label for the endpoint. Never sent anywhere.",
			"Endpoint.events":              "Events are the subject patterns this endpoint subscribes to\n(\"commerce.order.>\"). An EMPTY list means every event, not none.",
			"Endpoint.failures7d":          "Failures7d is how many of those settled as failed — the subscriber never\naccepted it and no further attempt will be made. It is the numerator to\nDeliveries7d, over the same window.",
			"Endpoint.id":                  "ID is the endpoint's handle, server-minted and stable for its life. It is what\nevery other route here addresses.",
			"Endpoint.org":                 "Org is the tenant that owns the endpoint, taken from the validated principal\nrather than from any request field.",
			"Endpoint.secret":              "Secret is the HMAC-SHA256 signing key a subscriber recomputes the signature\nwith. It is returned exactly ONCE, on create: a later read of the endpoint\nomits it, so a lost secret is replaced rather than recovered.",
			"Endpoint.status":              "Status is \"active\" or \"disabled\" — nothing else is accepted. A disabled\nendpoint keeps its subscription and receives no deliveries, except a manual\ntest send, which goes out anyway.",
			"Endpoint.updated":             "UpdatedAt is when its url, events, status or description last changed.",
			"Endpoint.url":                 "URL is where the POST goes. Changing it is the one edit that redirects an\norg's events, which is why it is never bindable from a query string.",
			"updateEndpointIn.description": "Description is a free-text label for the console. Optional, clipped to 1024 bytes.",
			"updateEndpointIn.events":      "Events are NATS subject patterns to subscribe to. An empty or omitted list\nmeans EVERY event. Max 64 patterns, each max 256 bytes.",
			"updateEndpointIn.status":      "Status is \"active\" or \"disabled\". Empty defaults to active.",
			"updateEndpointIn.url":         "URL is the https:// address each matching event is POSTed to. Required,\nmax 2048 bytes; http:// and every other scheme is refused.",
		},
		Example: json.RawMessage(`{"id":"wh_9f8c1d2e","url":"https://acme.example/hooks/v2","events":["commerce.order.paid"],"status":"disabled"}`),
	})
}
