// Code generated by zipdoc; DO NOT EDIT.

package allowance

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("github.com/hanzoai/cloud/apps/allowance GET /v1/allowance", zip.Doc{
		Description: "Answers what the CALLER has left of their plan's free-call allowance this period,\nand the instant the count starts again.\n\nThis is the number a product shows beside the composer — \"17 of 20 left today\" —\nand the moment to offer a plan is when it reaches zero. It READS: asking does not\nspend, so a page that polls it costs the caller nothing.\n\nThe subject is the caller's own, resolved from the verified credential, and can\nnever be named in the request — so this is a mirror, not a lookup of someone else.\nAn unauthenticated caller is refused: there is no allowance without someone to\nhold it.\n\nA named handler, not a closure, so zipdoc can lift this prose into the registry.",
		Fields: map[string]string{
			"Allowance.limit":  "calls the plan allows per period; 0 = unbounded",
			"Allowance.plan":   "the tier the limit came from",
			"Allowance.resets": "unix seconds; when THAT window starts again",
			"Allowance.spent":  "the subject is at the limit",
			"Allowance.used":   "Used is how many zero-priced calls this subject has been SERVED in the period\nending at Resets — the UTC calendar day. Only a served call counts, so an\nadmission check, a refusal, or a vendor that never answered leaves it where it\nstood. It stops AT Limit rather than climbing past it, so Limit-Used is what\nremains and never goes negative.",
			"Allowance.window": "Window is which ceiling these numbers describe — \"hour\" or \"day\" — because a\ncaller is held to both and only one of them is the answer. It is the window\nthat REFUSED where one did, and otherwise the one with least left, so\nLimit-Used is always the number that will actually stop them next. Empty\nwhere no window bounds the subject at all.",
		},
	})
	zip.Describe("github.com/hanzoai/cloud/apps/allowance POST /allowance/read", zip.Doc{
		Description: "Answers what a subject has left of their plan's free-call allowance this period,\nwithout counting anything: the tier the ceiling came from, the ceiling, the count,\nwhether it is spent, and when it starts again.\n\nTHIS IS THE ADMISSION HALF. The gate asks it before a call and refuses a subject at\nthe ceiling; asking costs the subject nothing, so a refusal never becomes usage and\na request that dies before any model leaves the count exactly where it found it.\n\nThe ORG is the CALLER'S — the gateway's assertion — and can never be named in the\ninput. It selects the TIER, which is the ceiling this subject is held to. The row\nitself is addressed by subject alone (see Store), so what keeps one caller out of\nanother's count is the subject the gate resolved from a verified credential, and\nthe plane's own boundary: this answers on a unix socket inside the pod and has no\naddress on the edge.\n\nA named handler, not a closure, so zipdoc can lift this prose into the registry.",
		Fields: map[string]string{
			"Allowance.limit":  "calls the plan allows per period; 0 = unbounded",
			"Allowance.plan":   "the tier the limit came from",
			"Allowance.resets": "unix seconds; when THAT window starts again",
			"Allowance.spent":  "the subject is at the limit",
			"Allowance.used":   "Used is how many zero-priced calls this subject has been SERVED in the period\nending at Resets — the UTC calendar day. Only a served call counts, so an\nadmission check, a refusal, or a vendor that never answered leaves it where it\nstood. It stops AT Limit rather than climbing past it, so Limit-Used is what\nremains and never goes negative.",
			"Allowance.window": "Window is which ceiling these numbers describe — \"hour\" or \"day\" — because a\ncaller is held to both and only one of them is the answer. It is the window\nthat REFUSED where one did, and otherwise the one with least left, so\nLimit-Used is always the number that will actually stop them next. Empty\nwhere no window bounds the subject at all.",
		},
	})
	zip.Describe("github.com/hanzoai/cloud/apps/allowance POST /allowance/take", zip.Doc{
		Description: "Counts ONE SERVED zero-priced call against a subject's plan allowance for the\ncurrent period and answers what stands after it: the tier the ceiling came from,\nthe ceiling, the count, whether it is now spent, and when it starts again.\n\nThe ORG is the CALLER'S — the gateway's assertion — and can never be named in the\ninput; it selects the TIER whose ceiling applies. The row is addressed by subject\nalone, so what keeps one caller out of another's count is the subject the gate\nresolved from a verified credential, and the plane's own boundary.\n\nA CALL IS COUNTED WHERE IT ANSWERED. The ceiling bounds spend and spend is incurred\nwhen a model is reached, so the gate asks AllowanceRead before the call and this is\nreached only from the caller's record of a served one. Nothing else may reach it:\ncounting an attempt charges a customer for an outage of ours.\n\nThe read and the increment inside it are ONE statement in ONE transaction, so two\nserved calls arriving together cannot both write the same count. A subject already\nat the ceiling is answered spent=true with their count unchanged — refusals are not\nusage.\n\nA named handler, not a closure, so zipdoc can lift this prose into the registry.",
		Fields: map[string]string{
			"Allowance.limit":  "calls the plan allows per period; 0 = unbounded",
			"Allowance.plan":   "the tier the limit came from",
			"Allowance.resets": "unix seconds; when THAT window starts again",
			"Allowance.spent":  "the subject is at the limit",
			"Allowance.used":   "Used is how many zero-priced calls this subject has been SERVED in the period\nending at Resets — the UTC calendar day. Only a served call counts, so an\nadmission check, a refusal, or a vendor that never answered leaves it where it\nstood. It stops AT Limit rather than climbing past it, so Limit-Used is what\nremains and never goes negative.",
			"Allowance.window": "Window is which ceiling these numbers describe — \"hour\" or \"day\" — because a\ncaller is held to both and only one of them is the answer. It is the window\nthat REFUSED where one did, and otherwise the one with least left, so\nLimit-Used is always the number that will actually stop them next. Empty\nwhere no window bounds the subject at all.",
		},
	})
}
