// Code generated by plane/gen; DO NOT EDIT.

// Package platform is the typed client for the "platform" app's internal ops.
//
// Every call here is a ZAP call BY NAME over the peer's unix socket — no URL, no
// env var, no HTTP round trip, and no way to reach the public edge by accident.
// That last one is not a style preference: platform's own callers used to reach it
// through CLOUD_COMMERCE_HTTP_URL, which defaulted to the api.hanzo.ai edge —
// the SAME binary — so the forwarder re-entered itself and the billing gate died
// of it. A call by name cannot express that mistake.
//
// It depends on the CONTRACT (package plane) and never on platform's implementation,
// so importing it costs a caller nothing but the types it is already sending.
package platform

import (
	"context"

	"github.com/hanzoai/cloud/plane"
)

// App is the peer's name, which is also the socket it answers on. It is the
// ONE place this package spells it.
const App = "platform"

// Ops is every op this peer answers, in the spelling the wire uses.
//
// It exists so a test can hold this generated surface against the LIVE plane
// registry and fail when they disagree — which is what lets this be generated
// from source without the document drifting away from the program. See
// plane_registry_test.go.
var Ops = []string{
	plane.PlatformFleet,
	plane.PlatformPush,
	plane.PlatformRelease,
}

// PlatformFleet every app this org can observe.
//
// Calls plane.PlatformFleet on platform over the peer plane.
func PlatformFleet(ctx context.Context) (*plane.Fleet, error) {
	return plane.Ask[struct{}, plane.Fleet](ctx, App, plane.PlatformFleet, &struct{}{})
}

// PlatformPush turn a landed push into a build for every app tracking it.
//
// Calls plane.PlatformPush on platform over the peer plane.
func PlatformPush(ctx context.Context, in *plane.PushIn) (*plane.Built, error) {
	return plane.Ask[plane.PushIn, plane.Built](ctx, App, plane.PlatformPush, in)
}

// PlatformRelease roll a proven, clean-semver image onto its operator Service CR.
//
// Calls plane.PlatformRelease on platform over the peer plane.
func PlatformRelease(ctx context.Context, in *plane.ReleaseIn) (*plane.Released, error) {
	return plane.Ask[plane.ReleaseIn, plane.Released](ctx, App, plane.PlatformRelease, in)
}
